/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTransactionAccountAssignmentRequestBody } from '../../models/create-transaction-account-assignment-request-body';
import { TransactionAccountAssignment } from '../../models/transaction-account-assignment';

export interface CreateTransactionAccountAssignment$Params {
  transactionId: string;
      body: CreateTransactionAccountAssignmentRequestBody
}

export function createTransactionAccountAssignment(http: HttpClient, rootUrl: string, params: CreateTransactionAccountAssignment$Params, context?: HttpContext): Observable<StrictHttpResponse<TransactionAccountAssignment>> {
  const rb = new RequestBuilder(rootUrl, createTransactionAccountAssignment.PATH, 'post');
  if (params) {
    rb.path('transactionId', params.transactionId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TransactionAccountAssignment>;
    })
  );
}

createTransactionAccountAssignment.PATH = '/v1/transactions/{transactionId}/assignments';
