/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTransactionRequestBody {

  /**
   * A URL to the JSON Schema for this object.
   */
  '$schema'?: string;

  /**
   * Transaction amount as decimal string
   */
  amount: string;

  /**
   * Assigned budget account UUID
   */
  assignedAccountId?: string;

  /**
   * Booking date
   */
  bookedAt: string;

  /**
   * Credit transaction account UUID
   */
  creditTransactionAccountId: string;

  /**
   * Debit transaction account UUID
   */
  debitTransactionAccountId: string;

  /**
   * Transaction description
   */
  description?: string;

  /**
   * Document date
   */
  documentDate: string;

  /**
   * Transaction reference
   */
  reference?: string;
}
