/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTransactionAccountRequestBody {

  /**
   * A URL to the JSON Schema for this object.
   */
  '$schema'?: string;

  /**
   * Unique account code
   */
  code: string;

  /**
   * Optional description
   */
  displayDescription?: string;

  /**
   * Human-readable name
   */
  displayName?: string;

  /**
   * Import source UUID
   */
  importSourceId: string;
}
