/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateAccountGroupAssignmentRequestBody {

  /**
   * A URL to the JSON Schema for this object.
   */
  '$schema'?: string;
  accountId: string;
  negate: boolean;
}
