/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ErrorDetail } from '../models/error-detail';
export interface ErrorModel {

  /**
   * A URL to the JSON Schema for this object.
   */
  '$schema'?: string;

  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;

  /**
   * Optional list of individual error details
   */
  errors?: (Array<ErrorDetail> | null);

  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string;

  /**
   * HTTP status code
   */
  status?: number;

  /**
   * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
   */
  title?: string;

  /**
   * A URI reference to human-readable documentation for the error.
   */
  type?: string;
}
