/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountGroupAssignment } from '../models/account-group-assignment';
export interface ListAccountGroupAssignmentsResponseBody {

  /**
   * A URL to the JSON Schema for this object.
   */
  '$schema'?: string;
  assignments: (Array<AccountGroupAssignment> | null);

  /**
   * Total number of assignments matching the filter
   */
  total: number;
}
