/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TransactionAccountAssignment } from '../models/transaction-account-assignment';
export interface ListTransactionAccountAssignmentsResponseBody {

  /**
   * A URL to the JSON Schema for this object.
   */
  '$schema'?: string;
  assignments: (Array<TransactionAccountAssignment> | null);

  /**
   * Total number of assignments matching the filter
   */
  total: number;
}
