/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountGroup } from '../models/account-group';
export interface ListAccountGroupsResponseBody {

  /**
   * A URL to the JSON Schema for this object.
   */
  '$schema'?: string;
  accountGroups: (Array<AccountGroup> | null);

  /**
   * Total number of account groups matching the filter
   */
  total: number;
}
