/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTransactionAccountRequestBody {

  /**
   * A URL to the JSON Schema for this object.
   */
  '$schema'?: string;

  /**
   * Optional description
   */
  displayDescription?: string;

  /**
   * Human-readable name
   */
  displayName?: string;
}
