/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateReportTemplateRequestBody {

  /**
   * A URL to the JSON Schema for this object.
   */
  '$schema'?: string;

  /**
   * Human-readable name
   */
  displayName?: string;

  /**
   * Handlebars template content
   */
  template?: string;
}
