/* tslint:disable */

/**
 * Permission enumerates every discrete access right in the system.
 * Each value encodes a resource and an action, following the convention
 * RESOURCE_ACTION (all upper-snake-case).
 *
 *  - PERMISSION_DASHBOARD_READ: Dashboard
 *  - PERMISSION_ACCOUNTS_READ: Accounts
 *  - PERMISSION_ACCOUNT_GROUPS_READ: Account Groups
 *  - PERMISSION_BUDGETS_READ: Budgets / Plans
 *  - PERMISSION_JOURNAL_READ: Journal
 *  - PERMISSION_TRANSACTIONS_READ: Transactions
 *  - PERMISSION_MATRIX_READ: Matrix
 *  - PERMISSION_REPORTS_READ: Reports
 *  - PERMISSION_REPORT_TEMPLATES_READ: Report Templates
 *  - PERMISSION_IMPORT_SOURCES_READ: Import Sources
 *  - PERMISSION_USERS_READ: Users
 *  - PERMISSION_GROUPS_READ: Groups
 *  - PERMISSION_SETTINGS_READ: Settings
 */
type V1Permission =
  'PERMISSION_UNSPECIFIED' |
  'PERMISSION_DASHBOARD_READ' |
  'PERMISSION_ACCOUNTS_READ' |
  'PERMISSION_ACCOUNTS_CREATE' |
  'PERMISSION_ACCOUNTS_UPDATE' |
  'PERMISSION_ACCOUNTS_DELETE' |
  'PERMISSION_ACCOUNT_GROUPS_READ' |
  'PERMISSION_ACCOUNT_GROUPS_CREATE' |
  'PERMISSION_ACCOUNT_GROUPS_UPDATE' |
  'PERMISSION_ACCOUNT_GROUPS_DELETE' |
  'PERMISSION_BUDGETS_READ' |
  'PERMISSION_BUDGETS_CREATE' |
  'PERMISSION_BUDGETS_UPDATE' |
  'PERMISSION_BUDGETS_DELETE' |
  'PERMISSION_JOURNAL_READ' |
  'PERMISSION_JOURNAL_IMPORT' |
  'PERMISSION_TRANSACTIONS_READ' |
  'PERMISSION_TRANSACTIONS_UPDATE' |
  'PERMISSION_TRANSACTIONS_DELETE' |
  'PERMISSION_MATRIX_READ' |
  'PERMISSION_MATRIX_UPDATE' |
  'PERMISSION_REPORTS_READ' |
  'PERMISSION_REPORTS_CREATE' |
  'PERMISSION_REPORTS_DELETE' |
  'PERMISSION_REPORT_TEMPLATES_READ' |
  'PERMISSION_REPORT_TEMPLATES_CREATE' |
  'PERMISSION_REPORT_TEMPLATES_UPDATE' |
  'PERMISSION_REPORT_TEMPLATES_DELETE' |
  'PERMISSION_IMPORT_SOURCES_READ' |
  'PERMISSION_IMPORT_SOURCES_CREATE' |
  'PERMISSION_IMPORT_SOURCES_UPDATE' |
  'PERMISSION_USERS_READ' |
  'PERMISSION_USERS_UPDATE' |
  'PERMISSION_GROUPS_READ' |
  'PERMISSION_GROUPS_CREATE' |
  'PERMISSION_GROUPS_UPDATE' |
  'PERMISSION_GROUPS_DELETE' |
  'PERMISSION_SETTINGS_READ' |
  'PERMISSION_SETTINGS_UPDATE';
module V1Permission {
  export const PERMISSION_UNSPECIFIED: V1Permission = 'PERMISSION_UNSPECIFIED';
  export const PERMISSION_DASHBOARD_READ: V1Permission = 'PERMISSION_DASHBOARD_READ';
  export const PERMISSION_ACCOUNTS_READ: V1Permission = 'PERMISSION_ACCOUNTS_READ';
  export const PERMISSION_ACCOUNTS_CREATE: V1Permission = 'PERMISSION_ACCOUNTS_CREATE';
  export const PERMISSION_ACCOUNTS_UPDATE: V1Permission = 'PERMISSION_ACCOUNTS_UPDATE';
  export const PERMISSION_ACCOUNTS_DELETE: V1Permission = 'PERMISSION_ACCOUNTS_DELETE';
  export const PERMISSION_ACCOUNT_GROUPS_READ: V1Permission = 'PERMISSION_ACCOUNT_GROUPS_READ';
  export const PERMISSION_ACCOUNT_GROUPS_CREATE: V1Permission = 'PERMISSION_ACCOUNT_GROUPS_CREATE';
  export const PERMISSION_ACCOUNT_GROUPS_UPDATE: V1Permission = 'PERMISSION_ACCOUNT_GROUPS_UPDATE';
  export const PERMISSION_ACCOUNT_GROUPS_DELETE: V1Permission = 'PERMISSION_ACCOUNT_GROUPS_DELETE';
  export const PERMISSION_BUDGETS_READ: V1Permission = 'PERMISSION_BUDGETS_READ';
  export const PERMISSION_BUDGETS_CREATE: V1Permission = 'PERMISSION_BUDGETS_CREATE';
  export const PERMISSION_BUDGETS_UPDATE: V1Permission = 'PERMISSION_BUDGETS_UPDATE';
  export const PERMISSION_BUDGETS_DELETE: V1Permission = 'PERMISSION_BUDGETS_DELETE';
  export const PERMISSION_JOURNAL_READ: V1Permission = 'PERMISSION_JOURNAL_READ';
  export const PERMISSION_JOURNAL_IMPORT: V1Permission = 'PERMISSION_JOURNAL_IMPORT';
  export const PERMISSION_TRANSACTIONS_READ: V1Permission = 'PERMISSION_TRANSACTIONS_READ';
  export const PERMISSION_TRANSACTIONS_UPDATE: V1Permission = 'PERMISSION_TRANSACTIONS_UPDATE';
  export const PERMISSION_TRANSACTIONS_DELETE: V1Permission = 'PERMISSION_TRANSACTIONS_DELETE';
  export const PERMISSION_MATRIX_READ: V1Permission = 'PERMISSION_MATRIX_READ';
  export const PERMISSION_MATRIX_UPDATE: V1Permission = 'PERMISSION_MATRIX_UPDATE';
  export const PERMISSION_REPORTS_READ: V1Permission = 'PERMISSION_REPORTS_READ';
  export const PERMISSION_REPORTS_CREATE: V1Permission = 'PERMISSION_REPORTS_CREATE';
  export const PERMISSION_REPORTS_DELETE: V1Permission = 'PERMISSION_REPORTS_DELETE';
  export const PERMISSION_REPORT_TEMPLATES_READ: V1Permission = 'PERMISSION_REPORT_TEMPLATES_READ';
  export const PERMISSION_REPORT_TEMPLATES_CREATE: V1Permission = 'PERMISSION_REPORT_TEMPLATES_CREATE';
  export const PERMISSION_REPORT_TEMPLATES_UPDATE: V1Permission = 'PERMISSION_REPORT_TEMPLATES_UPDATE';
  export const PERMISSION_REPORT_TEMPLATES_DELETE: V1Permission = 'PERMISSION_REPORT_TEMPLATES_DELETE';
  export const PERMISSION_IMPORT_SOURCES_READ: V1Permission = 'PERMISSION_IMPORT_SOURCES_READ';
  export const PERMISSION_IMPORT_SOURCES_CREATE: V1Permission = 'PERMISSION_IMPORT_SOURCES_CREATE';
  export const PERMISSION_IMPORT_SOURCES_UPDATE: V1Permission = 'PERMISSION_IMPORT_SOURCES_UPDATE';
  export const PERMISSION_USERS_READ: V1Permission = 'PERMISSION_USERS_READ';
  export const PERMISSION_USERS_UPDATE: V1Permission = 'PERMISSION_USERS_UPDATE';
  export const PERMISSION_GROUPS_READ: V1Permission = 'PERMISSION_GROUPS_READ';
  export const PERMISSION_GROUPS_CREATE: V1Permission = 'PERMISSION_GROUPS_CREATE';
  export const PERMISSION_GROUPS_UPDATE: V1Permission = 'PERMISSION_GROUPS_UPDATE';
  export const PERMISSION_GROUPS_DELETE: V1Permission = 'PERMISSION_GROUPS_DELETE';
  export const PERMISSION_SETTINGS_READ: V1Permission = 'PERMISSION_SETTINGS_READ';
  export const PERMISSION_SETTINGS_UPDATE: V1Permission = 'PERMISSION_SETTINGS_UPDATE';
  export function values(): V1Permission[] {
    return [
      PERMISSION_UNSPECIFIED,
      PERMISSION_DASHBOARD_READ,
      PERMISSION_ACCOUNTS_READ,
      PERMISSION_ACCOUNTS_CREATE,
      PERMISSION_ACCOUNTS_UPDATE,
      PERMISSION_ACCOUNTS_DELETE,
      PERMISSION_ACCOUNT_GROUPS_READ,
      PERMISSION_ACCOUNT_GROUPS_CREATE,
      PERMISSION_ACCOUNT_GROUPS_UPDATE,
      PERMISSION_ACCOUNT_GROUPS_DELETE,
      PERMISSION_BUDGETS_READ,
      PERMISSION_BUDGETS_CREATE,
      PERMISSION_BUDGETS_UPDATE,
      PERMISSION_BUDGETS_DELETE,
      PERMISSION_JOURNAL_READ,
      PERMISSION_JOURNAL_IMPORT,
      PERMISSION_TRANSACTIONS_READ,
      PERMISSION_TRANSACTIONS_UPDATE,
      PERMISSION_TRANSACTIONS_DELETE,
      PERMISSION_MATRIX_READ,
      PERMISSION_MATRIX_UPDATE,
      PERMISSION_REPORTS_READ,
      PERMISSION_REPORTS_CREATE,
      PERMISSION_REPORTS_DELETE,
      PERMISSION_REPORT_TEMPLATES_READ,
      PERMISSION_REPORT_TEMPLATES_CREATE,
      PERMISSION_REPORT_TEMPLATES_UPDATE,
      PERMISSION_REPORT_TEMPLATES_DELETE,
      PERMISSION_IMPORT_SOURCES_READ,
      PERMISSION_IMPORT_SOURCES_CREATE,
      PERMISSION_IMPORT_SOURCES_UPDATE,
      PERMISSION_USERS_READ,
      PERMISSION_USERS_UPDATE,
      PERMISSION_GROUPS_READ,
      PERMISSION_GROUPS_CREATE,
      PERMISSION_GROUPS_UPDATE,
      PERMISSION_GROUPS_DELETE,
      PERMISSION_SETTINGS_READ,
      PERMISSION_SETTINGS_UPDATE
    ];
  }
}

export { V1Permission }