/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReportTemplate } from '../../models/report-template';

export interface GetReportTemplate$Params {

/**
 * Report template UUID
 */
  reportTemplateId: string;
}

export function getReportTemplate(http: HttpClient, rootUrl: string, params: GetReportTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<ReportTemplate>> {
  const rb = new RequestBuilder(rootUrl, getReportTemplate.PATH, 'get');
  if (params) {
    rb.path('reportTemplateId', params.reportTemplateId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReportTemplate>;
    })
  );
}

getReportTemplate.PATH = '/v1/reportTemplates/{reportTemplateId}';
