name: vsfv-production

services:
  app-migrate:
    image: pixlcrashr/vsfv:${VERSION:-latest}
    restart: "no"
    environment:
      TZ: Europe/Berlin
      DB_URL: ${DB_URL}
    entrypoint: ["./node_modules/.bin/prisma"]
    command: ["migrate", "deploy"]
    networks:
      - internal
  app:
    image: pixlcrashr/vsfv:${VERSION:-latest}
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      HOST: 0.0.0.0
      PORT: 3000
      DB_URL: ${DB_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID}
      GITLAB_CLIENT_SECRET: ${GITLAB_CLIENT_SECRET}
      GITLAB_ISSUER: ${GITLAB_ISSUER}
      ORGANISATION_NAME: ${ORGANISATION_NAME}
      GOTENBERG_URL: http://gotenberg:3000
    depends_on:
      app-migrate:
        condition: service_completed_successfully
      gotenberg:
        condition: service_started
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - internal
  gotenberg:
    image: gotenberg/gotenberg:8
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - internal

networks:
  internal:
