name: vsfv-dev

services:
  development-db:
    image: postgres:18
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      POSTGRES_DB: vsf
      POSTGRES_USER: vsf
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5334:5432
  test-db:
    image: postgres:18
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      POSTGRES_DB: vsf
      POSTGRES_USER: vsf
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5335:5432
  gotenberg:
    image: gotenberg/gotenberg:8
    restart: unless-stopped
    ports:
      - 127.0.0.1:8090:3000
