// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"github.com/pixlcrashr/vsfv/pkg/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newBudgetTagAccountValue(db *gorm.DB, opts ...gen.DOOption) budgetTagAccountValue {
	_budgetTagAccountValue := budgetTagAccountValue{}

	_budgetTagAccountValue.budgetTagAccountValueDo.UseDB(db, opts...)
	_budgetTagAccountValue.budgetTagAccountValueDo.UseModel(&model.BudgetTagAccountValue{})

	tableName := _budgetTagAccountValue.budgetTagAccountValueDo.TableName()
	_budgetTagAccountValue.ALL = field.NewAsterisk(tableName)
	_budgetTagAccountValue.ID = field.NewField(tableName, "id")
	_budgetTagAccountValue.OrganizationID = field.NewField(tableName, "organization_id")
	_budgetTagAccountValue.BudgetTagID = field.NewField(tableName, "budget_tag_id")
	_budgetTagAccountValue.AccountID = field.NewField(tableName, "account_id")
	_budgetTagAccountValue.Value = field.NewField(tableName, "value")
	_budgetTagAccountValue.UpdatedAt = field.NewTime(tableName, "updated_at")
	_budgetTagAccountValue.CreatedAt = field.NewTime(tableName, "created_at")
	_budgetTagAccountValue.Organization = budgetTagAccountValueBelongsToOrganization{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Organization", "model.Organization"),
		AccountGroupAssignments: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			AccountGroup struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}
			Account struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
				BudgetTagAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					BudgetTag struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetTags struct {
								field.RelationField
							}
						}
						BudgetTagAccountValues struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
				TransactionAccountAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditTransactionAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							ImportSource struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								TransactionAccounts struct {
									field.RelationField
								}
								ImportSourcePeriods struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									ImportSource struct {
										field.RelationField
									}
								}
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitTransactionAccount struct {
							field.RelationField
						}
						TransactionAccountAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
			}
		}{
			RelationField: field.NewRelation("Organization.AccountGroupAssignments", "model.AccountGroupAssignment"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.AccountGroupAssignments.Organization", "model.Organization"),
			},
			AccountGroup: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Organization.AccountGroupAssignments.AccountGroup", "model.AccountGroup"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.AccountGroup.Organization", "model.Organization"),
				},
				AccountGroupAssignments: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.AccountGroup.AccountGroupAssignments", "model.AccountGroupAssignment"),
				},
			},
			Account: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
				BudgetTagAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					BudgetTag struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetTags struct {
								field.RelationField
							}
						}
						BudgetTagAccountValues struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
				TransactionAccountAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditTransactionAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							ImportSource struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								TransactionAccounts struct {
									field.RelationField
								}
								ImportSourcePeriods struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									ImportSource struct {
										field.RelationField
									}
								}
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitTransactionAccount struct {
							field.RelationField
						}
						TransactionAccountAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account", "model.Account"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.Organization", "model.Organization"),
				},
				ParentAccount: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.ParentAccount", "model.Account"),
				},
				ChildAccounts: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.ChildAccounts", "model.Account"),
				},
				AccountGroupAssignments: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.AccountGroupAssignments", "model.AccountGroupAssignment"),
				},
				BudgetTagAccountValues: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					BudgetTag struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetTags struct {
								field.RelationField
							}
						}
						BudgetTagAccountValues struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetTagAccountValues", "model.BudgetTagAccountValue"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.Organization", "model.Organization"),
					},
					BudgetTag: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetTags struct {
								field.RelationField
							}
						}
						BudgetTagAccountValues struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.BudgetTag", "model.BudgetTag"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.BudgetTag.Organization", "model.Organization"),
						},
						Budget: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetTags struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.BudgetTag.Budget", "model.Budget"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.BudgetTag.Budget.Organization", "model.Organization"),
							},
							BudgetTags: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.BudgetTag.Budget.BudgetTags", "model.BudgetTag"),
							},
						},
						BudgetTagAccountValues: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.BudgetTag.BudgetTagAccountValues", "model.BudgetTagAccountValue"),
						},
					},
					Account: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.Account", "model.Account"),
					},
				},
				TransactionAccountAssignments: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditTransactionAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							ImportSource struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								TransactionAccounts struct {
									field.RelationField
								}
								ImportSourcePeriods struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									ImportSource struct {
										field.RelationField
									}
								}
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitTransactionAccount struct {
							field.RelationField
						}
						TransactionAccountAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Organization", "model.Organization"),
					},
					Transaction: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditTransactionAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							ImportSource struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								TransactionAccounts struct {
									field.RelationField
								}
								ImportSourcePeriods struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									ImportSource struct {
										field.RelationField
									}
								}
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitTransactionAccount struct {
							field.RelationField
						}
						TransactionAccountAssignments struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction", "model.Transaction_"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.Organization", "model.Organization"),
						},
						CreditTransactionAccount: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							ImportSource struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								TransactionAccounts struct {
									field.RelationField
								}
								ImportSourcePeriods struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									ImportSource struct {
										field.RelationField
									}
								}
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount", "model.TransactionAccount"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.Organization", "model.Organization"),
							},
							ImportSource: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								TransactionAccounts struct {
									field.RelationField
								}
								ImportSourcePeriods struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									ImportSource struct {
										field.RelationField
									}
								}
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource", "model.ImportSource"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.Organization", "model.Organization"),
								},
								TransactionAccounts: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.TransactionAccounts", "model.TransactionAccount"),
								},
								ImportSourcePeriods: struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									ImportSource struct {
										field.RelationField
									}
								}{
									RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.ImportSourcePeriods", "model.ImportSourcePeriod"),
									Organization: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.ImportSourcePeriods.Organization", "model.Organization"),
									},
									ImportSource: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.ImportSourcePeriods.ImportSource", "model.ImportSource"),
									},
								},
							},
							CreditTransactions: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.CreditTransactions", "model.Transaction_"),
							},
							DebitTransactions: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.DebitTransactions", "model.Transaction_"),
							},
						},
						DebitTransactionAccount: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.DebitTransactionAccount", "model.TransactionAccount"),
						},
						TransactionAccountAssignments: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
						},
					},
					Account: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Account", "model.Account"),
					},
				},
			},
		},
		AccountGroups: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.AccountGroups", "model.AccountGroup"),
		},
		Accounts: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.Accounts", "model.Account"),
		},
		BudgetTags: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.BudgetTags", "model.BudgetTag"),
		},
		BudgetTagAccountValues: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.BudgetTagAccountValues", "model.BudgetTagAccountValue"),
		},
		Budgets: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.Budgets", "model.Budget"),
		},
		ImportSourcePeriods: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.ImportSourcePeriods", "model.ImportSourcePeriod"),
		},
		ImportSources: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.ImportSources", "model.ImportSource"),
		},
		ReportTemplates: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Organization.ReportTemplates", "model.ReportTemplate"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.ReportTemplates.Organization", "model.Organization"),
			},
		},
		Reports: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Organization.Reports", "model.Report"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.Reports.Organization", "model.Organization"),
			},
		},
		Transactions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.Transactions", "model.Transaction_"),
		},
		TransactionAccountAssignments: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
		},
		TransactionAccounts: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.TransactionAccounts", "model.TransactionAccount"),
		},
	}

	_budgetTagAccountValue.BudgetTag = budgetTagAccountValueBelongsToBudgetTag{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("BudgetTag", "model.BudgetTag"),
	}

	_budgetTagAccountValue.Account = budgetTagAccountValueBelongsToAccount{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Account", "model.Account"),
	}

	_budgetTagAccountValue.fillFieldMap()

	return _budgetTagAccountValue
}

type budgetTagAccountValue struct {
	budgetTagAccountValueDo budgetTagAccountValueDo

	ALL            field.Asterisk
	ID             field.Field
	OrganizationID field.Field
	BudgetTagID    field.Field
	AccountID      field.Field
	Value          field.Field
	UpdatedAt      field.Time
	CreatedAt      field.Time
	Organization   budgetTagAccountValueBelongsToOrganization

	BudgetTag budgetTagAccountValueBelongsToBudgetTag

	Account budgetTagAccountValueBelongsToAccount

	fieldMap map[string]field.Expr
}

func (b budgetTagAccountValue) Table(newTableName string) *budgetTagAccountValue {
	b.budgetTagAccountValueDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b budgetTagAccountValue) As(alias string) *budgetTagAccountValue {
	b.budgetTagAccountValueDo.DO = *(b.budgetTagAccountValueDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *budgetTagAccountValue) updateTableName(table string) *budgetTagAccountValue {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewField(table, "id")
	b.OrganizationID = field.NewField(table, "organization_id")
	b.BudgetTagID = field.NewField(table, "budget_tag_id")
	b.AccountID = field.NewField(table, "account_id")
	b.Value = field.NewField(table, "value")
	b.UpdatedAt = field.NewTime(table, "updated_at")
	b.CreatedAt = field.NewTime(table, "created_at")

	b.fillFieldMap()

	return b
}

func (b *budgetTagAccountValue) WithContext(ctx context.Context) IBudgetTagAccountValueDo {
	return b.budgetTagAccountValueDo.WithContext(ctx)
}

func (b budgetTagAccountValue) TableName() string { return b.budgetTagAccountValueDo.TableName() }

func (b budgetTagAccountValue) Alias() string { return b.budgetTagAccountValueDo.Alias() }

func (b budgetTagAccountValue) Columns(cols ...field.Expr) gen.Columns {
	return b.budgetTagAccountValueDo.Columns(cols...)
}

func (b *budgetTagAccountValue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *budgetTagAccountValue) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 10)
	b.fieldMap["id"] = b.ID
	b.fieldMap["organization_id"] = b.OrganizationID
	b.fieldMap["budget_tag_id"] = b.BudgetTagID
	b.fieldMap["account_id"] = b.AccountID
	b.fieldMap["value"] = b.Value
	b.fieldMap["updated_at"] = b.UpdatedAt
	b.fieldMap["created_at"] = b.CreatedAt

}

func (b budgetTagAccountValue) clone(db *gorm.DB) budgetTagAccountValue {
	b.budgetTagAccountValueDo.ReplaceConnPool(db.Statement.ConnPool)
	b.Organization.db = db.Session(&gorm.Session{Initialized: true})
	b.Organization.db.Statement.ConnPool = db.Statement.ConnPool
	b.BudgetTag.db = db.Session(&gorm.Session{Initialized: true})
	b.BudgetTag.db.Statement.ConnPool = db.Statement.ConnPool
	b.Account.db = db.Session(&gorm.Session{Initialized: true})
	b.Account.db.Statement.ConnPool = db.Statement.ConnPool
	return b
}

func (b budgetTagAccountValue) replaceDB(db *gorm.DB) budgetTagAccountValue {
	b.budgetTagAccountValueDo.ReplaceDB(db)
	b.Organization.db = db.Session(&gorm.Session{})
	b.BudgetTag.db = db.Session(&gorm.Session{})
	b.Account.db = db.Session(&gorm.Session{})
	return b
}

type budgetTagAccountValueBelongsToOrganization struct {
	db *gorm.DB

	field.RelationField

	AccountGroupAssignments struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
		AccountGroup struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			AccountGroupAssignments struct {
				field.RelationField
			}
		}
		Account struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			ParentAccount struct {
				field.RelationField
			}
			ChildAccounts struct {
				field.RelationField
			}
			AccountGroupAssignments struct {
				field.RelationField
			}
			BudgetTagAccountValues struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				BudgetTag struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetTags struct {
							field.RelationField
						}
					}
					BudgetTagAccountValues struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
				}
			}
			TransactionAccountAssignments struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Transaction struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					CreditTransactionAccount struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						ImportSource struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							TransactionAccounts struct {
								field.RelationField
							}
							ImportSourcePeriods struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								ImportSource struct {
									field.RelationField
								}
							}
						}
						CreditTransactions struct {
							field.RelationField
						}
						DebitTransactions struct {
							field.RelationField
						}
					}
					DebitTransactionAccount struct {
						field.RelationField
					}
					TransactionAccountAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
				}
			}
		}
	}
	AccountGroups struct {
		field.RelationField
	}
	Accounts struct {
		field.RelationField
	}
	BudgetTags struct {
		field.RelationField
	}
	BudgetTagAccountValues struct {
		field.RelationField
	}
	Budgets struct {
		field.RelationField
	}
	ImportSourcePeriods struct {
		field.RelationField
	}
	ImportSources struct {
		field.RelationField
	}
	ReportTemplates struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
	}
	Reports struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
	}
	Transactions struct {
		field.RelationField
	}
	TransactionAccountAssignments struct {
		field.RelationField
	}
	TransactionAccounts struct {
		field.RelationField
	}
}

func (a budgetTagAccountValueBelongsToOrganization) Where(conds ...field.Expr) *budgetTagAccountValueBelongsToOrganization {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a budgetTagAccountValueBelongsToOrganization) WithContext(ctx context.Context) *budgetTagAccountValueBelongsToOrganization {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a budgetTagAccountValueBelongsToOrganization) Session(session *gorm.Session) *budgetTagAccountValueBelongsToOrganization {
	a.db = a.db.Session(session)
	return &a
}

func (a budgetTagAccountValueBelongsToOrganization) Model(m *model.BudgetTagAccountValue) *budgetTagAccountValueBelongsToOrganizationTx {
	return &budgetTagAccountValueBelongsToOrganizationTx{a.db.Model(m).Association(a.Name())}
}

func (a budgetTagAccountValueBelongsToOrganization) Unscoped() *budgetTagAccountValueBelongsToOrganization {
	a.db = a.db.Unscoped()
	return &a
}

type budgetTagAccountValueBelongsToOrganizationTx struct{ tx *gorm.Association }

func (a budgetTagAccountValueBelongsToOrganizationTx) Find() (result *model.Organization, err error) {
	return result, a.tx.Find(&result)
}

func (a budgetTagAccountValueBelongsToOrganizationTx) Append(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a budgetTagAccountValueBelongsToOrganizationTx) Replace(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a budgetTagAccountValueBelongsToOrganizationTx) Delete(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a budgetTagAccountValueBelongsToOrganizationTx) Clear() error {
	return a.tx.Clear()
}

func (a budgetTagAccountValueBelongsToOrganizationTx) Count() int64 {
	return a.tx.Count()
}

func (a budgetTagAccountValueBelongsToOrganizationTx) Unscoped() *budgetTagAccountValueBelongsToOrganizationTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type budgetTagAccountValueBelongsToBudgetTag struct {
	db *gorm.DB

	field.RelationField
}

func (a budgetTagAccountValueBelongsToBudgetTag) Where(conds ...field.Expr) *budgetTagAccountValueBelongsToBudgetTag {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a budgetTagAccountValueBelongsToBudgetTag) WithContext(ctx context.Context) *budgetTagAccountValueBelongsToBudgetTag {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a budgetTagAccountValueBelongsToBudgetTag) Session(session *gorm.Session) *budgetTagAccountValueBelongsToBudgetTag {
	a.db = a.db.Session(session)
	return &a
}

func (a budgetTagAccountValueBelongsToBudgetTag) Model(m *model.BudgetTagAccountValue) *budgetTagAccountValueBelongsToBudgetTagTx {
	return &budgetTagAccountValueBelongsToBudgetTagTx{a.db.Model(m).Association(a.Name())}
}

func (a budgetTagAccountValueBelongsToBudgetTag) Unscoped() *budgetTagAccountValueBelongsToBudgetTag {
	a.db = a.db.Unscoped()
	return &a
}

type budgetTagAccountValueBelongsToBudgetTagTx struct{ tx *gorm.Association }

func (a budgetTagAccountValueBelongsToBudgetTagTx) Find() (result *model.BudgetTag, err error) {
	return result, a.tx.Find(&result)
}

func (a budgetTagAccountValueBelongsToBudgetTagTx) Append(values ...*model.BudgetTag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a budgetTagAccountValueBelongsToBudgetTagTx) Replace(values ...*model.BudgetTag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a budgetTagAccountValueBelongsToBudgetTagTx) Delete(values ...*model.BudgetTag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a budgetTagAccountValueBelongsToBudgetTagTx) Clear() error {
	return a.tx.Clear()
}

func (a budgetTagAccountValueBelongsToBudgetTagTx) Count() int64 {
	return a.tx.Count()
}

func (a budgetTagAccountValueBelongsToBudgetTagTx) Unscoped() *budgetTagAccountValueBelongsToBudgetTagTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type budgetTagAccountValueBelongsToAccount struct {
	db *gorm.DB

	field.RelationField
}

func (a budgetTagAccountValueBelongsToAccount) Where(conds ...field.Expr) *budgetTagAccountValueBelongsToAccount {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a budgetTagAccountValueBelongsToAccount) WithContext(ctx context.Context) *budgetTagAccountValueBelongsToAccount {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a budgetTagAccountValueBelongsToAccount) Session(session *gorm.Session) *budgetTagAccountValueBelongsToAccount {
	a.db = a.db.Session(session)
	return &a
}

func (a budgetTagAccountValueBelongsToAccount) Model(m *model.BudgetTagAccountValue) *budgetTagAccountValueBelongsToAccountTx {
	return &budgetTagAccountValueBelongsToAccountTx{a.db.Model(m).Association(a.Name())}
}

func (a budgetTagAccountValueBelongsToAccount) Unscoped() *budgetTagAccountValueBelongsToAccount {
	a.db = a.db.Unscoped()
	return &a
}

type budgetTagAccountValueBelongsToAccountTx struct{ tx *gorm.Association }

func (a budgetTagAccountValueBelongsToAccountTx) Find() (result *model.Account, err error) {
	return result, a.tx.Find(&result)
}

func (a budgetTagAccountValueBelongsToAccountTx) Append(values ...*model.Account) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a budgetTagAccountValueBelongsToAccountTx) Replace(values ...*model.Account) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a budgetTagAccountValueBelongsToAccountTx) Delete(values ...*model.Account) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a budgetTagAccountValueBelongsToAccountTx) Clear() error {
	return a.tx.Clear()
}

func (a budgetTagAccountValueBelongsToAccountTx) Count() int64 {
	return a.tx.Count()
}

func (a budgetTagAccountValueBelongsToAccountTx) Unscoped() *budgetTagAccountValueBelongsToAccountTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type budgetTagAccountValueDo struct{ gen.DO }

type IBudgetTagAccountValueDo interface {
	gen.SubQuery
	Debug() IBudgetTagAccountValueDo
	WithContext(ctx context.Context) IBudgetTagAccountValueDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBudgetTagAccountValueDo
	WriteDB() IBudgetTagAccountValueDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBudgetTagAccountValueDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBudgetTagAccountValueDo
	Not(conds ...gen.Condition) IBudgetTagAccountValueDo
	Or(conds ...gen.Condition) IBudgetTagAccountValueDo
	Select(conds ...field.Expr) IBudgetTagAccountValueDo
	Where(conds ...gen.Condition) IBudgetTagAccountValueDo
	Order(conds ...field.Expr) IBudgetTagAccountValueDo
	Distinct(cols ...field.Expr) IBudgetTagAccountValueDo
	Omit(cols ...field.Expr) IBudgetTagAccountValueDo
	Join(table schema.Tabler, on ...field.Expr) IBudgetTagAccountValueDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBudgetTagAccountValueDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBudgetTagAccountValueDo
	Group(cols ...field.Expr) IBudgetTagAccountValueDo
	Having(conds ...gen.Condition) IBudgetTagAccountValueDo
	Limit(limit int) IBudgetTagAccountValueDo
	Offset(offset int) IBudgetTagAccountValueDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBudgetTagAccountValueDo
	Unscoped() IBudgetTagAccountValueDo
	Create(values ...*model.BudgetTagAccountValue) error
	CreateInBatches(values []*model.BudgetTagAccountValue, batchSize int) error
	Save(values ...*model.BudgetTagAccountValue) error
	First() (*model.BudgetTagAccountValue, error)
	Take() (*model.BudgetTagAccountValue, error)
	Last() (*model.BudgetTagAccountValue, error)
	Find() ([]*model.BudgetTagAccountValue, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BudgetTagAccountValue, err error)
	FindInBatches(result *[]*model.BudgetTagAccountValue, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BudgetTagAccountValue) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBudgetTagAccountValueDo
	Assign(attrs ...field.AssignExpr) IBudgetTagAccountValueDo
	Joins(fields ...field.RelationField) IBudgetTagAccountValueDo
	Preload(fields ...field.RelationField) IBudgetTagAccountValueDo
	FirstOrInit() (*model.BudgetTagAccountValue, error)
	FirstOrCreate() (*model.BudgetTagAccountValue, error)
	FindByPage(offset int, limit int) (result []*model.BudgetTagAccountValue, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBudgetTagAccountValueDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b budgetTagAccountValueDo) Debug() IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Debug())
}

func (b budgetTagAccountValueDo) WithContext(ctx context.Context) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b budgetTagAccountValueDo) ReadDB() IBudgetTagAccountValueDo {
	return b.Clauses(dbresolver.Read)
}

func (b budgetTagAccountValueDo) WriteDB() IBudgetTagAccountValueDo {
	return b.Clauses(dbresolver.Write)
}

func (b budgetTagAccountValueDo) Session(config *gorm.Session) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Session(config))
}

func (b budgetTagAccountValueDo) Clauses(conds ...clause.Expression) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b budgetTagAccountValueDo) Returning(value interface{}, columns ...string) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b budgetTagAccountValueDo) Not(conds ...gen.Condition) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b budgetTagAccountValueDo) Or(conds ...gen.Condition) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b budgetTagAccountValueDo) Select(conds ...field.Expr) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b budgetTagAccountValueDo) Where(conds ...gen.Condition) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b budgetTagAccountValueDo) Order(conds ...field.Expr) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b budgetTagAccountValueDo) Distinct(cols ...field.Expr) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b budgetTagAccountValueDo) Omit(cols ...field.Expr) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b budgetTagAccountValueDo) Join(table schema.Tabler, on ...field.Expr) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b budgetTagAccountValueDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b budgetTagAccountValueDo) RightJoin(table schema.Tabler, on ...field.Expr) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b budgetTagAccountValueDo) Group(cols ...field.Expr) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b budgetTagAccountValueDo) Having(conds ...gen.Condition) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b budgetTagAccountValueDo) Limit(limit int) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b budgetTagAccountValueDo) Offset(offset int) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b budgetTagAccountValueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b budgetTagAccountValueDo) Unscoped() IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Unscoped())
}

func (b budgetTagAccountValueDo) Create(values ...*model.BudgetTagAccountValue) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b budgetTagAccountValueDo) CreateInBatches(values []*model.BudgetTagAccountValue, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b budgetTagAccountValueDo) Save(values ...*model.BudgetTagAccountValue) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b budgetTagAccountValueDo) First() (*model.BudgetTagAccountValue, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BudgetTagAccountValue), nil
	}
}

func (b budgetTagAccountValueDo) Take() (*model.BudgetTagAccountValue, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BudgetTagAccountValue), nil
	}
}

func (b budgetTagAccountValueDo) Last() (*model.BudgetTagAccountValue, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BudgetTagAccountValue), nil
	}
}

func (b budgetTagAccountValueDo) Find() ([]*model.BudgetTagAccountValue, error) {
	result, err := b.DO.Find()
	return result.([]*model.BudgetTagAccountValue), err
}

func (b budgetTagAccountValueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BudgetTagAccountValue, err error) {
	buf := make([]*model.BudgetTagAccountValue, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b budgetTagAccountValueDo) FindInBatches(result *[]*model.BudgetTagAccountValue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b budgetTagAccountValueDo) Attrs(attrs ...field.AssignExpr) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b budgetTagAccountValueDo) Assign(attrs ...field.AssignExpr) IBudgetTagAccountValueDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b budgetTagAccountValueDo) Joins(fields ...field.RelationField) IBudgetTagAccountValueDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b budgetTagAccountValueDo) Preload(fields ...field.RelationField) IBudgetTagAccountValueDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b budgetTagAccountValueDo) FirstOrInit() (*model.BudgetTagAccountValue, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BudgetTagAccountValue), nil
	}
}

func (b budgetTagAccountValueDo) FirstOrCreate() (*model.BudgetTagAccountValue, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BudgetTagAccountValue), nil
	}
}

func (b budgetTagAccountValueDo) FindByPage(offset int, limit int) (result []*model.BudgetTagAccountValue, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b budgetTagAccountValueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b budgetTagAccountValueDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b budgetTagAccountValueDo) Delete(models ...*model.BudgetTagAccountValue) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *budgetTagAccountValueDo) withDO(do gen.Dao) *budgetTagAccountValueDo {
	b.DO = *do.(*gen.DO)
	return b
}
