// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"github.com/pixlcrashr/vsfv/pkg/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newBudget(db *gorm.DB, opts ...gen.DOOption) budget {
	_budget := budget{}

	_budget.budgetDo.UseDB(db, opts...)
	_budget.budgetDo.UseModel(&model.Budget{})

	tableName := _budget.budgetDo.TableName()
	_budget.ALL = field.NewAsterisk(tableName)
	_budget.ID = field.NewField(tableName, "id")
	_budget.OrganizationID = field.NewField(tableName, "organization_id")
	_budget.DisplayName = field.NewString(tableName, "display_name")
	_budget.DisplayDescription = field.NewString(tableName, "display_description")
	_budget.IsClosed = field.NewBool(tableName, "is_closed")
	_budget.PeriodStart = field.NewTime(tableName, "period_start")
	_budget.PeriodEnd = field.NewTime(tableName, "period_end")
	_budget.UpdatedAt = field.NewTime(tableName, "updated_at")
	_budget.CreatedAt = field.NewTime(tableName, "created_at")
	_budget.BudgetTags = budgetHasManyBudgetTags{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("BudgetTags", "model.BudgetTag"),
		Organization: struct {
			field.RelationField
			AccountGroupAssignments struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetTagAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetTag struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
					TransactionAccountAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactionAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								ImportSource struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									TransactionAccounts struct {
										field.RelationField
									}
									ImportSourcePeriods struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										ImportSource struct {
											field.RelationField
										}
									}
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitTransactionAccount struct {
								field.RelationField
							}
							TransactionAccountAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}
				}
			}
			AccountGroups struct {
				field.RelationField
			}
			Accounts struct {
				field.RelationField
			}
			BudgetTags struct {
				field.RelationField
			}
			BudgetTagAccountValues struct {
				field.RelationField
			}
			Budgets struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				BudgetTags struct {
					field.RelationField
				}
			}
			ImportSourcePeriods struct {
				field.RelationField
			}
			ImportSources struct {
				field.RelationField
			}
			ReportTemplates struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Reports struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Transactions struct {
				field.RelationField
			}
			TransactionAccountAssignments struct {
				field.RelationField
			}
			TransactionAccounts struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("BudgetTags.Organization", "model.Organization"),
			AccountGroupAssignments: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetTagAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetTag struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
					TransactionAccountAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactionAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								ImportSource struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									TransactionAccounts struct {
										field.RelationField
									}
									ImportSourcePeriods struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										ImportSource struct {
											field.RelationField
										}
									}
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitTransactionAccount struct {
								field.RelationField
							}
							TransactionAccountAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments", "model.AccountGroupAssignment"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Organization", "model.Organization"),
				},
				AccountGroup: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.AccountGroup", "model.AccountGroup"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.AccountGroup.Organization", "model.Organization"),
					},
					AccountGroupAssignments: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.AccountGroup.AccountGroupAssignments", "model.AccountGroupAssignment"),
					},
				},
				Account: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetTagAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetTag struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
					TransactionAccountAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactionAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								ImportSource struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									TransactionAccounts struct {
										field.RelationField
									}
									ImportSourcePeriods struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										ImportSource struct {
											field.RelationField
										}
									}
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitTransactionAccount struct {
								field.RelationField
							}
							TransactionAccountAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account", "model.Account"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.Organization", "model.Organization"),
					},
					ParentAccount: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.ParentAccount", "model.Account"),
					},
					ChildAccounts: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.ChildAccounts", "model.Account"),
					},
					AccountGroupAssignments: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.AccountGroupAssignments", "model.AccountGroupAssignment"),
					},
					BudgetTagAccountValues: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetTag struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.BudgetTagAccountValues", "model.BudgetTagAccountValue"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.Organization", "model.Organization"),
						},
						BudgetTag: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.BudgetTag", "model.BudgetTag"),
						},
						Account: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.Account", "model.Account"),
						},
					},
					TransactionAccountAssignments: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactionAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								ImportSource struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									TransactionAccounts struct {
										field.RelationField
									}
									ImportSourcePeriods struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										ImportSource struct {
											field.RelationField
										}
									}
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitTransactionAccount struct {
								field.RelationField
							}
							TransactionAccountAssignments struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Organization", "model.Organization"),
						},
						Transaction: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactionAccount struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								ImportSource struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									TransactionAccounts struct {
										field.RelationField
									}
									ImportSourcePeriods struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										ImportSource struct {
											field.RelationField
										}
									}
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}
							DebitTransactionAccount struct {
								field.RelationField
							}
							TransactionAccountAssignments struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction", "model.Transaction_"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.Organization", "model.Organization"),
							},
							CreditTransactionAccount: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								ImportSource struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									TransactionAccounts struct {
										field.RelationField
									}
									ImportSourcePeriods struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										ImportSource struct {
											field.RelationField
										}
									}
								}
								CreditTransactions struct {
									field.RelationField
								}
								DebitTransactions struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount", "model.TransactionAccount"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.Organization", "model.Organization"),
								},
								ImportSource: struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									TransactionAccounts struct {
										field.RelationField
									}
									ImportSourcePeriods struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										ImportSource struct {
											field.RelationField
										}
									}
								}{
									RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource", "model.ImportSource"),
									Organization: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.Organization", "model.Organization"),
									},
									TransactionAccounts: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.TransactionAccounts", "model.TransactionAccount"),
									},
									ImportSourcePeriods: struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										ImportSource struct {
											field.RelationField
										}
									}{
										RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.ImportSourcePeriods", "model.ImportSourcePeriod"),
										Organization: struct {
											field.RelationField
										}{
											RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.ImportSourcePeriods.Organization", "model.Organization"),
										},
										ImportSource: struct {
											field.RelationField
										}{
											RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.ImportSourcePeriods.ImportSource", "model.ImportSource"),
										},
									},
								},
								CreditTransactions: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.CreditTransactions", "model.Transaction_"),
								},
								DebitTransactions: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.DebitTransactions", "model.Transaction_"),
								},
							},
							DebitTransactionAccount: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.DebitTransactionAccount", "model.TransactionAccount"),
							},
							TransactionAccountAssignments: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
							},
						},
						Account: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("BudgetTags.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Account", "model.Account"),
						},
					},
				},
			},
			AccountGroups: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("BudgetTags.Organization.AccountGroups", "model.AccountGroup"),
			},
			Accounts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("BudgetTags.Organization.Accounts", "model.Account"),
			},
			BudgetTags: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("BudgetTags.Organization.BudgetTags", "model.BudgetTag"),
			},
			BudgetTagAccountValues: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("BudgetTags.Organization.BudgetTagAccountValues", "model.BudgetTagAccountValue"),
			},
			Budgets: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				BudgetTags struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("BudgetTags.Organization.Budgets", "model.Budget"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("BudgetTags.Organization.Budgets.Organization", "model.Organization"),
				},
				BudgetTags: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("BudgetTags.Organization.Budgets.BudgetTags", "model.BudgetTag"),
				},
			},
			ImportSourcePeriods: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("BudgetTags.Organization.ImportSourcePeriods", "model.ImportSourcePeriod"),
			},
			ImportSources: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("BudgetTags.Organization.ImportSources", "model.ImportSource"),
			},
			ReportTemplates: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("BudgetTags.Organization.ReportTemplates", "model.ReportTemplate"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("BudgetTags.Organization.ReportTemplates.Organization", "model.Organization"),
				},
			},
			Reports: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("BudgetTags.Organization.Reports", "model.Report"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("BudgetTags.Organization.Reports.Organization", "model.Organization"),
				},
			},
			Transactions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("BudgetTags.Organization.Transactions", "model.Transaction_"),
			},
			TransactionAccountAssignments: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("BudgetTags.Organization.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
			},
			TransactionAccounts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("BudgetTags.Organization.TransactionAccounts", "model.TransactionAccount"),
			},
		},
		Budget: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("BudgetTags.Budget", "model.Budget"),
		},
		BudgetTagAccountValues: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("BudgetTags.BudgetTagAccountValues", "model.BudgetTagAccountValue"),
		},
	}

	_budget.Organization = budgetBelongsToOrganization{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Organization", "model.Organization"),
	}

	_budget.fillFieldMap()

	return _budget
}

type budget struct {
	budgetDo budgetDo

	ALL                field.Asterisk
	ID                 field.Field
	OrganizationID     field.Field
	DisplayName        field.String
	DisplayDescription field.String
	IsClosed           field.Bool
	PeriodStart        field.Time
	PeriodEnd          field.Time
	UpdatedAt          field.Time
	CreatedAt          field.Time
	BudgetTags         budgetHasManyBudgetTags

	Organization budgetBelongsToOrganization

	fieldMap map[string]field.Expr
}

func (b budget) Table(newTableName string) *budget {
	b.budgetDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b budget) As(alias string) *budget {
	b.budgetDo.DO = *(b.budgetDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *budget) updateTableName(table string) *budget {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewField(table, "id")
	b.OrganizationID = field.NewField(table, "organization_id")
	b.DisplayName = field.NewString(table, "display_name")
	b.DisplayDescription = field.NewString(table, "display_description")
	b.IsClosed = field.NewBool(table, "is_closed")
	b.PeriodStart = field.NewTime(table, "period_start")
	b.PeriodEnd = field.NewTime(table, "period_end")
	b.UpdatedAt = field.NewTime(table, "updated_at")
	b.CreatedAt = field.NewTime(table, "created_at")

	b.fillFieldMap()

	return b
}

func (b *budget) WithContext(ctx context.Context) IBudgetDo { return b.budgetDo.WithContext(ctx) }

func (b budget) TableName() string { return b.budgetDo.TableName() }

func (b budget) Alias() string { return b.budgetDo.Alias() }

func (b budget) Columns(cols ...field.Expr) gen.Columns { return b.budgetDo.Columns(cols...) }

func (b *budget) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *budget) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 11)
	b.fieldMap["id"] = b.ID
	b.fieldMap["organization_id"] = b.OrganizationID
	b.fieldMap["display_name"] = b.DisplayName
	b.fieldMap["display_description"] = b.DisplayDescription
	b.fieldMap["is_closed"] = b.IsClosed
	b.fieldMap["period_start"] = b.PeriodStart
	b.fieldMap["period_end"] = b.PeriodEnd
	b.fieldMap["updated_at"] = b.UpdatedAt
	b.fieldMap["created_at"] = b.CreatedAt

}

func (b budget) clone(db *gorm.DB) budget {
	b.budgetDo.ReplaceConnPool(db.Statement.ConnPool)
	b.BudgetTags.db = db.Session(&gorm.Session{Initialized: true})
	b.BudgetTags.db.Statement.ConnPool = db.Statement.ConnPool
	b.Organization.db = db.Session(&gorm.Session{Initialized: true})
	b.Organization.db.Statement.ConnPool = db.Statement.ConnPool
	return b
}

func (b budget) replaceDB(db *gorm.DB) budget {
	b.budgetDo.ReplaceDB(db)
	b.BudgetTags.db = db.Session(&gorm.Session{})
	b.Organization.db = db.Session(&gorm.Session{})
	return b
}

type budgetHasManyBudgetTags struct {
	db *gorm.DB

	field.RelationField

	Organization struct {
		field.RelationField
		AccountGroupAssignments struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			AccountGroup struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}
			Account struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
				BudgetTagAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					BudgetTag struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
				TransactionAccountAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditTransactionAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							ImportSource struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								TransactionAccounts struct {
									field.RelationField
								}
								ImportSourcePeriods struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									ImportSource struct {
										field.RelationField
									}
								}
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitTransactionAccount struct {
							field.RelationField
						}
						TransactionAccountAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
			}
		}
		AccountGroups struct {
			field.RelationField
		}
		Accounts struct {
			field.RelationField
		}
		BudgetTags struct {
			field.RelationField
		}
		BudgetTagAccountValues struct {
			field.RelationField
		}
		Budgets struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			BudgetTags struct {
				field.RelationField
			}
		}
		ImportSourcePeriods struct {
			field.RelationField
		}
		ImportSources struct {
			field.RelationField
		}
		ReportTemplates struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		Reports struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		Transactions struct {
			field.RelationField
		}
		TransactionAccountAssignments struct {
			field.RelationField
		}
		TransactionAccounts struct {
			field.RelationField
		}
	}
	Budget struct {
		field.RelationField
	}
	BudgetTagAccountValues struct {
		field.RelationField
	}
}

func (a budgetHasManyBudgetTags) Where(conds ...field.Expr) *budgetHasManyBudgetTags {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a budgetHasManyBudgetTags) WithContext(ctx context.Context) *budgetHasManyBudgetTags {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a budgetHasManyBudgetTags) Session(session *gorm.Session) *budgetHasManyBudgetTags {
	a.db = a.db.Session(session)
	return &a
}

func (a budgetHasManyBudgetTags) Model(m *model.Budget) *budgetHasManyBudgetTagsTx {
	return &budgetHasManyBudgetTagsTx{a.db.Model(m).Association(a.Name())}
}

func (a budgetHasManyBudgetTags) Unscoped() *budgetHasManyBudgetTags {
	a.db = a.db.Unscoped()
	return &a
}

type budgetHasManyBudgetTagsTx struct{ tx *gorm.Association }

func (a budgetHasManyBudgetTagsTx) Find() (result []*model.BudgetTag, err error) {
	return result, a.tx.Find(&result)
}

func (a budgetHasManyBudgetTagsTx) Append(values ...*model.BudgetTag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a budgetHasManyBudgetTagsTx) Replace(values ...*model.BudgetTag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a budgetHasManyBudgetTagsTx) Delete(values ...*model.BudgetTag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a budgetHasManyBudgetTagsTx) Clear() error {
	return a.tx.Clear()
}

func (a budgetHasManyBudgetTagsTx) Count() int64 {
	return a.tx.Count()
}

func (a budgetHasManyBudgetTagsTx) Unscoped() *budgetHasManyBudgetTagsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type budgetBelongsToOrganization struct {
	db *gorm.DB

	field.RelationField
}

func (a budgetBelongsToOrganization) Where(conds ...field.Expr) *budgetBelongsToOrganization {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a budgetBelongsToOrganization) WithContext(ctx context.Context) *budgetBelongsToOrganization {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a budgetBelongsToOrganization) Session(session *gorm.Session) *budgetBelongsToOrganization {
	a.db = a.db.Session(session)
	return &a
}

func (a budgetBelongsToOrganization) Model(m *model.Budget) *budgetBelongsToOrganizationTx {
	return &budgetBelongsToOrganizationTx{a.db.Model(m).Association(a.Name())}
}

func (a budgetBelongsToOrganization) Unscoped() *budgetBelongsToOrganization {
	a.db = a.db.Unscoped()
	return &a
}

type budgetBelongsToOrganizationTx struct{ tx *gorm.Association }

func (a budgetBelongsToOrganizationTx) Find() (result *model.Organization, err error) {
	return result, a.tx.Find(&result)
}

func (a budgetBelongsToOrganizationTx) Append(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a budgetBelongsToOrganizationTx) Replace(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a budgetBelongsToOrganizationTx) Delete(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a budgetBelongsToOrganizationTx) Clear() error {
	return a.tx.Clear()
}

func (a budgetBelongsToOrganizationTx) Count() int64 {
	return a.tx.Count()
}

func (a budgetBelongsToOrganizationTx) Unscoped() *budgetBelongsToOrganizationTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type budgetDo struct{ gen.DO }

type IBudgetDo interface {
	gen.SubQuery
	Debug() IBudgetDo
	WithContext(ctx context.Context) IBudgetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBudgetDo
	WriteDB() IBudgetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBudgetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBudgetDo
	Not(conds ...gen.Condition) IBudgetDo
	Or(conds ...gen.Condition) IBudgetDo
	Select(conds ...field.Expr) IBudgetDo
	Where(conds ...gen.Condition) IBudgetDo
	Order(conds ...field.Expr) IBudgetDo
	Distinct(cols ...field.Expr) IBudgetDo
	Omit(cols ...field.Expr) IBudgetDo
	Join(table schema.Tabler, on ...field.Expr) IBudgetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBudgetDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBudgetDo
	Group(cols ...field.Expr) IBudgetDo
	Having(conds ...gen.Condition) IBudgetDo
	Limit(limit int) IBudgetDo
	Offset(offset int) IBudgetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBudgetDo
	Unscoped() IBudgetDo
	Create(values ...*model.Budget) error
	CreateInBatches(values []*model.Budget, batchSize int) error
	Save(values ...*model.Budget) error
	First() (*model.Budget, error)
	Take() (*model.Budget, error)
	Last() (*model.Budget, error)
	Find() ([]*model.Budget, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Budget, err error)
	FindInBatches(result *[]*model.Budget, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Budget) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBudgetDo
	Assign(attrs ...field.AssignExpr) IBudgetDo
	Joins(fields ...field.RelationField) IBudgetDo
	Preload(fields ...field.RelationField) IBudgetDo
	FirstOrInit() (*model.Budget, error)
	FirstOrCreate() (*model.Budget, error)
	FindByPage(offset int, limit int) (result []*model.Budget, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBudgetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b budgetDo) Debug() IBudgetDo {
	return b.withDO(b.DO.Debug())
}

func (b budgetDo) WithContext(ctx context.Context) IBudgetDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b budgetDo) ReadDB() IBudgetDo {
	return b.Clauses(dbresolver.Read)
}

func (b budgetDo) WriteDB() IBudgetDo {
	return b.Clauses(dbresolver.Write)
}

func (b budgetDo) Session(config *gorm.Session) IBudgetDo {
	return b.withDO(b.DO.Session(config))
}

func (b budgetDo) Clauses(conds ...clause.Expression) IBudgetDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b budgetDo) Returning(value interface{}, columns ...string) IBudgetDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b budgetDo) Not(conds ...gen.Condition) IBudgetDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b budgetDo) Or(conds ...gen.Condition) IBudgetDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b budgetDo) Select(conds ...field.Expr) IBudgetDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b budgetDo) Where(conds ...gen.Condition) IBudgetDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b budgetDo) Order(conds ...field.Expr) IBudgetDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b budgetDo) Distinct(cols ...field.Expr) IBudgetDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b budgetDo) Omit(cols ...field.Expr) IBudgetDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b budgetDo) Join(table schema.Tabler, on ...field.Expr) IBudgetDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b budgetDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBudgetDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b budgetDo) RightJoin(table schema.Tabler, on ...field.Expr) IBudgetDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b budgetDo) Group(cols ...field.Expr) IBudgetDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b budgetDo) Having(conds ...gen.Condition) IBudgetDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b budgetDo) Limit(limit int) IBudgetDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b budgetDo) Offset(offset int) IBudgetDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b budgetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBudgetDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b budgetDo) Unscoped() IBudgetDo {
	return b.withDO(b.DO.Unscoped())
}

func (b budgetDo) Create(values ...*model.Budget) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b budgetDo) CreateInBatches(values []*model.Budget, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b budgetDo) Save(values ...*model.Budget) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b budgetDo) First() (*model.Budget, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Budget), nil
	}
}

func (b budgetDo) Take() (*model.Budget, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Budget), nil
	}
}

func (b budgetDo) Last() (*model.Budget, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Budget), nil
	}
}

func (b budgetDo) Find() ([]*model.Budget, error) {
	result, err := b.DO.Find()
	return result.([]*model.Budget), err
}

func (b budgetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Budget, err error) {
	buf := make([]*model.Budget, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b budgetDo) FindInBatches(result *[]*model.Budget, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b budgetDo) Attrs(attrs ...field.AssignExpr) IBudgetDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b budgetDo) Assign(attrs ...field.AssignExpr) IBudgetDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b budgetDo) Joins(fields ...field.RelationField) IBudgetDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b budgetDo) Preload(fields ...field.RelationField) IBudgetDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b budgetDo) FirstOrInit() (*model.Budget, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Budget), nil
	}
}

func (b budgetDo) FirstOrCreate() (*model.Budget, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Budget), nil
	}
}

func (b budgetDo) FindByPage(offset int, limit int) (result []*model.Budget, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b budgetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b budgetDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b budgetDo) Delete(models ...*model.Budget) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *budgetDo) withDO(do gen.Dao) *budgetDo {
	b.DO = *do.(*gen.DO)
	return b
}
