// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"github.com/pixlcrashr/vsfv/pkg/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newImportSource(db *gorm.DB, opts ...gen.DOOption) importSource {
	_importSource := importSource{}

	_importSource.importSourceDo.UseDB(db, opts...)
	_importSource.importSourceDo.UseModel(&model.ImportSource{})

	tableName := _importSource.importSourceDo.TableName()
	_importSource.ALL = field.NewAsterisk(tableName)
	_importSource.ID = field.NewField(tableName, "id")
	_importSource.DisplayName = field.NewString(tableName, "display_name")
	_importSource.DisplayDescription = field.NewString(tableName, "display_description")
	_importSource.PeriodStart = field.NewTime(tableName, "period_start")
	_importSource.UpdatedAt = field.NewTime(tableName, "updated_at")
	_importSource.CreatedAt = field.NewTime(tableName, "created_at")
	_importSource.TransactionAccounts = importSourceHasManyTransactionAccounts{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("TransactionAccounts", "model.TransactionAccount"),
		ImportSource: struct {
			field.RelationField
			TransactionAccounts struct {
				field.RelationField
			}
			ImportSourcePeriods struct {
				field.RelationField
				ImportSource struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("TransactionAccounts.ImportSource", "model.ImportSource"),
			TransactionAccounts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("TransactionAccounts.ImportSource.TransactionAccounts", "model.TransactionAccount"),
			},
			ImportSourcePeriods: struct {
				field.RelationField
				ImportSource struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("TransactionAccounts.ImportSource.ImportSourcePeriods", "model.ImportSourcePeriod"),
				ImportSource: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("TransactionAccounts.ImportSource.ImportSourcePeriods.ImportSource", "model.ImportSource"),
				},
			},
		},
		CreditTransactions: struct {
			field.RelationField
			AssignedAccount struct {
				field.RelationField
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
					AccountGroup struct {
						field.RelationField
						AccountGroupAssignments struct {
							field.RelationField
						}
						ViewAccountGroupAssignments struct {
							field.RelationField
							View struct {
								field.RelationField
								ViewAccountAssignments struct {
									field.RelationField
									View struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
								ViewAccountGroupAssignments struct {
									field.RelationField
								}
								ViewBudgetAssignments struct {
									field.RelationField
									View struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
										BudgetRevisions struct {
											field.RelationField
											Budget struct {
												field.RelationField
											}
											BudgetRevisionAccountValues struct {
												field.RelationField
												BudgetRevision struct {
													field.RelationField
												}
												Account struct {
													field.RelationField
												}
											}
										}
										ViewBudgetAssignments struct {
											field.RelationField
										}
									}
								}
							}
							AccountGroup struct {
								field.RelationField
							}
						}
					}
					Account struct {
						field.RelationField
					}
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
				}
				ViewAccountAssignments struct {
					field.RelationField
				}
				TransactionAccountAssignments struct {
					field.RelationField
					Transaction struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
			}
			CreditTransactionAccount struct {
				field.RelationField
			}
			DebitTransactionAccount struct {
				field.RelationField
			}
			TransactionAccountAssignments struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("TransactionAccounts.CreditTransactions", "model.Transaction_"),
			AssignedAccount: struct {
				field.RelationField
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
					AccountGroup struct {
						field.RelationField
						AccountGroupAssignments struct {
							field.RelationField
						}
						ViewAccountGroupAssignments struct {
							field.RelationField
							View struct {
								field.RelationField
								ViewAccountAssignments struct {
									field.RelationField
									View struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
								ViewAccountGroupAssignments struct {
									field.RelationField
								}
								ViewBudgetAssignments struct {
									field.RelationField
									View struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
										BudgetRevisions struct {
											field.RelationField
											Budget struct {
												field.RelationField
											}
											BudgetRevisionAccountValues struct {
												field.RelationField
												BudgetRevision struct {
													field.RelationField
												}
												Account struct {
													field.RelationField
												}
											}
										}
										ViewBudgetAssignments struct {
											field.RelationField
										}
									}
								}
							}
							AccountGroup struct {
								field.RelationField
							}
						}
					}
					Account struct {
						field.RelationField
					}
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
				}
				ViewAccountAssignments struct {
					field.RelationField
				}
				TransactionAccountAssignments struct {
					field.RelationField
					Transaction struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount", "model.Account"),
				ParentAccount: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.ParentAccount", "model.Account"),
				},
				ChildAccounts: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.ChildAccounts", "model.Account"),
				},
				AccountGroupAssignments: struct {
					field.RelationField
					AccountGroup struct {
						field.RelationField
						AccountGroupAssignments struct {
							field.RelationField
						}
						ViewAccountGroupAssignments struct {
							field.RelationField
							View struct {
								field.RelationField
								ViewAccountAssignments struct {
									field.RelationField
									View struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
								ViewAccountGroupAssignments struct {
									field.RelationField
								}
								ViewBudgetAssignments struct {
									field.RelationField
									View struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
										BudgetRevisions struct {
											field.RelationField
											Budget struct {
												field.RelationField
											}
											BudgetRevisionAccountValues struct {
												field.RelationField
												BudgetRevision struct {
													field.RelationField
												}
												Account struct {
													field.RelationField
												}
											}
										}
										ViewBudgetAssignments struct {
											field.RelationField
										}
									}
								}
							}
							AccountGroup struct {
								field.RelationField
							}
						}
					}
					Account struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments", "model.AccountGroupAssignment"),
					AccountGroup: struct {
						field.RelationField
						AccountGroupAssignments struct {
							field.RelationField
						}
						ViewAccountGroupAssignments struct {
							field.RelationField
							View struct {
								field.RelationField
								ViewAccountAssignments struct {
									field.RelationField
									View struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
								ViewAccountGroupAssignments struct {
									field.RelationField
								}
								ViewBudgetAssignments struct {
									field.RelationField
									View struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
										BudgetRevisions struct {
											field.RelationField
											Budget struct {
												field.RelationField
											}
											BudgetRevisionAccountValues struct {
												field.RelationField
												BudgetRevision struct {
													field.RelationField
												}
												Account struct {
													field.RelationField
												}
											}
										}
										ViewBudgetAssignments struct {
											field.RelationField
										}
									}
								}
							}
							AccountGroup struct {
								field.RelationField
							}
						}
					}{
						RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup", "model.AccountGroup"),
						AccountGroupAssignments: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.AccountGroupAssignments", "model.AccountGroupAssignment"),
						},
						ViewAccountGroupAssignments: struct {
							field.RelationField
							View struct {
								field.RelationField
								ViewAccountAssignments struct {
									field.RelationField
									View struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
								ViewAccountGroupAssignments struct {
									field.RelationField
								}
								ViewBudgetAssignments struct {
									field.RelationField
									View struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
										BudgetRevisions struct {
											field.RelationField
											Budget struct {
												field.RelationField
											}
											BudgetRevisionAccountValues struct {
												field.RelationField
												BudgetRevision struct {
													field.RelationField
												}
												Account struct {
													field.RelationField
												}
											}
										}
										ViewBudgetAssignments struct {
											field.RelationField
										}
									}
								}
							}
							AccountGroup struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.ViewAccountGroupAssignments", "model.ViewAccountGroupAssignment"),
							View: struct {
								field.RelationField
								ViewAccountAssignments struct {
									field.RelationField
									View struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
								ViewAccountGroupAssignments struct {
									field.RelationField
								}
								ViewBudgetAssignments struct {
									field.RelationField
									View struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
										BudgetRevisions struct {
											field.RelationField
											Budget struct {
												field.RelationField
											}
											BudgetRevisionAccountValues struct {
												field.RelationField
												BudgetRevision struct {
													field.RelationField
												}
												Account struct {
													field.RelationField
												}
											}
										}
										ViewBudgetAssignments struct {
											field.RelationField
										}
									}
								}
							}{
								RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.ViewAccountGroupAssignments.View", "model.View"),
								ViewAccountAssignments: struct {
									field.RelationField
									View struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}{
									RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.ViewAccountGroupAssignments.View.ViewAccountAssignments", "model.ViewAccountAssignment"),
									View: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.ViewAccountGroupAssignments.View.ViewAccountAssignments.View", "model.View"),
									},
									Account: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.ViewAccountGroupAssignments.View.ViewAccountAssignments.Account", "model.Account"),
									},
								},
								ViewAccountGroupAssignments: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.ViewAccountGroupAssignments.View.ViewAccountGroupAssignments", "model.ViewAccountGroupAssignment"),
								},
								ViewBudgetAssignments: struct {
									field.RelationField
									View struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
										BudgetRevisions struct {
											field.RelationField
											Budget struct {
												field.RelationField
											}
											BudgetRevisionAccountValues struct {
												field.RelationField
												BudgetRevision struct {
													field.RelationField
												}
												Account struct {
													field.RelationField
												}
											}
										}
										ViewBudgetAssignments struct {
											field.RelationField
										}
									}
								}{
									RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.ViewAccountGroupAssignments.View.ViewBudgetAssignments", "model.ViewBudgetAssignment"),
									View: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.ViewAccountGroupAssignments.View.ViewBudgetAssignments.View", "model.View"),
									},
									Budget: struct {
										field.RelationField
										BudgetRevisions struct {
											field.RelationField
											Budget struct {
												field.RelationField
											}
											BudgetRevisionAccountValues struct {
												field.RelationField
												BudgetRevision struct {
													field.RelationField
												}
												Account struct {
													field.RelationField
												}
											}
										}
										ViewBudgetAssignments struct {
											field.RelationField
										}
									}{
										RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.ViewAccountGroupAssignments.View.ViewBudgetAssignments.Budget", "model.Budget"),
										BudgetRevisions: struct {
											field.RelationField
											Budget struct {
												field.RelationField
											}
											BudgetRevisionAccountValues struct {
												field.RelationField
												BudgetRevision struct {
													field.RelationField
												}
												Account struct {
													field.RelationField
												}
											}
										}{
											RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.ViewAccountGroupAssignments.View.ViewBudgetAssignments.Budget.BudgetRevisions", "model.BudgetRevision"),
											Budget: struct {
												field.RelationField
											}{
												RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.ViewAccountGroupAssignments.View.ViewBudgetAssignments.Budget.BudgetRevisions.Budget", "model.Budget"),
											},
											BudgetRevisionAccountValues: struct {
												field.RelationField
												BudgetRevision struct {
													field.RelationField
												}
												Account struct {
													field.RelationField
												}
											}{
												RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.ViewAccountGroupAssignments.View.ViewBudgetAssignments.Budget.BudgetRevisions.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
												BudgetRevision: struct {
													field.RelationField
												}{
													RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.ViewAccountGroupAssignments.View.ViewBudgetAssignments.Budget.BudgetRevisions.BudgetRevisionAccountValues.BudgetRevision", "model.BudgetRevision"),
												},
												Account: struct {
													field.RelationField
												}{
													RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.ViewAccountGroupAssignments.View.ViewBudgetAssignments.Budget.BudgetRevisions.BudgetRevisionAccountValues.Account", "model.Account"),
												},
											},
										},
										ViewBudgetAssignments: struct {
											field.RelationField
										}{
											RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.ViewAccountGroupAssignments.View.ViewBudgetAssignments.Budget.ViewBudgetAssignments", "model.ViewBudgetAssignment"),
										},
									},
								},
							},
							AccountGroup: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.AccountGroup.ViewAccountGroupAssignments.AccountGroup", "model.AccountGroup"),
							},
						},
					},
					Account: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.AccountGroupAssignments.Account", "model.Account"),
					},
				},
				BudgetRevisionAccountValues: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
				},
				ViewAccountAssignments: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.ViewAccountAssignments", "model.ViewAccountAssignment"),
				},
				TransactionAccountAssignments: struct {
					field.RelationField
					Transaction struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
					Transaction: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.TransactionAccountAssignments.Transaction", "model.Transaction_"),
					},
					Account: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.AssignedAccount.TransactionAccountAssignments.Account", "model.Account"),
					},
				},
			},
			CreditTransactionAccount: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.CreditTransactionAccount", "model.TransactionAccount"),
			},
			DebitTransactionAccount: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.DebitTransactionAccount", "model.TransactionAccount"),
			},
			TransactionAccountAssignments: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("TransactionAccounts.CreditTransactions.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
			},
		},
		DebitTransactions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("TransactionAccounts.DebitTransactions", "model.Transaction_"),
		},
	}

	_importSource.ImportSourcePeriods = importSourceHasManyImportSourcePeriods{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ImportSourcePeriods", "model.ImportSourcePeriod"),
	}

	_importSource.fillFieldMap()

	return _importSource
}

type importSource struct {
	importSourceDo importSourceDo

	ALL                 field.Asterisk
	ID                  field.Field
	DisplayName         field.String
	DisplayDescription  field.String
	PeriodStart         field.Time
	UpdatedAt           field.Time
	CreatedAt           field.Time
	TransactionAccounts importSourceHasManyTransactionAccounts

	ImportSourcePeriods importSourceHasManyImportSourcePeriods

	fieldMap map[string]field.Expr
}

func (i importSource) Table(newTableName string) *importSource {
	i.importSourceDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i importSource) As(alias string) *importSource {
	i.importSourceDo.DO = *(i.importSourceDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *importSource) updateTableName(table string) *importSource {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewField(table, "id")
	i.DisplayName = field.NewString(table, "display_name")
	i.DisplayDescription = field.NewString(table, "display_description")
	i.PeriodStart = field.NewTime(table, "period_start")
	i.UpdatedAt = field.NewTime(table, "updated_at")
	i.CreatedAt = field.NewTime(table, "created_at")

	i.fillFieldMap()

	return i
}

func (i *importSource) WithContext(ctx context.Context) IImportSourceDo {
	return i.importSourceDo.WithContext(ctx)
}

func (i importSource) TableName() string { return i.importSourceDo.TableName() }

func (i importSource) Alias() string { return i.importSourceDo.Alias() }

func (i importSource) Columns(cols ...field.Expr) gen.Columns {
	return i.importSourceDo.Columns(cols...)
}

func (i *importSource) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *importSource) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 8)
	i.fieldMap["id"] = i.ID
	i.fieldMap["display_name"] = i.DisplayName
	i.fieldMap["display_description"] = i.DisplayDescription
	i.fieldMap["period_start"] = i.PeriodStart
	i.fieldMap["updated_at"] = i.UpdatedAt
	i.fieldMap["created_at"] = i.CreatedAt

}

func (i importSource) clone(db *gorm.DB) importSource {
	i.importSourceDo.ReplaceConnPool(db.Statement.ConnPool)
	i.TransactionAccounts.db = db.Session(&gorm.Session{Initialized: true})
	i.TransactionAccounts.db.Statement.ConnPool = db.Statement.ConnPool
	i.ImportSourcePeriods.db = db.Session(&gorm.Session{Initialized: true})
	i.ImportSourcePeriods.db.Statement.ConnPool = db.Statement.ConnPool
	return i
}

func (i importSource) replaceDB(db *gorm.DB) importSource {
	i.importSourceDo.ReplaceDB(db)
	i.TransactionAccounts.db = db.Session(&gorm.Session{})
	i.ImportSourcePeriods.db = db.Session(&gorm.Session{})
	return i
}

type importSourceHasManyTransactionAccounts struct {
	db *gorm.DB

	field.RelationField

	ImportSource struct {
		field.RelationField
		TransactionAccounts struct {
			field.RelationField
		}
		ImportSourcePeriods struct {
			field.RelationField
			ImportSource struct {
				field.RelationField
			}
		}
	}
	CreditTransactions struct {
		field.RelationField
		AssignedAccount struct {
			field.RelationField
			ParentAccount struct {
				field.RelationField
			}
			ChildAccounts struct {
				field.RelationField
			}
			AccountGroupAssignments struct {
				field.RelationField
				AccountGroup struct {
					field.RelationField
					AccountGroupAssignments struct {
						field.RelationField
					}
					ViewAccountGroupAssignments struct {
						field.RelationField
						View struct {
							field.RelationField
							ViewAccountAssignments struct {
								field.RelationField
								View struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
							ViewAccountGroupAssignments struct {
								field.RelationField
							}
							ViewBudgetAssignments struct {
								field.RelationField
								View struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
									BudgetRevisions struct {
										field.RelationField
										Budget struct {
											field.RelationField
										}
										BudgetRevisionAccountValues struct {
											field.RelationField
											BudgetRevision struct {
												field.RelationField
											}
											Account struct {
												field.RelationField
											}
										}
									}
									ViewBudgetAssignments struct {
										field.RelationField
									}
								}
							}
						}
						AccountGroup struct {
							field.RelationField
						}
					}
				}
				Account struct {
					field.RelationField
				}
			}
			BudgetRevisionAccountValues struct {
				field.RelationField
			}
			ViewAccountAssignments struct {
				field.RelationField
			}
			TransactionAccountAssignments struct {
				field.RelationField
				Transaction struct {
					field.RelationField
				}
				Account struct {
					field.RelationField
				}
			}
		}
		CreditTransactionAccount struct {
			field.RelationField
		}
		DebitTransactionAccount struct {
			field.RelationField
		}
		TransactionAccountAssignments struct {
			field.RelationField
		}
	}
	DebitTransactions struct {
		field.RelationField
	}
}

func (a importSourceHasManyTransactionAccounts) Where(conds ...field.Expr) *importSourceHasManyTransactionAccounts {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a importSourceHasManyTransactionAccounts) WithContext(ctx context.Context) *importSourceHasManyTransactionAccounts {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a importSourceHasManyTransactionAccounts) Session(session *gorm.Session) *importSourceHasManyTransactionAccounts {
	a.db = a.db.Session(session)
	return &a
}

func (a importSourceHasManyTransactionAccounts) Model(m *model.ImportSource) *importSourceHasManyTransactionAccountsTx {
	return &importSourceHasManyTransactionAccountsTx{a.db.Model(m).Association(a.Name())}
}

func (a importSourceHasManyTransactionAccounts) Unscoped() *importSourceHasManyTransactionAccounts {
	a.db = a.db.Unscoped()
	return &a
}

type importSourceHasManyTransactionAccountsTx struct{ tx *gorm.Association }

func (a importSourceHasManyTransactionAccountsTx) Find() (result []*model.TransactionAccount, err error) {
	return result, a.tx.Find(&result)
}

func (a importSourceHasManyTransactionAccountsTx) Append(values ...*model.TransactionAccount) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a importSourceHasManyTransactionAccountsTx) Replace(values ...*model.TransactionAccount) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a importSourceHasManyTransactionAccountsTx) Delete(values ...*model.TransactionAccount) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a importSourceHasManyTransactionAccountsTx) Clear() error {
	return a.tx.Clear()
}

func (a importSourceHasManyTransactionAccountsTx) Count() int64 {
	return a.tx.Count()
}

func (a importSourceHasManyTransactionAccountsTx) Unscoped() *importSourceHasManyTransactionAccountsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type importSourceHasManyImportSourcePeriods struct {
	db *gorm.DB

	field.RelationField
}

func (a importSourceHasManyImportSourcePeriods) Where(conds ...field.Expr) *importSourceHasManyImportSourcePeriods {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a importSourceHasManyImportSourcePeriods) WithContext(ctx context.Context) *importSourceHasManyImportSourcePeriods {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a importSourceHasManyImportSourcePeriods) Session(session *gorm.Session) *importSourceHasManyImportSourcePeriods {
	a.db = a.db.Session(session)
	return &a
}

func (a importSourceHasManyImportSourcePeriods) Model(m *model.ImportSource) *importSourceHasManyImportSourcePeriodsTx {
	return &importSourceHasManyImportSourcePeriodsTx{a.db.Model(m).Association(a.Name())}
}

func (a importSourceHasManyImportSourcePeriods) Unscoped() *importSourceHasManyImportSourcePeriods {
	a.db = a.db.Unscoped()
	return &a
}

type importSourceHasManyImportSourcePeriodsTx struct{ tx *gorm.Association }

func (a importSourceHasManyImportSourcePeriodsTx) Find() (result []*model.ImportSourcePeriod, err error) {
	return result, a.tx.Find(&result)
}

func (a importSourceHasManyImportSourcePeriodsTx) Append(values ...*model.ImportSourcePeriod) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a importSourceHasManyImportSourcePeriodsTx) Replace(values ...*model.ImportSourcePeriod) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a importSourceHasManyImportSourcePeriodsTx) Delete(values ...*model.ImportSourcePeriod) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a importSourceHasManyImportSourcePeriodsTx) Clear() error {
	return a.tx.Clear()
}

func (a importSourceHasManyImportSourcePeriodsTx) Count() int64 {
	return a.tx.Count()
}

func (a importSourceHasManyImportSourcePeriodsTx) Unscoped() *importSourceHasManyImportSourcePeriodsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type importSourceDo struct{ gen.DO }

type IImportSourceDo interface {
	gen.SubQuery
	Debug() IImportSourceDo
	WithContext(ctx context.Context) IImportSourceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IImportSourceDo
	WriteDB() IImportSourceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IImportSourceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IImportSourceDo
	Not(conds ...gen.Condition) IImportSourceDo
	Or(conds ...gen.Condition) IImportSourceDo
	Select(conds ...field.Expr) IImportSourceDo
	Where(conds ...gen.Condition) IImportSourceDo
	Order(conds ...field.Expr) IImportSourceDo
	Distinct(cols ...field.Expr) IImportSourceDo
	Omit(cols ...field.Expr) IImportSourceDo
	Join(table schema.Tabler, on ...field.Expr) IImportSourceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IImportSourceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IImportSourceDo
	Group(cols ...field.Expr) IImportSourceDo
	Having(conds ...gen.Condition) IImportSourceDo
	Limit(limit int) IImportSourceDo
	Offset(offset int) IImportSourceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IImportSourceDo
	Unscoped() IImportSourceDo
	Create(values ...*model.ImportSource) error
	CreateInBatches(values []*model.ImportSource, batchSize int) error
	Save(values ...*model.ImportSource) error
	First() (*model.ImportSource, error)
	Take() (*model.ImportSource, error)
	Last() (*model.ImportSource, error)
	Find() ([]*model.ImportSource, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ImportSource, err error)
	FindInBatches(result *[]*model.ImportSource, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ImportSource) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IImportSourceDo
	Assign(attrs ...field.AssignExpr) IImportSourceDo
	Joins(fields ...field.RelationField) IImportSourceDo
	Preload(fields ...field.RelationField) IImportSourceDo
	FirstOrInit() (*model.ImportSource, error)
	FirstOrCreate() (*model.ImportSource, error)
	FindByPage(offset int, limit int) (result []*model.ImportSource, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IImportSourceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i importSourceDo) Debug() IImportSourceDo {
	return i.withDO(i.DO.Debug())
}

func (i importSourceDo) WithContext(ctx context.Context) IImportSourceDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i importSourceDo) ReadDB() IImportSourceDo {
	return i.Clauses(dbresolver.Read)
}

func (i importSourceDo) WriteDB() IImportSourceDo {
	return i.Clauses(dbresolver.Write)
}

func (i importSourceDo) Session(config *gorm.Session) IImportSourceDo {
	return i.withDO(i.DO.Session(config))
}

func (i importSourceDo) Clauses(conds ...clause.Expression) IImportSourceDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i importSourceDo) Returning(value interface{}, columns ...string) IImportSourceDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i importSourceDo) Not(conds ...gen.Condition) IImportSourceDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i importSourceDo) Or(conds ...gen.Condition) IImportSourceDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i importSourceDo) Select(conds ...field.Expr) IImportSourceDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i importSourceDo) Where(conds ...gen.Condition) IImportSourceDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i importSourceDo) Order(conds ...field.Expr) IImportSourceDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i importSourceDo) Distinct(cols ...field.Expr) IImportSourceDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i importSourceDo) Omit(cols ...field.Expr) IImportSourceDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i importSourceDo) Join(table schema.Tabler, on ...field.Expr) IImportSourceDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i importSourceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IImportSourceDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i importSourceDo) RightJoin(table schema.Tabler, on ...field.Expr) IImportSourceDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i importSourceDo) Group(cols ...field.Expr) IImportSourceDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i importSourceDo) Having(conds ...gen.Condition) IImportSourceDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i importSourceDo) Limit(limit int) IImportSourceDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i importSourceDo) Offset(offset int) IImportSourceDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i importSourceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IImportSourceDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i importSourceDo) Unscoped() IImportSourceDo {
	return i.withDO(i.DO.Unscoped())
}

func (i importSourceDo) Create(values ...*model.ImportSource) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i importSourceDo) CreateInBatches(values []*model.ImportSource, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i importSourceDo) Save(values ...*model.ImportSource) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i importSourceDo) First() (*model.ImportSource, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImportSource), nil
	}
}

func (i importSourceDo) Take() (*model.ImportSource, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImportSource), nil
	}
}

func (i importSourceDo) Last() (*model.ImportSource, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImportSource), nil
	}
}

func (i importSourceDo) Find() ([]*model.ImportSource, error) {
	result, err := i.DO.Find()
	return result.([]*model.ImportSource), err
}

func (i importSourceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ImportSource, err error) {
	buf := make([]*model.ImportSource, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i importSourceDo) FindInBatches(result *[]*model.ImportSource, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i importSourceDo) Attrs(attrs ...field.AssignExpr) IImportSourceDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i importSourceDo) Assign(attrs ...field.AssignExpr) IImportSourceDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i importSourceDo) Joins(fields ...field.RelationField) IImportSourceDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i importSourceDo) Preload(fields ...field.RelationField) IImportSourceDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i importSourceDo) FirstOrInit() (*model.ImportSource, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImportSource), nil
	}
}

func (i importSourceDo) FirstOrCreate() (*model.ImportSource, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImportSource), nil
	}
}

func (i importSourceDo) FindByPage(offset int, limit int) (result []*model.ImportSource, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i importSourceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i importSourceDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i importSourceDo) Delete(models ...*model.ImportSource) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *importSourceDo) withDO(do gen.Dao) *importSourceDo {
	i.DO = *do.(*gen.DO)
	return i
}
