// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"github.com/pixlcrashr/vsfv/pkg/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newOrganization(db *gorm.DB, opts ...gen.DOOption) organization {
	_organization := organization{}

	_organization.organizationDo.UseDB(db, opts...)
	_organization.organizationDo.UseModel(&model.Organization{})

	tableName := _organization.organizationDo.TableName()
	_organization.ALL = field.NewAsterisk(tableName)
	_organization.ID = field.NewField(tableName, "id")
	_organization.DisplayName = field.NewString(tableName, "display_name")
	_organization.UpdatedAt = field.NewTime(tableName, "updated_at")
	_organization.CreatedAt = field.NewTime(tableName, "created_at")
	_organization.AccountGroupAssignments = organizationHasManyAccountGroupAssignments{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("AccountGroupAssignments", "model.AccountGroupAssignment"),
		Organization: struct {
			field.RelationField
			AccountGroupAssignments struct {
				field.RelationField
			}
			AccountGroups struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}
			Accounts struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
				BudgetTagAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					BudgetTag struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetTags struct {
								field.RelationField
							}
						}
						BudgetTagAccountValues struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
				TransactionAccountAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditTransactionAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							ImportSource struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								TransactionAccounts struct {
									field.RelationField
								}
								ImportSourcePeriods struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									ImportSource struct {
										field.RelationField
									}
								}
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitTransactionAccount struct {
							field.RelationField
						}
						TransactionAccountAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
			}
			BudgetTags struct {
				field.RelationField
			}
			BudgetTagAccountValues struct {
				field.RelationField
			}
			Budgets struct {
				field.RelationField
			}
			ImportSourcePeriods struct {
				field.RelationField
			}
			ImportSources struct {
				field.RelationField
			}
			ReportTemplates struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Reports struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Transactions struct {
				field.RelationField
			}
			TransactionAccountAssignments struct {
				field.RelationField
			}
			TransactionAccounts struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("AccountGroupAssignments.Organization", "model.Organization"),
			AccountGroupAssignments: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AccountGroupAssignments.Organization.AccountGroupAssignments", "model.AccountGroupAssignment"),
			},
			AccountGroups: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("AccountGroupAssignments.Organization.AccountGroups", "model.AccountGroup"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("AccountGroupAssignments.Organization.AccountGroups.Organization", "model.Organization"),
				},
				AccountGroupAssignments: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("AccountGroupAssignments.Organization.AccountGroups.AccountGroupAssignments", "model.AccountGroupAssignment"),
				},
			},
			Accounts: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
				BudgetTagAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					BudgetTag struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetTags struct {
								field.RelationField
							}
						}
						BudgetTagAccountValues struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
				TransactionAccountAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditTransactionAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							ImportSource struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								TransactionAccounts struct {
									field.RelationField
								}
								ImportSourcePeriods struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									ImportSource struct {
										field.RelationField
									}
								}
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitTransactionAccount struct {
							field.RelationField
						}
						TransactionAccountAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts", "model.Account"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.Organization", "model.Organization"),
				},
				ParentAccount: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.ParentAccount", "model.Account"),
				},
				ChildAccounts: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.ChildAccounts", "model.Account"),
				},
				AccountGroupAssignments: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.AccountGroupAssignments", "model.AccountGroupAssignment"),
				},
				BudgetTagAccountValues: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					BudgetTag struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetTags struct {
								field.RelationField
							}
						}
						BudgetTagAccountValues struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.BudgetTagAccountValues", "model.BudgetTagAccountValue"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.BudgetTagAccountValues.Organization", "model.Organization"),
					},
					BudgetTag: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetTags struct {
								field.RelationField
							}
						}
						BudgetTagAccountValues struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.BudgetTagAccountValues.BudgetTag", "model.BudgetTag"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.BudgetTagAccountValues.BudgetTag.Organization", "model.Organization"),
						},
						Budget: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetTags struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.BudgetTagAccountValues.BudgetTag.Budget", "model.Budget"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.BudgetTagAccountValues.BudgetTag.Budget.Organization", "model.Organization"),
							},
							BudgetTags: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.BudgetTagAccountValues.BudgetTag.Budget.BudgetTags", "model.BudgetTag"),
							},
						},
						BudgetTagAccountValues: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.BudgetTagAccountValues.BudgetTag.BudgetTagAccountValues", "model.BudgetTagAccountValue"),
						},
					},
					Account: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.BudgetTagAccountValues.Account", "model.Account"),
					},
				},
				TransactionAccountAssignments: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditTransactionAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							ImportSource struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								TransactionAccounts struct {
									field.RelationField
								}
								ImportSourcePeriods struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									ImportSource struct {
										field.RelationField
									}
								}
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitTransactionAccount struct {
							field.RelationField
						}
						TransactionAccountAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments.Organization", "model.Organization"),
					},
					Transaction: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditTransactionAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							ImportSource struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								TransactionAccounts struct {
									field.RelationField
								}
								ImportSourcePeriods struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									ImportSource struct {
										field.RelationField
									}
								}
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitTransactionAccount struct {
							field.RelationField
						}
						TransactionAccountAssignments struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments.Transaction", "model.Transaction_"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments.Transaction.Organization", "model.Organization"),
						},
						CreditTransactionAccount: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							ImportSource struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								TransactionAccounts struct {
									field.RelationField
								}
								ImportSourcePeriods struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									ImportSource struct {
										field.RelationField
									}
								}
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments.Transaction.CreditTransactionAccount", "model.TransactionAccount"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments.Transaction.CreditTransactionAccount.Organization", "model.Organization"),
							},
							ImportSource: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								TransactionAccounts struct {
									field.RelationField
								}
								ImportSourcePeriods struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									ImportSource struct {
										field.RelationField
									}
								}
							}{
								RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource", "model.ImportSource"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.Organization", "model.Organization"),
								},
								TransactionAccounts: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.TransactionAccounts", "model.TransactionAccount"),
								},
								ImportSourcePeriods: struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									ImportSource struct {
										field.RelationField
									}
								}{
									RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.ImportSourcePeriods", "model.ImportSourcePeriod"),
									Organization: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.ImportSourcePeriods.Organization", "model.Organization"),
									},
									ImportSource: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.ImportSourcePeriods.ImportSource", "model.ImportSource"),
									},
								},
							},
							CreditTransactions: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments.Transaction.CreditTransactionAccount.CreditTransactions", "model.Transaction_"),
							},
							DebitTransactions: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments.Transaction.CreditTransactionAccount.DebitTransactions", "model.Transaction_"),
							},
						},
						DebitTransactionAccount: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments.Transaction.DebitTransactionAccount", "model.TransactionAccount"),
						},
						TransactionAccountAssignments: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments.Transaction.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
						},
					},
					Account: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("AccountGroupAssignments.Organization.Accounts.TransactionAccountAssignments.Account", "model.Account"),
					},
				},
			},
			BudgetTags: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AccountGroupAssignments.Organization.BudgetTags", "model.BudgetTag"),
			},
			BudgetTagAccountValues: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AccountGroupAssignments.Organization.BudgetTagAccountValues", "model.BudgetTagAccountValue"),
			},
			Budgets: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AccountGroupAssignments.Organization.Budgets", "model.Budget"),
			},
			ImportSourcePeriods: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AccountGroupAssignments.Organization.ImportSourcePeriods", "model.ImportSourcePeriod"),
			},
			ImportSources: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AccountGroupAssignments.Organization.ImportSources", "model.ImportSource"),
			},
			ReportTemplates: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("AccountGroupAssignments.Organization.ReportTemplates", "model.ReportTemplate"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("AccountGroupAssignments.Organization.ReportTemplates.Organization", "model.Organization"),
				},
			},
			Reports: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("AccountGroupAssignments.Organization.Reports", "model.Report"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("AccountGroupAssignments.Organization.Reports.Organization", "model.Organization"),
				},
			},
			Transactions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AccountGroupAssignments.Organization.Transactions", "model.Transaction_"),
			},
			TransactionAccountAssignments: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AccountGroupAssignments.Organization.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
			},
			TransactionAccounts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AccountGroupAssignments.Organization.TransactionAccounts", "model.TransactionAccount"),
			},
		},
		AccountGroup: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("AccountGroupAssignments.AccountGroup", "model.AccountGroup"),
		},
		Account: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("AccountGroupAssignments.Account", "model.Account"),
		},
	}

	_organization.AccountGroups = organizationHasManyAccountGroups{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("AccountGroups", "model.AccountGroup"),
	}

	_organization.Accounts = organizationHasManyAccounts{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Accounts", "model.Account"),
	}

	_organization.BudgetTags = organizationHasManyBudgetTags{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("BudgetTags", "model.BudgetTag"),
	}

	_organization.BudgetTagAccountValues = organizationHasManyBudgetTagAccountValues{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("BudgetTagAccountValues", "model.BudgetTagAccountValue"),
	}

	_organization.Budgets = organizationHasManyBudgets{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Budgets", "model.Budget"),
	}

	_organization.ImportSourcePeriods = organizationHasManyImportSourcePeriods{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ImportSourcePeriods", "model.ImportSourcePeriod"),
	}

	_organization.ImportSources = organizationHasManyImportSources{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ImportSources", "model.ImportSource"),
	}

	_organization.ReportTemplates = organizationHasManyReportTemplates{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ReportTemplates", "model.ReportTemplate"),
	}

	_organization.Reports = organizationHasManyReports{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Reports", "model.Report"),
	}

	_organization.Transactions = organizationHasManyTransactions{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Transactions", "model.Transaction_"),
	}

	_organization.TransactionAccountAssignments = organizationHasManyTransactionAccountAssignments{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("TransactionAccountAssignments", "model.TransactionAccountAssignment"),
	}

	_organization.TransactionAccounts = organizationHasManyTransactionAccounts{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("TransactionAccounts", "model.TransactionAccount"),
	}

	_organization.fillFieldMap()

	return _organization
}

type organization struct {
	organizationDo organizationDo

	ALL                     field.Asterisk
	ID                      field.Field
	DisplayName             field.String
	UpdatedAt               field.Time
	CreatedAt               field.Time
	AccountGroupAssignments organizationHasManyAccountGroupAssignments

	AccountGroups organizationHasManyAccountGroups

	Accounts organizationHasManyAccounts

	BudgetTags organizationHasManyBudgetTags

	BudgetTagAccountValues organizationHasManyBudgetTagAccountValues

	Budgets organizationHasManyBudgets

	ImportSourcePeriods organizationHasManyImportSourcePeriods

	ImportSources organizationHasManyImportSources

	ReportTemplates organizationHasManyReportTemplates

	Reports organizationHasManyReports

	Transactions organizationHasManyTransactions

	TransactionAccountAssignments organizationHasManyTransactionAccountAssignments

	TransactionAccounts organizationHasManyTransactionAccounts

	fieldMap map[string]field.Expr
}

func (o organization) Table(newTableName string) *organization {
	o.organizationDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o organization) As(alias string) *organization {
	o.organizationDo.DO = *(o.organizationDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *organization) updateTableName(table string) *organization {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewField(table, "id")
	o.DisplayName = field.NewString(table, "display_name")
	o.UpdatedAt = field.NewTime(table, "updated_at")
	o.CreatedAt = field.NewTime(table, "created_at")

	o.fillFieldMap()

	return o
}

func (o *organization) WithContext(ctx context.Context) IOrganizationDo {
	return o.organizationDo.WithContext(ctx)
}

func (o organization) TableName() string { return o.organizationDo.TableName() }

func (o organization) Alias() string { return o.organizationDo.Alias() }

func (o organization) Columns(cols ...field.Expr) gen.Columns {
	return o.organizationDo.Columns(cols...)
}

func (o *organization) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *organization) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 17)
	o.fieldMap["id"] = o.ID
	o.fieldMap["display_name"] = o.DisplayName
	o.fieldMap["updated_at"] = o.UpdatedAt
	o.fieldMap["created_at"] = o.CreatedAt

}

func (o organization) clone(db *gorm.DB) organization {
	o.organizationDo.ReplaceConnPool(db.Statement.ConnPool)
	o.AccountGroupAssignments.db = db.Session(&gorm.Session{Initialized: true})
	o.AccountGroupAssignments.db.Statement.ConnPool = db.Statement.ConnPool
	o.AccountGroups.db = db.Session(&gorm.Session{Initialized: true})
	o.AccountGroups.db.Statement.ConnPool = db.Statement.ConnPool
	o.Accounts.db = db.Session(&gorm.Session{Initialized: true})
	o.Accounts.db.Statement.ConnPool = db.Statement.ConnPool
	o.BudgetTags.db = db.Session(&gorm.Session{Initialized: true})
	o.BudgetTags.db.Statement.ConnPool = db.Statement.ConnPool
	o.BudgetTagAccountValues.db = db.Session(&gorm.Session{Initialized: true})
	o.BudgetTagAccountValues.db.Statement.ConnPool = db.Statement.ConnPool
	o.Budgets.db = db.Session(&gorm.Session{Initialized: true})
	o.Budgets.db.Statement.ConnPool = db.Statement.ConnPool
	o.ImportSourcePeriods.db = db.Session(&gorm.Session{Initialized: true})
	o.ImportSourcePeriods.db.Statement.ConnPool = db.Statement.ConnPool
	o.ImportSources.db = db.Session(&gorm.Session{Initialized: true})
	o.ImportSources.db.Statement.ConnPool = db.Statement.ConnPool
	o.ReportTemplates.db = db.Session(&gorm.Session{Initialized: true})
	o.ReportTemplates.db.Statement.ConnPool = db.Statement.ConnPool
	o.Reports.db = db.Session(&gorm.Session{Initialized: true})
	o.Reports.db.Statement.ConnPool = db.Statement.ConnPool
	o.Transactions.db = db.Session(&gorm.Session{Initialized: true})
	o.Transactions.db.Statement.ConnPool = db.Statement.ConnPool
	o.TransactionAccountAssignments.db = db.Session(&gorm.Session{Initialized: true})
	o.TransactionAccountAssignments.db.Statement.ConnPool = db.Statement.ConnPool
	o.TransactionAccounts.db = db.Session(&gorm.Session{Initialized: true})
	o.TransactionAccounts.db.Statement.ConnPool = db.Statement.ConnPool
	return o
}

func (o organization) replaceDB(db *gorm.DB) organization {
	o.organizationDo.ReplaceDB(db)
	o.AccountGroupAssignments.db = db.Session(&gorm.Session{})
	o.AccountGroups.db = db.Session(&gorm.Session{})
	o.Accounts.db = db.Session(&gorm.Session{})
	o.BudgetTags.db = db.Session(&gorm.Session{})
	o.BudgetTagAccountValues.db = db.Session(&gorm.Session{})
	o.Budgets.db = db.Session(&gorm.Session{})
	o.ImportSourcePeriods.db = db.Session(&gorm.Session{})
	o.ImportSources.db = db.Session(&gorm.Session{})
	o.ReportTemplates.db = db.Session(&gorm.Session{})
	o.Reports.db = db.Session(&gorm.Session{})
	o.Transactions.db = db.Session(&gorm.Session{})
	o.TransactionAccountAssignments.db = db.Session(&gorm.Session{})
	o.TransactionAccounts.db = db.Session(&gorm.Session{})
	return o
}

type organizationHasManyAccountGroupAssignments struct {
	db *gorm.DB

	field.RelationField

	Organization struct {
		field.RelationField
		AccountGroupAssignments struct {
			field.RelationField
		}
		AccountGroups struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			AccountGroupAssignments struct {
				field.RelationField
			}
		}
		Accounts struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			ParentAccount struct {
				field.RelationField
			}
			ChildAccounts struct {
				field.RelationField
			}
			AccountGroupAssignments struct {
				field.RelationField
			}
			BudgetTagAccountValues struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				BudgetTag struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetTags struct {
							field.RelationField
						}
					}
					BudgetTagAccountValues struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
				}
			}
			TransactionAccountAssignments struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Transaction struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					CreditTransactionAccount struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						ImportSource struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							TransactionAccounts struct {
								field.RelationField
							}
							ImportSourcePeriods struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								ImportSource struct {
									field.RelationField
								}
							}
						}
						CreditTransactions struct {
							field.RelationField
						}
						DebitTransactions struct {
							field.RelationField
						}
					}
					DebitTransactionAccount struct {
						field.RelationField
					}
					TransactionAccountAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
				}
			}
		}
		BudgetTags struct {
			field.RelationField
		}
		BudgetTagAccountValues struct {
			field.RelationField
		}
		Budgets struct {
			field.RelationField
		}
		ImportSourcePeriods struct {
			field.RelationField
		}
		ImportSources struct {
			field.RelationField
		}
		ReportTemplates struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		Reports struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		Transactions struct {
			field.RelationField
		}
		TransactionAccountAssignments struct {
			field.RelationField
		}
		TransactionAccounts struct {
			field.RelationField
		}
	}
	AccountGroup struct {
		field.RelationField
	}
	Account struct {
		field.RelationField
	}
}

func (a organizationHasManyAccountGroupAssignments) Where(conds ...field.Expr) *organizationHasManyAccountGroupAssignments {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a organizationHasManyAccountGroupAssignments) WithContext(ctx context.Context) *organizationHasManyAccountGroupAssignments {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a organizationHasManyAccountGroupAssignments) Session(session *gorm.Session) *organizationHasManyAccountGroupAssignments {
	a.db = a.db.Session(session)
	return &a
}

func (a organizationHasManyAccountGroupAssignments) Model(m *model.Organization) *organizationHasManyAccountGroupAssignmentsTx {
	return &organizationHasManyAccountGroupAssignmentsTx{a.db.Model(m).Association(a.Name())}
}

func (a organizationHasManyAccountGroupAssignments) Unscoped() *organizationHasManyAccountGroupAssignments {
	a.db = a.db.Unscoped()
	return &a
}

type organizationHasManyAccountGroupAssignmentsTx struct{ tx *gorm.Association }

func (a organizationHasManyAccountGroupAssignmentsTx) Find() (result []*model.AccountGroupAssignment, err error) {
	return result, a.tx.Find(&result)
}

func (a organizationHasManyAccountGroupAssignmentsTx) Append(values ...*model.AccountGroupAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a organizationHasManyAccountGroupAssignmentsTx) Replace(values ...*model.AccountGroupAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a organizationHasManyAccountGroupAssignmentsTx) Delete(values ...*model.AccountGroupAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a organizationHasManyAccountGroupAssignmentsTx) Clear() error {
	return a.tx.Clear()
}

func (a organizationHasManyAccountGroupAssignmentsTx) Count() int64 {
	return a.tx.Count()
}

func (a organizationHasManyAccountGroupAssignmentsTx) Unscoped() *organizationHasManyAccountGroupAssignmentsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type organizationHasManyAccountGroups struct {
	db *gorm.DB

	field.RelationField
}

func (a organizationHasManyAccountGroups) Where(conds ...field.Expr) *organizationHasManyAccountGroups {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a organizationHasManyAccountGroups) WithContext(ctx context.Context) *organizationHasManyAccountGroups {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a organizationHasManyAccountGroups) Session(session *gorm.Session) *organizationHasManyAccountGroups {
	a.db = a.db.Session(session)
	return &a
}

func (a organizationHasManyAccountGroups) Model(m *model.Organization) *organizationHasManyAccountGroupsTx {
	return &organizationHasManyAccountGroupsTx{a.db.Model(m).Association(a.Name())}
}

func (a organizationHasManyAccountGroups) Unscoped() *organizationHasManyAccountGroups {
	a.db = a.db.Unscoped()
	return &a
}

type organizationHasManyAccountGroupsTx struct{ tx *gorm.Association }

func (a organizationHasManyAccountGroupsTx) Find() (result []*model.AccountGroup, err error) {
	return result, a.tx.Find(&result)
}

func (a organizationHasManyAccountGroupsTx) Append(values ...*model.AccountGroup) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a organizationHasManyAccountGroupsTx) Replace(values ...*model.AccountGroup) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a organizationHasManyAccountGroupsTx) Delete(values ...*model.AccountGroup) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a organizationHasManyAccountGroupsTx) Clear() error {
	return a.tx.Clear()
}

func (a organizationHasManyAccountGroupsTx) Count() int64 {
	return a.tx.Count()
}

func (a organizationHasManyAccountGroupsTx) Unscoped() *organizationHasManyAccountGroupsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type organizationHasManyAccounts struct {
	db *gorm.DB

	field.RelationField
}

func (a organizationHasManyAccounts) Where(conds ...field.Expr) *organizationHasManyAccounts {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a organizationHasManyAccounts) WithContext(ctx context.Context) *organizationHasManyAccounts {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a organizationHasManyAccounts) Session(session *gorm.Session) *organizationHasManyAccounts {
	a.db = a.db.Session(session)
	return &a
}

func (a organizationHasManyAccounts) Model(m *model.Organization) *organizationHasManyAccountsTx {
	return &organizationHasManyAccountsTx{a.db.Model(m).Association(a.Name())}
}

func (a organizationHasManyAccounts) Unscoped() *organizationHasManyAccounts {
	a.db = a.db.Unscoped()
	return &a
}

type organizationHasManyAccountsTx struct{ tx *gorm.Association }

func (a organizationHasManyAccountsTx) Find() (result []*model.Account, err error) {
	return result, a.tx.Find(&result)
}

func (a organizationHasManyAccountsTx) Append(values ...*model.Account) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a organizationHasManyAccountsTx) Replace(values ...*model.Account) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a organizationHasManyAccountsTx) Delete(values ...*model.Account) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a organizationHasManyAccountsTx) Clear() error {
	return a.tx.Clear()
}

func (a organizationHasManyAccountsTx) Count() int64 {
	return a.tx.Count()
}

func (a organizationHasManyAccountsTx) Unscoped() *organizationHasManyAccountsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type organizationHasManyBudgetTags struct {
	db *gorm.DB

	field.RelationField
}

func (a organizationHasManyBudgetTags) Where(conds ...field.Expr) *organizationHasManyBudgetTags {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a organizationHasManyBudgetTags) WithContext(ctx context.Context) *organizationHasManyBudgetTags {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a organizationHasManyBudgetTags) Session(session *gorm.Session) *organizationHasManyBudgetTags {
	a.db = a.db.Session(session)
	return &a
}

func (a organizationHasManyBudgetTags) Model(m *model.Organization) *organizationHasManyBudgetTagsTx {
	return &organizationHasManyBudgetTagsTx{a.db.Model(m).Association(a.Name())}
}

func (a organizationHasManyBudgetTags) Unscoped() *organizationHasManyBudgetTags {
	a.db = a.db.Unscoped()
	return &a
}

type organizationHasManyBudgetTagsTx struct{ tx *gorm.Association }

func (a organizationHasManyBudgetTagsTx) Find() (result []*model.BudgetTag, err error) {
	return result, a.tx.Find(&result)
}

func (a organizationHasManyBudgetTagsTx) Append(values ...*model.BudgetTag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a organizationHasManyBudgetTagsTx) Replace(values ...*model.BudgetTag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a organizationHasManyBudgetTagsTx) Delete(values ...*model.BudgetTag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a organizationHasManyBudgetTagsTx) Clear() error {
	return a.tx.Clear()
}

func (a organizationHasManyBudgetTagsTx) Count() int64 {
	return a.tx.Count()
}

func (a organizationHasManyBudgetTagsTx) Unscoped() *organizationHasManyBudgetTagsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type organizationHasManyBudgetTagAccountValues struct {
	db *gorm.DB

	field.RelationField
}

func (a organizationHasManyBudgetTagAccountValues) Where(conds ...field.Expr) *organizationHasManyBudgetTagAccountValues {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a organizationHasManyBudgetTagAccountValues) WithContext(ctx context.Context) *organizationHasManyBudgetTagAccountValues {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a organizationHasManyBudgetTagAccountValues) Session(session *gorm.Session) *organizationHasManyBudgetTagAccountValues {
	a.db = a.db.Session(session)
	return &a
}

func (a organizationHasManyBudgetTagAccountValues) Model(m *model.Organization) *organizationHasManyBudgetTagAccountValuesTx {
	return &organizationHasManyBudgetTagAccountValuesTx{a.db.Model(m).Association(a.Name())}
}

func (a organizationHasManyBudgetTagAccountValues) Unscoped() *organizationHasManyBudgetTagAccountValues {
	a.db = a.db.Unscoped()
	return &a
}

type organizationHasManyBudgetTagAccountValuesTx struct{ tx *gorm.Association }

func (a organizationHasManyBudgetTagAccountValuesTx) Find() (result []*model.BudgetTagAccountValue, err error) {
	return result, a.tx.Find(&result)
}

func (a organizationHasManyBudgetTagAccountValuesTx) Append(values ...*model.BudgetTagAccountValue) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a organizationHasManyBudgetTagAccountValuesTx) Replace(values ...*model.BudgetTagAccountValue) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a organizationHasManyBudgetTagAccountValuesTx) Delete(values ...*model.BudgetTagAccountValue) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a organizationHasManyBudgetTagAccountValuesTx) Clear() error {
	return a.tx.Clear()
}

func (a organizationHasManyBudgetTagAccountValuesTx) Count() int64 {
	return a.tx.Count()
}

func (a organizationHasManyBudgetTagAccountValuesTx) Unscoped() *organizationHasManyBudgetTagAccountValuesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type organizationHasManyBudgets struct {
	db *gorm.DB

	field.RelationField
}

func (a organizationHasManyBudgets) Where(conds ...field.Expr) *organizationHasManyBudgets {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a organizationHasManyBudgets) WithContext(ctx context.Context) *organizationHasManyBudgets {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a organizationHasManyBudgets) Session(session *gorm.Session) *organizationHasManyBudgets {
	a.db = a.db.Session(session)
	return &a
}

func (a organizationHasManyBudgets) Model(m *model.Organization) *organizationHasManyBudgetsTx {
	return &organizationHasManyBudgetsTx{a.db.Model(m).Association(a.Name())}
}

func (a organizationHasManyBudgets) Unscoped() *organizationHasManyBudgets {
	a.db = a.db.Unscoped()
	return &a
}

type organizationHasManyBudgetsTx struct{ tx *gorm.Association }

func (a organizationHasManyBudgetsTx) Find() (result []*model.Budget, err error) {
	return result, a.tx.Find(&result)
}

func (a organizationHasManyBudgetsTx) Append(values ...*model.Budget) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a organizationHasManyBudgetsTx) Replace(values ...*model.Budget) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a organizationHasManyBudgetsTx) Delete(values ...*model.Budget) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a organizationHasManyBudgetsTx) Clear() error {
	return a.tx.Clear()
}

func (a organizationHasManyBudgetsTx) Count() int64 {
	return a.tx.Count()
}

func (a organizationHasManyBudgetsTx) Unscoped() *organizationHasManyBudgetsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type organizationHasManyImportSourcePeriods struct {
	db *gorm.DB

	field.RelationField
}

func (a organizationHasManyImportSourcePeriods) Where(conds ...field.Expr) *organizationHasManyImportSourcePeriods {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a organizationHasManyImportSourcePeriods) WithContext(ctx context.Context) *organizationHasManyImportSourcePeriods {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a organizationHasManyImportSourcePeriods) Session(session *gorm.Session) *organizationHasManyImportSourcePeriods {
	a.db = a.db.Session(session)
	return &a
}

func (a organizationHasManyImportSourcePeriods) Model(m *model.Organization) *organizationHasManyImportSourcePeriodsTx {
	return &organizationHasManyImportSourcePeriodsTx{a.db.Model(m).Association(a.Name())}
}

func (a organizationHasManyImportSourcePeriods) Unscoped() *organizationHasManyImportSourcePeriods {
	a.db = a.db.Unscoped()
	return &a
}

type organizationHasManyImportSourcePeriodsTx struct{ tx *gorm.Association }

func (a organizationHasManyImportSourcePeriodsTx) Find() (result []*model.ImportSourcePeriod, err error) {
	return result, a.tx.Find(&result)
}

func (a organizationHasManyImportSourcePeriodsTx) Append(values ...*model.ImportSourcePeriod) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a organizationHasManyImportSourcePeriodsTx) Replace(values ...*model.ImportSourcePeriod) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a organizationHasManyImportSourcePeriodsTx) Delete(values ...*model.ImportSourcePeriod) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a organizationHasManyImportSourcePeriodsTx) Clear() error {
	return a.tx.Clear()
}

func (a organizationHasManyImportSourcePeriodsTx) Count() int64 {
	return a.tx.Count()
}

func (a organizationHasManyImportSourcePeriodsTx) Unscoped() *organizationHasManyImportSourcePeriodsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type organizationHasManyImportSources struct {
	db *gorm.DB

	field.RelationField
}

func (a organizationHasManyImportSources) Where(conds ...field.Expr) *organizationHasManyImportSources {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a organizationHasManyImportSources) WithContext(ctx context.Context) *organizationHasManyImportSources {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a organizationHasManyImportSources) Session(session *gorm.Session) *organizationHasManyImportSources {
	a.db = a.db.Session(session)
	return &a
}

func (a organizationHasManyImportSources) Model(m *model.Organization) *organizationHasManyImportSourcesTx {
	return &organizationHasManyImportSourcesTx{a.db.Model(m).Association(a.Name())}
}

func (a organizationHasManyImportSources) Unscoped() *organizationHasManyImportSources {
	a.db = a.db.Unscoped()
	return &a
}

type organizationHasManyImportSourcesTx struct{ tx *gorm.Association }

func (a organizationHasManyImportSourcesTx) Find() (result []*model.ImportSource, err error) {
	return result, a.tx.Find(&result)
}

func (a organizationHasManyImportSourcesTx) Append(values ...*model.ImportSource) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a organizationHasManyImportSourcesTx) Replace(values ...*model.ImportSource) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a organizationHasManyImportSourcesTx) Delete(values ...*model.ImportSource) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a organizationHasManyImportSourcesTx) Clear() error {
	return a.tx.Clear()
}

func (a organizationHasManyImportSourcesTx) Count() int64 {
	return a.tx.Count()
}

func (a organizationHasManyImportSourcesTx) Unscoped() *organizationHasManyImportSourcesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type organizationHasManyReportTemplates struct {
	db *gorm.DB

	field.RelationField
}

func (a organizationHasManyReportTemplates) Where(conds ...field.Expr) *organizationHasManyReportTemplates {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a organizationHasManyReportTemplates) WithContext(ctx context.Context) *organizationHasManyReportTemplates {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a organizationHasManyReportTemplates) Session(session *gorm.Session) *organizationHasManyReportTemplates {
	a.db = a.db.Session(session)
	return &a
}

func (a organizationHasManyReportTemplates) Model(m *model.Organization) *organizationHasManyReportTemplatesTx {
	return &organizationHasManyReportTemplatesTx{a.db.Model(m).Association(a.Name())}
}

func (a organizationHasManyReportTemplates) Unscoped() *organizationHasManyReportTemplates {
	a.db = a.db.Unscoped()
	return &a
}

type organizationHasManyReportTemplatesTx struct{ tx *gorm.Association }

func (a organizationHasManyReportTemplatesTx) Find() (result []*model.ReportTemplate, err error) {
	return result, a.tx.Find(&result)
}

func (a organizationHasManyReportTemplatesTx) Append(values ...*model.ReportTemplate) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a organizationHasManyReportTemplatesTx) Replace(values ...*model.ReportTemplate) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a organizationHasManyReportTemplatesTx) Delete(values ...*model.ReportTemplate) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a organizationHasManyReportTemplatesTx) Clear() error {
	return a.tx.Clear()
}

func (a organizationHasManyReportTemplatesTx) Count() int64 {
	return a.tx.Count()
}

func (a organizationHasManyReportTemplatesTx) Unscoped() *organizationHasManyReportTemplatesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type organizationHasManyReports struct {
	db *gorm.DB

	field.RelationField
}

func (a organizationHasManyReports) Where(conds ...field.Expr) *organizationHasManyReports {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a organizationHasManyReports) WithContext(ctx context.Context) *organizationHasManyReports {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a organizationHasManyReports) Session(session *gorm.Session) *organizationHasManyReports {
	a.db = a.db.Session(session)
	return &a
}

func (a organizationHasManyReports) Model(m *model.Organization) *organizationHasManyReportsTx {
	return &organizationHasManyReportsTx{a.db.Model(m).Association(a.Name())}
}

func (a organizationHasManyReports) Unscoped() *organizationHasManyReports {
	a.db = a.db.Unscoped()
	return &a
}

type organizationHasManyReportsTx struct{ tx *gorm.Association }

func (a organizationHasManyReportsTx) Find() (result []*model.Report, err error) {
	return result, a.tx.Find(&result)
}

func (a organizationHasManyReportsTx) Append(values ...*model.Report) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a organizationHasManyReportsTx) Replace(values ...*model.Report) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a organizationHasManyReportsTx) Delete(values ...*model.Report) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a organizationHasManyReportsTx) Clear() error {
	return a.tx.Clear()
}

func (a organizationHasManyReportsTx) Count() int64 {
	return a.tx.Count()
}

func (a organizationHasManyReportsTx) Unscoped() *organizationHasManyReportsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type organizationHasManyTransactions struct {
	db *gorm.DB

	field.RelationField
}

func (a organizationHasManyTransactions) Where(conds ...field.Expr) *organizationHasManyTransactions {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a organizationHasManyTransactions) WithContext(ctx context.Context) *organizationHasManyTransactions {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a organizationHasManyTransactions) Session(session *gorm.Session) *organizationHasManyTransactions {
	a.db = a.db.Session(session)
	return &a
}

func (a organizationHasManyTransactions) Model(m *model.Organization) *organizationHasManyTransactionsTx {
	return &organizationHasManyTransactionsTx{a.db.Model(m).Association(a.Name())}
}

func (a organizationHasManyTransactions) Unscoped() *organizationHasManyTransactions {
	a.db = a.db.Unscoped()
	return &a
}

type organizationHasManyTransactionsTx struct{ tx *gorm.Association }

func (a organizationHasManyTransactionsTx) Find() (result []*model.Transaction_, err error) {
	return result, a.tx.Find(&result)
}

func (a organizationHasManyTransactionsTx) Append(values ...*model.Transaction_) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a organizationHasManyTransactionsTx) Replace(values ...*model.Transaction_) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a organizationHasManyTransactionsTx) Delete(values ...*model.Transaction_) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a organizationHasManyTransactionsTx) Clear() error {
	return a.tx.Clear()
}

func (a organizationHasManyTransactionsTx) Count() int64 {
	return a.tx.Count()
}

func (a organizationHasManyTransactionsTx) Unscoped() *organizationHasManyTransactionsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type organizationHasManyTransactionAccountAssignments struct {
	db *gorm.DB

	field.RelationField
}

func (a organizationHasManyTransactionAccountAssignments) Where(conds ...field.Expr) *organizationHasManyTransactionAccountAssignments {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a organizationHasManyTransactionAccountAssignments) WithContext(ctx context.Context) *organizationHasManyTransactionAccountAssignments {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a organizationHasManyTransactionAccountAssignments) Session(session *gorm.Session) *organizationHasManyTransactionAccountAssignments {
	a.db = a.db.Session(session)
	return &a
}

func (a organizationHasManyTransactionAccountAssignments) Model(m *model.Organization) *organizationHasManyTransactionAccountAssignmentsTx {
	return &organizationHasManyTransactionAccountAssignmentsTx{a.db.Model(m).Association(a.Name())}
}

func (a organizationHasManyTransactionAccountAssignments) Unscoped() *organizationHasManyTransactionAccountAssignments {
	a.db = a.db.Unscoped()
	return &a
}

type organizationHasManyTransactionAccountAssignmentsTx struct{ tx *gorm.Association }

func (a organizationHasManyTransactionAccountAssignmentsTx) Find() (result []*model.TransactionAccountAssignment, err error) {
	return result, a.tx.Find(&result)
}

func (a organizationHasManyTransactionAccountAssignmentsTx) Append(values ...*model.TransactionAccountAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a organizationHasManyTransactionAccountAssignmentsTx) Replace(values ...*model.TransactionAccountAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a organizationHasManyTransactionAccountAssignmentsTx) Delete(values ...*model.TransactionAccountAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a organizationHasManyTransactionAccountAssignmentsTx) Clear() error {
	return a.tx.Clear()
}

func (a organizationHasManyTransactionAccountAssignmentsTx) Count() int64 {
	return a.tx.Count()
}

func (a organizationHasManyTransactionAccountAssignmentsTx) Unscoped() *organizationHasManyTransactionAccountAssignmentsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type organizationHasManyTransactionAccounts struct {
	db *gorm.DB

	field.RelationField
}

func (a organizationHasManyTransactionAccounts) Where(conds ...field.Expr) *organizationHasManyTransactionAccounts {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a organizationHasManyTransactionAccounts) WithContext(ctx context.Context) *organizationHasManyTransactionAccounts {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a organizationHasManyTransactionAccounts) Session(session *gorm.Session) *organizationHasManyTransactionAccounts {
	a.db = a.db.Session(session)
	return &a
}

func (a organizationHasManyTransactionAccounts) Model(m *model.Organization) *organizationHasManyTransactionAccountsTx {
	return &organizationHasManyTransactionAccountsTx{a.db.Model(m).Association(a.Name())}
}

func (a organizationHasManyTransactionAccounts) Unscoped() *organizationHasManyTransactionAccounts {
	a.db = a.db.Unscoped()
	return &a
}

type organizationHasManyTransactionAccountsTx struct{ tx *gorm.Association }

func (a organizationHasManyTransactionAccountsTx) Find() (result []*model.TransactionAccount, err error) {
	return result, a.tx.Find(&result)
}

func (a organizationHasManyTransactionAccountsTx) Append(values ...*model.TransactionAccount) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a organizationHasManyTransactionAccountsTx) Replace(values ...*model.TransactionAccount) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a organizationHasManyTransactionAccountsTx) Delete(values ...*model.TransactionAccount) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a organizationHasManyTransactionAccountsTx) Clear() error {
	return a.tx.Clear()
}

func (a organizationHasManyTransactionAccountsTx) Count() int64 {
	return a.tx.Count()
}

func (a organizationHasManyTransactionAccountsTx) Unscoped() *organizationHasManyTransactionAccountsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type organizationDo struct{ gen.DO }

type IOrganizationDo interface {
	gen.SubQuery
	Debug() IOrganizationDo
	WithContext(ctx context.Context) IOrganizationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOrganizationDo
	WriteDB() IOrganizationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOrganizationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOrganizationDo
	Not(conds ...gen.Condition) IOrganizationDo
	Or(conds ...gen.Condition) IOrganizationDo
	Select(conds ...field.Expr) IOrganizationDo
	Where(conds ...gen.Condition) IOrganizationDo
	Order(conds ...field.Expr) IOrganizationDo
	Distinct(cols ...field.Expr) IOrganizationDo
	Omit(cols ...field.Expr) IOrganizationDo
	Join(table schema.Tabler, on ...field.Expr) IOrganizationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOrganizationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOrganizationDo
	Group(cols ...field.Expr) IOrganizationDo
	Having(conds ...gen.Condition) IOrganizationDo
	Limit(limit int) IOrganizationDo
	Offset(offset int) IOrganizationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOrganizationDo
	Unscoped() IOrganizationDo
	Create(values ...*model.Organization) error
	CreateInBatches(values []*model.Organization, batchSize int) error
	Save(values ...*model.Organization) error
	First() (*model.Organization, error)
	Take() (*model.Organization, error)
	Last() (*model.Organization, error)
	Find() ([]*model.Organization, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Organization, err error)
	FindInBatches(result *[]*model.Organization, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Organization) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOrganizationDo
	Assign(attrs ...field.AssignExpr) IOrganizationDo
	Joins(fields ...field.RelationField) IOrganizationDo
	Preload(fields ...field.RelationField) IOrganizationDo
	FirstOrInit() (*model.Organization, error)
	FirstOrCreate() (*model.Organization, error)
	FindByPage(offset int, limit int) (result []*model.Organization, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOrganizationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o organizationDo) Debug() IOrganizationDo {
	return o.withDO(o.DO.Debug())
}

func (o organizationDo) WithContext(ctx context.Context) IOrganizationDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o organizationDo) ReadDB() IOrganizationDo {
	return o.Clauses(dbresolver.Read)
}

func (o organizationDo) WriteDB() IOrganizationDo {
	return o.Clauses(dbresolver.Write)
}

func (o organizationDo) Session(config *gorm.Session) IOrganizationDo {
	return o.withDO(o.DO.Session(config))
}

func (o organizationDo) Clauses(conds ...clause.Expression) IOrganizationDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o organizationDo) Returning(value interface{}, columns ...string) IOrganizationDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o organizationDo) Not(conds ...gen.Condition) IOrganizationDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o organizationDo) Or(conds ...gen.Condition) IOrganizationDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o organizationDo) Select(conds ...field.Expr) IOrganizationDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o organizationDo) Where(conds ...gen.Condition) IOrganizationDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o organizationDo) Order(conds ...field.Expr) IOrganizationDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o organizationDo) Distinct(cols ...field.Expr) IOrganizationDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o organizationDo) Omit(cols ...field.Expr) IOrganizationDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o organizationDo) Join(table schema.Tabler, on ...field.Expr) IOrganizationDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o organizationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOrganizationDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o organizationDo) RightJoin(table schema.Tabler, on ...field.Expr) IOrganizationDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o organizationDo) Group(cols ...field.Expr) IOrganizationDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o organizationDo) Having(conds ...gen.Condition) IOrganizationDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o organizationDo) Limit(limit int) IOrganizationDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o organizationDo) Offset(offset int) IOrganizationDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o organizationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOrganizationDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o organizationDo) Unscoped() IOrganizationDo {
	return o.withDO(o.DO.Unscoped())
}

func (o organizationDo) Create(values ...*model.Organization) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o organizationDo) CreateInBatches(values []*model.Organization, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o organizationDo) Save(values ...*model.Organization) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o organizationDo) First() (*model.Organization, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Organization), nil
	}
}

func (o organizationDo) Take() (*model.Organization, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Organization), nil
	}
}

func (o organizationDo) Last() (*model.Organization, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Organization), nil
	}
}

func (o organizationDo) Find() ([]*model.Organization, error) {
	result, err := o.DO.Find()
	return result.([]*model.Organization), err
}

func (o organizationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Organization, err error) {
	buf := make([]*model.Organization, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o organizationDo) FindInBatches(result *[]*model.Organization, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o organizationDo) Attrs(attrs ...field.AssignExpr) IOrganizationDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o organizationDo) Assign(attrs ...field.AssignExpr) IOrganizationDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o organizationDo) Joins(fields ...field.RelationField) IOrganizationDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o organizationDo) Preload(fields ...field.RelationField) IOrganizationDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o organizationDo) FirstOrInit() (*model.Organization, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Organization), nil
	}
}

func (o organizationDo) FirstOrCreate() (*model.Organization, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Organization), nil
	}
}

func (o organizationDo) FindByPage(offset int, limit int) (result []*model.Organization, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o organizationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o organizationDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o organizationDo) Delete(models ...*model.Organization) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *organizationDo) withDO(do gen.Dao) *organizationDo {
	o.DO = *do.(*gen.DO)
	return o
}
