// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"github.com/pixlcrashr/vsfv/pkg/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newReport(db *gorm.DB, opts ...gen.DOOption) report {
	_report := report{}

	_report.reportDo.UseDB(db, opts...)
	_report.reportDo.UseModel(&model.Report{})

	tableName := _report.reportDo.TableName()
	_report.ALL = field.NewAsterisk(tableName)
	_report.ID = field.NewField(tableName, "id")
	_report.CustomID = field.NewString(tableName, "custom_id")
	_report.OrganizationID = field.NewField(tableName, "organization_id")
	_report.DisplayName = field.NewString(tableName, "display_name")
	_report.Data = field.NewBytes(tableName, "data")
	_report.CreatedAt = field.NewTime(tableName, "created_at")
	_report.Organization = reportBelongsToOrganization{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Organization", "model.Organization"),
		AccountGroupAssignments: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			AccountGroup struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}
			Account struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevisions struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
					}
					BudgetRevision struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
				BudgetAccountValues struct {
					field.RelationField
				}
				TransactionAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditLedgerAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitLedgerAccount struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
			}
		}{
			RelationField: field.NewRelation("Organization.AccountGroupAssignments", "model.AccountGroupAssignment"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.AccountGroupAssignments.Organization", "model.Organization"),
			},
			AccountGroup: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Organization.AccountGroupAssignments.AccountGroup", "model.AccountGroup"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.AccountGroup.Organization", "model.Organization"),
				},
				AccountGroupAssignments: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.AccountGroup.AccountGroupAssignments", "model.AccountGroupAssignment"),
				},
			},
			Account: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevisions struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
					}
					BudgetRevision struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
				BudgetAccountValues struct {
					field.RelationField
				}
				TransactionAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditLedgerAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitLedgerAccount struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account", "model.Account"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.Organization", "model.Organization"),
				},
				ParentAccount: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.ParentAccount", "model.Account"),
				},
				ChildAccounts: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.ChildAccounts", "model.Account"),
				},
				AccountGroupAssignments: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.AccountGroupAssignments", "model.AccountGroupAssignment"),
				},
				BudgetRevisionAccountValues: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Budget struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevisions struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
					}
					BudgetRevision struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Organization", "model.Organization"),
					},
					Budget: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevisions struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						BudgetAccountValues struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget", "model.Budget"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.Organization", "model.Organization"),
						},
						BudgetRevisions: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions", "model.BudgetRevision"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.Organization", "model.Organization"),
							},
							Budget: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.Budget", "model.Budget"),
							},
							BudgetRevisionAccountValues: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetRevisions.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
							},
						},
						BudgetAccountValues: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues", "model.BudgetAccountValue"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Organization", "model.Organization"),
							},
							Budget: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Budget", "model.Budget"),
							},
							Account: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Budget.BudgetAccountValues.Account", "model.Account"),
							},
						},
					},
					BudgetRevision: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision", "model.BudgetRevision"),
					},
					Account: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Account", "model.Account"),
					},
				},
				BudgetAccountValues: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.BudgetAccountValues", "model.BudgetAccountValue"),
				},
				TransactionAssignments: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditLedgerAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitLedgerAccount struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments", "model.TransactionAssignment"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Organization", "model.Organization"),
					},
					Transaction: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditLedgerAccount struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}
						DebitLedgerAccount struct {
							field.RelationField
						}
						TransactionAssignments struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction", "model.Transaction_"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.Organization", "model.Organization"),
						},
						CreditLedgerAccount: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							CreditTransactions struct {
								field.RelationField
							}
							DebitTransactions struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount", "model.LedgerAccount"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.Organization", "model.Organization"),
							},
							CreditTransactions: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.CreditTransactions", "model.Transaction_"),
							},
							DebitTransactions: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.CreditLedgerAccount.DebitTransactions", "model.Transaction_"),
							},
						},
						DebitLedgerAccount: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.DebitLedgerAccount", "model.LedgerAccount"),
						},
						TransactionAssignments: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Transaction.TransactionAssignments", "model.TransactionAssignment"),
						},
					},
					Account: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Organization.AccountGroupAssignments.Account.TransactionAssignments.Account", "model.Account"),
					},
				},
			},
		},
		AccountGroups: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.AccountGroups", "model.AccountGroup"),
		},
		Accounts: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.Accounts", "model.Account"),
		},
		BudgetRevisions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.BudgetRevisions", "model.BudgetRevision"),
		},
		BudgetRevisionAccountValues: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
		},
		BudgetAccountValues: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.BudgetAccountValues", "model.BudgetAccountValue"),
		},
		Budgets: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.Budgets", "model.Budget"),
		},
		LedgerYears: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Organization.LedgerYears", "model.LedgerYear"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.LedgerYears.Organization", "model.Organization"),
			},
		},
		LedgerAccounts: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.LedgerAccounts", "model.LedgerAccount"),
		},
		ReportTemplates: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Organization.ReportTemplates", "model.ReportTemplate"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.ReportTemplates.Organization", "model.Organization"),
			},
		},
		Reports: struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Organization.Reports", "model.Report"),
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.Reports.Organization", "model.Organization"),
			},
		},
		Transactions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.Transactions", "model.Transaction_"),
		},
		TransactionAssignments: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Organization.TransactionAssignments", "model.TransactionAssignment"),
		},
		GroupOrganizations: struct {
			field.RelationField
			UserGroup struct {
				field.RelationField
				GroupOrganizations struct {
					field.RelationField
				}
			}
			Organization struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Organization.GroupOrganizations", "model.GroupOrganization"),
			UserGroup: struct {
				field.RelationField
				GroupOrganizations struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Organization.GroupOrganizations.UserGroup", "model.UserGroup"),
				GroupOrganizations: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Organization.GroupOrganizations.UserGroup.GroupOrganizations", "model.GroupOrganization"),
				},
			},
			Organization: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Organization.GroupOrganizations.Organization", "model.Organization"),
			},
		},
	}

	_report.fillFieldMap()

	return _report
}

type report struct {
	reportDo reportDo

	ALL            field.Asterisk
	ID             field.Field
	CustomID       field.String
	OrganizationID field.Field
	DisplayName    field.String
	Data           field.Bytes
	CreatedAt      field.Time
	Organization   reportBelongsToOrganization

	fieldMap map[string]field.Expr
}

func (r report) Table(newTableName string) *report {
	r.reportDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r report) As(alias string) *report {
	r.reportDo.DO = *(r.reportDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *report) updateTableName(table string) *report {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewField(table, "id")
	r.CustomID = field.NewString(table, "custom_id")
	r.OrganizationID = field.NewField(table, "organization_id")
	r.DisplayName = field.NewString(table, "display_name")
	r.Data = field.NewBytes(table, "data")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *report) WithContext(ctx context.Context) IReportDo { return r.reportDo.WithContext(ctx) }

func (r report) TableName() string { return r.reportDo.TableName() }

func (r report) Alias() string { return r.reportDo.Alias() }

func (r report) Columns(cols ...field.Expr) gen.Columns { return r.reportDo.Columns(cols...) }

func (r *report) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *report) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 7)
	r.fieldMap["id"] = r.ID
	r.fieldMap["custom_id"] = r.CustomID
	r.fieldMap["organization_id"] = r.OrganizationID
	r.fieldMap["display_name"] = r.DisplayName
	r.fieldMap["data"] = r.Data
	r.fieldMap["created_at"] = r.CreatedAt

}

func (r report) clone(db *gorm.DB) report {
	r.reportDo.ReplaceConnPool(db.Statement.ConnPool)
	r.Organization.db = db.Session(&gorm.Session{Initialized: true})
	r.Organization.db.Statement.ConnPool = db.Statement.ConnPool
	return r
}

func (r report) replaceDB(db *gorm.DB) report {
	r.reportDo.ReplaceDB(db)
	r.Organization.db = db.Session(&gorm.Session{})
	return r
}

type reportBelongsToOrganization struct {
	db *gorm.DB

	field.RelationField

	AccountGroupAssignments struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
		AccountGroup struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			AccountGroupAssignments struct {
				field.RelationField
			}
		}
		Account struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			ParentAccount struct {
				field.RelationField
			}
			ChildAccounts struct {
				field.RelationField
			}
			AccountGroupAssignments struct {
				field.RelationField
			}
			BudgetRevisionAccountValues struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Budget struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					BudgetRevisions struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
						}
						BudgetRevisionAccountValues struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
				}
				BudgetRevision struct {
					field.RelationField
				}
				Account struct {
					field.RelationField
				}
			}
			BudgetAccountValues struct {
				field.RelationField
			}
			TransactionAssignments struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				Transaction struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					CreditLedgerAccount struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						CreditTransactions struct {
							field.RelationField
						}
						DebitTransactions struct {
							field.RelationField
						}
					}
					DebitLedgerAccount struct {
						field.RelationField
					}
					TransactionAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
				}
			}
		}
	}
	AccountGroups struct {
		field.RelationField
	}
	Accounts struct {
		field.RelationField
	}
	BudgetRevisions struct {
		field.RelationField
	}
	BudgetRevisionAccountValues struct {
		field.RelationField
	}
	BudgetAccountValues struct {
		field.RelationField
	}
	Budgets struct {
		field.RelationField
	}
	LedgerYears struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
	}
	LedgerAccounts struct {
		field.RelationField
	}
	ReportTemplates struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
	}
	Reports struct {
		field.RelationField
		Organization struct {
			field.RelationField
		}
	}
	Transactions struct {
		field.RelationField
	}
	TransactionAssignments struct {
		field.RelationField
	}
	GroupOrganizations struct {
		field.RelationField
		UserGroup struct {
			field.RelationField
			GroupOrganizations struct {
				field.RelationField
			}
		}
		Organization struct {
			field.RelationField
		}
	}
}

func (a reportBelongsToOrganization) Where(conds ...field.Expr) *reportBelongsToOrganization {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a reportBelongsToOrganization) WithContext(ctx context.Context) *reportBelongsToOrganization {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a reportBelongsToOrganization) Session(session *gorm.Session) *reportBelongsToOrganization {
	a.db = a.db.Session(session)
	return &a
}

func (a reportBelongsToOrganization) Model(m *model.Report) *reportBelongsToOrganizationTx {
	return &reportBelongsToOrganizationTx{a.db.Model(m).Association(a.Name())}
}

func (a reportBelongsToOrganization) Unscoped() *reportBelongsToOrganization {
	a.db = a.db.Unscoped()
	return &a
}

type reportBelongsToOrganizationTx struct{ tx *gorm.Association }

func (a reportBelongsToOrganizationTx) Find() (result *model.Organization, err error) {
	return result, a.tx.Find(&result)
}

func (a reportBelongsToOrganizationTx) Append(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a reportBelongsToOrganizationTx) Replace(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a reportBelongsToOrganizationTx) Delete(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a reportBelongsToOrganizationTx) Clear() error {
	return a.tx.Clear()
}

func (a reportBelongsToOrganizationTx) Count() int64 {
	return a.tx.Count()
}

func (a reportBelongsToOrganizationTx) Unscoped() *reportBelongsToOrganizationTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type reportDo struct{ gen.DO }

type IReportDo interface {
	gen.SubQuery
	Debug() IReportDo
	WithContext(ctx context.Context) IReportDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IReportDo
	WriteDB() IReportDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IReportDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IReportDo
	Not(conds ...gen.Condition) IReportDo
	Or(conds ...gen.Condition) IReportDo
	Select(conds ...field.Expr) IReportDo
	Where(conds ...gen.Condition) IReportDo
	Order(conds ...field.Expr) IReportDo
	Distinct(cols ...field.Expr) IReportDo
	Omit(cols ...field.Expr) IReportDo
	Join(table schema.Tabler, on ...field.Expr) IReportDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IReportDo
	RightJoin(table schema.Tabler, on ...field.Expr) IReportDo
	Group(cols ...field.Expr) IReportDo
	Having(conds ...gen.Condition) IReportDo
	Limit(limit int) IReportDo
	Offset(offset int) IReportDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IReportDo
	Unscoped() IReportDo
	Create(values ...*model.Report) error
	CreateInBatches(values []*model.Report, batchSize int) error
	Save(values ...*model.Report) error
	First() (*model.Report, error)
	Take() (*model.Report, error)
	Last() (*model.Report, error)
	Find() ([]*model.Report, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Report, err error)
	FindInBatches(result *[]*model.Report, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Report) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IReportDo
	Assign(attrs ...field.AssignExpr) IReportDo
	Joins(fields ...field.RelationField) IReportDo
	Preload(fields ...field.RelationField) IReportDo
	FirstOrInit() (*model.Report, error)
	FirstOrCreate() (*model.Report, error)
	FindByPage(offset int, limit int) (result []*model.Report, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IReportDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r reportDo) Debug() IReportDo {
	return r.withDO(r.DO.Debug())
}

func (r reportDo) WithContext(ctx context.Context) IReportDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r reportDo) ReadDB() IReportDo {
	return r.Clauses(dbresolver.Read)
}

func (r reportDo) WriteDB() IReportDo {
	return r.Clauses(dbresolver.Write)
}

func (r reportDo) Session(config *gorm.Session) IReportDo {
	return r.withDO(r.DO.Session(config))
}

func (r reportDo) Clauses(conds ...clause.Expression) IReportDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r reportDo) Returning(value interface{}, columns ...string) IReportDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r reportDo) Not(conds ...gen.Condition) IReportDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r reportDo) Or(conds ...gen.Condition) IReportDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r reportDo) Select(conds ...field.Expr) IReportDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r reportDo) Where(conds ...gen.Condition) IReportDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r reportDo) Order(conds ...field.Expr) IReportDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r reportDo) Distinct(cols ...field.Expr) IReportDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r reportDo) Omit(cols ...field.Expr) IReportDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r reportDo) Join(table schema.Tabler, on ...field.Expr) IReportDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r reportDo) LeftJoin(table schema.Tabler, on ...field.Expr) IReportDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r reportDo) RightJoin(table schema.Tabler, on ...field.Expr) IReportDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r reportDo) Group(cols ...field.Expr) IReportDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r reportDo) Having(conds ...gen.Condition) IReportDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r reportDo) Limit(limit int) IReportDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r reportDo) Offset(offset int) IReportDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r reportDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IReportDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r reportDo) Unscoped() IReportDo {
	return r.withDO(r.DO.Unscoped())
}

func (r reportDo) Create(values ...*model.Report) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r reportDo) CreateInBatches(values []*model.Report, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r reportDo) Save(values ...*model.Report) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r reportDo) First() (*model.Report, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Report), nil
	}
}

func (r reportDo) Take() (*model.Report, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Report), nil
	}
}

func (r reportDo) Last() (*model.Report, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Report), nil
	}
}

func (r reportDo) Find() ([]*model.Report, error) {
	result, err := r.DO.Find()
	return result.([]*model.Report), err
}

func (r reportDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Report, err error) {
	buf := make([]*model.Report, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r reportDo) FindInBatches(result *[]*model.Report, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r reportDo) Attrs(attrs ...field.AssignExpr) IReportDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r reportDo) Assign(attrs ...field.AssignExpr) IReportDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r reportDo) Joins(fields ...field.RelationField) IReportDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r reportDo) Preload(fields ...field.RelationField) IReportDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r reportDo) FirstOrInit() (*model.Report, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Report), nil
	}
}

func (r reportDo) FirstOrCreate() (*model.Report, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Report), nil
	}
}

func (r reportDo) FindByPage(offset int, limit int) (result []*model.Report, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r reportDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r reportDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r reportDo) Delete(models ...*model.Report) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *reportDo) withDO(do gen.Dao) *reportDo {
	r.DO = *do.(*gen.DO)
	return r
}
