// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"github.com/pixlcrashr/vsfv/pkg/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newTransactionAccount(db *gorm.DB, opts ...gen.DOOption) transactionAccount {
	_transactionAccount := transactionAccount{}

	_transactionAccount.transactionAccountDo.UseDB(db, opts...)
	_transactionAccount.transactionAccountDo.UseModel(&model.TransactionAccount{})

	tableName := _transactionAccount.transactionAccountDo.TableName()
	_transactionAccount.ALL = field.NewAsterisk(tableName)
	_transactionAccount.ID = field.NewField(tableName, "id")
	_transactionAccount.OrganizationID = field.NewField(tableName, "organization_id")
	_transactionAccount.Code = field.NewString(tableName, "code")
	_transactionAccount.ImportSourceID = field.NewField(tableName, "import_source_id")
	_transactionAccount.DisplayName = field.NewString(tableName, "display_name")
	_transactionAccount.DisplayDescription = field.NewString(tableName, "display_description")
	_transactionAccount.UpdatedAt = field.NewTime(tableName, "updated_at")
	_transactionAccount.CreatedAt = field.NewTime(tableName, "created_at")
	_transactionAccount.CreditTransactions = transactionAccountHasManyCreditTransactions{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("CreditTransactions", "model.Transaction_"),
		Organization: struct {
			field.RelationField
			AccountGroupAssignments struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetRevisionAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevision struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								BudgetRevisions struct {
									field.RelationField
								}
								BudgetAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
					}
					TransactionAccountAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
				}
			}
			AccountGroups struct {
				field.RelationField
			}
			Accounts struct {
				field.RelationField
			}
			BudgetRevisions struct {
				field.RelationField
			}
			BudgetRevisionAccountValues struct {
				field.RelationField
			}
			BudgetAccountValues struct {
				field.RelationField
			}
			Budgets struct {
				field.RelationField
			}
			ImportSourcePeriods struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ImportSource struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					TransactionAccounts struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						ImportSource struct {
							field.RelationField
						}
						CreditTransactions struct {
							field.RelationField
						}
						DebitTransactions struct {
							field.RelationField
						}
					}
					ImportSourcePeriods struct {
						field.RelationField
					}
				}
			}
			ImportSources struct {
				field.RelationField
			}
			ReportTemplates struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Reports struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}
			Transactions struct {
				field.RelationField
			}
			TransactionAccountAssignments struct {
				field.RelationField
			}
			TransactionAccounts struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("CreditTransactions.Organization", "model.Organization"),
			AccountGroupAssignments: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
				Account struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetRevisionAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevision struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								BudgetRevisions struct {
									field.RelationField
								}
								BudgetAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
					}
					TransactionAccountAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments", "model.AccountGroupAssignment"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Organization", "model.Organization"),
				},
				AccountGroup: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.AccountGroup", "model.AccountGroup"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.AccountGroup.Organization", "model.Organization"),
					},
					AccountGroupAssignments: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.AccountGroup.AccountGroupAssignments", "model.AccountGroupAssignment"),
					},
				},
				Account: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ParentAccount struct {
						field.RelationField
					}
					ChildAccounts struct {
						field.RelationField
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
					BudgetRevisionAccountValues struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevision struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								BudgetRevisions struct {
									field.RelationField
								}
								BudgetAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}
					BudgetAccountValues struct {
						field.RelationField
					}
					TransactionAccountAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account", "model.Account"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.Organization", "model.Organization"),
					},
					ParentAccount: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.ParentAccount", "model.Account"),
					},
					ChildAccounts: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.ChildAccounts", "model.Account"),
					},
					AccountGroupAssignments: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.AccountGroupAssignments", "model.AccountGroupAssignment"),
					},
					BudgetRevisionAccountValues: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						BudgetRevision struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								BudgetRevisions struct {
									field.RelationField
								}
								BudgetAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}
						Account struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Organization", "model.Organization"),
						},
						BudgetRevision: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							Budget struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								BudgetRevisions struct {
									field.RelationField
								}
								BudgetAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
							}
							BudgetRevisionAccountValues struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision", "model.BudgetRevision"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision.Organization", "model.Organization"),
							},
							Budget: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								BudgetRevisions struct {
									field.RelationField
								}
								BudgetAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}
							}{
								RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision.Budget", "model.Budget"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision.Budget.Organization", "model.Organization"),
								},
								BudgetRevisions: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision.Budget.BudgetRevisions", "model.BudgetRevision"),
								},
								BudgetAccountValues: struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
									}
									Account struct {
										field.RelationField
									}
								}{
									RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision.Budget.BudgetAccountValues", "model.BudgetAccountValue"),
									Organization: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision.Budget.BudgetAccountValues.Organization", "model.Organization"),
									},
									Budget: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision.Budget.BudgetAccountValues.Budget", "model.Budget"),
									},
									Account: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision.Budget.BudgetAccountValues.Account", "model.Account"),
									},
								},
							},
							BudgetRevisionAccountValues: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.BudgetRevision.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
							},
						},
						Account: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetRevisionAccountValues.Account", "model.Account"),
						},
					},
					BudgetAccountValues: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.BudgetAccountValues", "model.BudgetAccountValue"),
					},
					TransactionAccountAssignments: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Transaction struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Organization", "model.Organization"),
						},
						Transaction: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction", "model.Transaction_"),
						},
						Account: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Account", "model.Account"),
						},
					},
				},
			},
			AccountGroups: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.AccountGroups", "model.AccountGroup"),
			},
			Accounts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.Accounts", "model.Account"),
			},
			BudgetRevisions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.BudgetRevisions", "model.BudgetRevision"),
			},
			BudgetRevisionAccountValues: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.BudgetRevisionAccountValues", "model.BudgetRevisionAccountValue"),
			},
			BudgetAccountValues: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.BudgetAccountValues", "model.BudgetAccountValue"),
			},
			Budgets: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.Budgets", "model.Budget"),
			},
			ImportSourcePeriods: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ImportSource struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					TransactionAccounts struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						ImportSource struct {
							field.RelationField
						}
						CreditTransactions struct {
							field.RelationField
						}
						DebitTransactions struct {
							field.RelationField
						}
					}
					ImportSourcePeriods struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.ImportSourcePeriods", "model.ImportSourcePeriod"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.ImportSourcePeriods.Organization", "model.Organization"),
				},
				ImportSource: struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					TransactionAccounts struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						ImportSource struct {
							field.RelationField
						}
						CreditTransactions struct {
							field.RelationField
						}
						DebitTransactions struct {
							field.RelationField
						}
					}
					ImportSourcePeriods struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.ImportSourcePeriods.ImportSource", "model.ImportSource"),
					Organization: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.ImportSourcePeriods.ImportSource.Organization", "model.Organization"),
					},
					TransactionAccounts: struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						ImportSource struct {
							field.RelationField
						}
						CreditTransactions struct {
							field.RelationField
						}
						DebitTransactions struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.ImportSourcePeriods.ImportSource.TransactionAccounts", "model.TransactionAccount"),
						Organization: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.ImportSourcePeriods.ImportSource.TransactionAccounts.Organization", "model.Organization"),
						},
						ImportSource: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.ImportSourcePeriods.ImportSource.TransactionAccounts.ImportSource", "model.ImportSource"),
						},
						CreditTransactions: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.ImportSourcePeriods.ImportSource.TransactionAccounts.CreditTransactions", "model.Transaction_"),
						},
						DebitTransactions: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("CreditTransactions.Organization.ImportSourcePeriods.ImportSource.TransactionAccounts.DebitTransactions", "model.Transaction_"),
						},
					},
					ImportSourcePeriods: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("CreditTransactions.Organization.ImportSourcePeriods.ImportSource.ImportSourcePeriods", "model.ImportSourcePeriod"),
					},
				},
			},
			ImportSources: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.ImportSources", "model.ImportSource"),
			},
			ReportTemplates: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.ReportTemplates", "model.ReportTemplate"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.ReportTemplates.Organization", "model.Organization"),
				},
			},
			Reports: struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.Reports", "model.Report"),
				Organization: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("CreditTransactions.Organization.Reports.Organization", "model.Organization"),
				},
			},
			Transactions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.Transactions", "model.Transaction_"),
			},
			TransactionAccountAssignments: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
			},
			TransactionAccounts: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("CreditTransactions.Organization.TransactionAccounts", "model.TransactionAccount"),
			},
		},
		CreditTransactionAccount: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("CreditTransactions.CreditTransactionAccount", "model.TransactionAccount"),
		},
		DebitTransactionAccount: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("CreditTransactions.DebitTransactionAccount", "model.TransactionAccount"),
		},
		TransactionAccountAssignments: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("CreditTransactions.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
		},
	}

	_transactionAccount.DebitTransactions = transactionAccountHasManyDebitTransactions{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("DebitTransactions", "model.Transaction_"),
	}

	_transactionAccount.Organization = transactionAccountBelongsToOrganization{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Organization", "model.Organization"),
	}

	_transactionAccount.ImportSource = transactionAccountBelongsToImportSource{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ImportSource", "model.ImportSource"),
	}

	_transactionAccount.fillFieldMap()

	return _transactionAccount
}

type transactionAccount struct {
	transactionAccountDo transactionAccountDo

	ALL                field.Asterisk
	ID                 field.Field
	OrganizationID     field.Field
	Code               field.String
	ImportSourceID     field.Field
	DisplayName        field.String
	DisplayDescription field.String
	UpdatedAt          field.Time
	CreatedAt          field.Time
	CreditTransactions transactionAccountHasManyCreditTransactions

	DebitTransactions transactionAccountHasManyDebitTransactions

	Organization transactionAccountBelongsToOrganization

	ImportSource transactionAccountBelongsToImportSource

	fieldMap map[string]field.Expr
}

func (t transactionAccount) Table(newTableName string) *transactionAccount {
	t.transactionAccountDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t transactionAccount) As(alias string) *transactionAccount {
	t.transactionAccountDo.DO = *(t.transactionAccountDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *transactionAccount) updateTableName(table string) *transactionAccount {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewField(table, "id")
	t.OrganizationID = field.NewField(table, "organization_id")
	t.Code = field.NewString(table, "code")
	t.ImportSourceID = field.NewField(table, "import_source_id")
	t.DisplayName = field.NewString(table, "display_name")
	t.DisplayDescription = field.NewString(table, "display_description")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.CreatedAt = field.NewTime(table, "created_at")

	t.fillFieldMap()

	return t
}

func (t *transactionAccount) WithContext(ctx context.Context) ITransactionAccountDo {
	return t.transactionAccountDo.WithContext(ctx)
}

func (t transactionAccount) TableName() string { return t.transactionAccountDo.TableName() }

func (t transactionAccount) Alias() string { return t.transactionAccountDo.Alias() }

func (t transactionAccount) Columns(cols ...field.Expr) gen.Columns {
	return t.transactionAccountDo.Columns(cols...)
}

func (t *transactionAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *transactionAccount) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 12)
	t.fieldMap["id"] = t.ID
	t.fieldMap["organization_id"] = t.OrganizationID
	t.fieldMap["code"] = t.Code
	t.fieldMap["import_source_id"] = t.ImportSourceID
	t.fieldMap["display_name"] = t.DisplayName
	t.fieldMap["display_description"] = t.DisplayDescription
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["created_at"] = t.CreatedAt

}

func (t transactionAccount) clone(db *gorm.DB) transactionAccount {
	t.transactionAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	t.CreditTransactions.db = db.Session(&gorm.Session{Initialized: true})
	t.CreditTransactions.db.Statement.ConnPool = db.Statement.ConnPool
	t.DebitTransactions.db = db.Session(&gorm.Session{Initialized: true})
	t.DebitTransactions.db.Statement.ConnPool = db.Statement.ConnPool
	t.Organization.db = db.Session(&gorm.Session{Initialized: true})
	t.Organization.db.Statement.ConnPool = db.Statement.ConnPool
	t.ImportSource.db = db.Session(&gorm.Session{Initialized: true})
	t.ImportSource.db.Statement.ConnPool = db.Statement.ConnPool
	return t
}

func (t transactionAccount) replaceDB(db *gorm.DB) transactionAccount {
	t.transactionAccountDo.ReplaceDB(db)
	t.CreditTransactions.db = db.Session(&gorm.Session{})
	t.DebitTransactions.db = db.Session(&gorm.Session{})
	t.Organization.db = db.Session(&gorm.Session{})
	t.ImportSource.db = db.Session(&gorm.Session{})
	return t
}

type transactionAccountHasManyCreditTransactions struct {
	db *gorm.DB

	field.RelationField

	Organization struct {
		field.RelationField
		AccountGroupAssignments struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			AccountGroup struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}
			Account struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				ParentAccount struct {
					field.RelationField
				}
				ChildAccounts struct {
					field.RelationField
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
				BudgetRevisionAccountValues struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					BudgetRevision struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						Budget struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							BudgetRevisions struct {
								field.RelationField
							}
							BudgetAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Budget struct {
									field.RelationField
								}
								Account struct {
									field.RelationField
								}
							}
						}
						BudgetRevisionAccountValues struct {
							field.RelationField
						}
					}
					Account struct {
						field.RelationField
					}
				}
				BudgetAccountValues struct {
					field.RelationField
				}
				TransactionAccountAssignments struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					Transaction struct {
						field.RelationField
					}
					Account struct {
						field.RelationField
					}
				}
			}
		}
		AccountGroups struct {
			field.RelationField
		}
		Accounts struct {
			field.RelationField
		}
		BudgetRevisions struct {
			field.RelationField
		}
		BudgetRevisionAccountValues struct {
			field.RelationField
		}
		BudgetAccountValues struct {
			field.RelationField
		}
		Budgets struct {
			field.RelationField
		}
		ImportSourcePeriods struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
			ImportSource struct {
				field.RelationField
				Organization struct {
					field.RelationField
				}
				TransactionAccounts struct {
					field.RelationField
					Organization struct {
						field.RelationField
					}
					ImportSource struct {
						field.RelationField
					}
					CreditTransactions struct {
						field.RelationField
					}
					DebitTransactions struct {
						field.RelationField
					}
				}
				ImportSourcePeriods struct {
					field.RelationField
				}
			}
		}
		ImportSources struct {
			field.RelationField
		}
		ReportTemplates struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		Reports struct {
			field.RelationField
			Organization struct {
				field.RelationField
			}
		}
		Transactions struct {
			field.RelationField
		}
		TransactionAccountAssignments struct {
			field.RelationField
		}
		TransactionAccounts struct {
			field.RelationField
		}
	}
	CreditTransactionAccount struct {
		field.RelationField
	}
	DebitTransactionAccount struct {
		field.RelationField
	}
	TransactionAccountAssignments struct {
		field.RelationField
	}
}

func (a transactionAccountHasManyCreditTransactions) Where(conds ...field.Expr) *transactionAccountHasManyCreditTransactions {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a transactionAccountHasManyCreditTransactions) WithContext(ctx context.Context) *transactionAccountHasManyCreditTransactions {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a transactionAccountHasManyCreditTransactions) Session(session *gorm.Session) *transactionAccountHasManyCreditTransactions {
	a.db = a.db.Session(session)
	return &a
}

func (a transactionAccountHasManyCreditTransactions) Model(m *model.TransactionAccount) *transactionAccountHasManyCreditTransactionsTx {
	return &transactionAccountHasManyCreditTransactionsTx{a.db.Model(m).Association(a.Name())}
}

func (a transactionAccountHasManyCreditTransactions) Unscoped() *transactionAccountHasManyCreditTransactions {
	a.db = a.db.Unscoped()
	return &a
}

type transactionAccountHasManyCreditTransactionsTx struct{ tx *gorm.Association }

func (a transactionAccountHasManyCreditTransactionsTx) Find() (result []*model.Transaction_, err error) {
	return result, a.tx.Find(&result)
}

func (a transactionAccountHasManyCreditTransactionsTx) Append(values ...*model.Transaction_) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a transactionAccountHasManyCreditTransactionsTx) Replace(values ...*model.Transaction_) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a transactionAccountHasManyCreditTransactionsTx) Delete(values ...*model.Transaction_) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a transactionAccountHasManyCreditTransactionsTx) Clear() error {
	return a.tx.Clear()
}

func (a transactionAccountHasManyCreditTransactionsTx) Count() int64 {
	return a.tx.Count()
}

func (a transactionAccountHasManyCreditTransactionsTx) Unscoped() *transactionAccountHasManyCreditTransactionsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type transactionAccountHasManyDebitTransactions struct {
	db *gorm.DB

	field.RelationField
}

func (a transactionAccountHasManyDebitTransactions) Where(conds ...field.Expr) *transactionAccountHasManyDebitTransactions {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a transactionAccountHasManyDebitTransactions) WithContext(ctx context.Context) *transactionAccountHasManyDebitTransactions {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a transactionAccountHasManyDebitTransactions) Session(session *gorm.Session) *transactionAccountHasManyDebitTransactions {
	a.db = a.db.Session(session)
	return &a
}

func (a transactionAccountHasManyDebitTransactions) Model(m *model.TransactionAccount) *transactionAccountHasManyDebitTransactionsTx {
	return &transactionAccountHasManyDebitTransactionsTx{a.db.Model(m).Association(a.Name())}
}

func (a transactionAccountHasManyDebitTransactions) Unscoped() *transactionAccountHasManyDebitTransactions {
	a.db = a.db.Unscoped()
	return &a
}

type transactionAccountHasManyDebitTransactionsTx struct{ tx *gorm.Association }

func (a transactionAccountHasManyDebitTransactionsTx) Find() (result []*model.Transaction_, err error) {
	return result, a.tx.Find(&result)
}

func (a transactionAccountHasManyDebitTransactionsTx) Append(values ...*model.Transaction_) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a transactionAccountHasManyDebitTransactionsTx) Replace(values ...*model.Transaction_) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a transactionAccountHasManyDebitTransactionsTx) Delete(values ...*model.Transaction_) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a transactionAccountHasManyDebitTransactionsTx) Clear() error {
	return a.tx.Clear()
}

func (a transactionAccountHasManyDebitTransactionsTx) Count() int64 {
	return a.tx.Count()
}

func (a transactionAccountHasManyDebitTransactionsTx) Unscoped() *transactionAccountHasManyDebitTransactionsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type transactionAccountBelongsToOrganization struct {
	db *gorm.DB

	field.RelationField
}

func (a transactionAccountBelongsToOrganization) Where(conds ...field.Expr) *transactionAccountBelongsToOrganization {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a transactionAccountBelongsToOrganization) WithContext(ctx context.Context) *transactionAccountBelongsToOrganization {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a transactionAccountBelongsToOrganization) Session(session *gorm.Session) *transactionAccountBelongsToOrganization {
	a.db = a.db.Session(session)
	return &a
}

func (a transactionAccountBelongsToOrganization) Model(m *model.TransactionAccount) *transactionAccountBelongsToOrganizationTx {
	return &transactionAccountBelongsToOrganizationTx{a.db.Model(m).Association(a.Name())}
}

func (a transactionAccountBelongsToOrganization) Unscoped() *transactionAccountBelongsToOrganization {
	a.db = a.db.Unscoped()
	return &a
}

type transactionAccountBelongsToOrganizationTx struct{ tx *gorm.Association }

func (a transactionAccountBelongsToOrganizationTx) Find() (result *model.Organization, err error) {
	return result, a.tx.Find(&result)
}

func (a transactionAccountBelongsToOrganizationTx) Append(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a transactionAccountBelongsToOrganizationTx) Replace(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a transactionAccountBelongsToOrganizationTx) Delete(values ...*model.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a transactionAccountBelongsToOrganizationTx) Clear() error {
	return a.tx.Clear()
}

func (a transactionAccountBelongsToOrganizationTx) Count() int64 {
	return a.tx.Count()
}

func (a transactionAccountBelongsToOrganizationTx) Unscoped() *transactionAccountBelongsToOrganizationTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type transactionAccountBelongsToImportSource struct {
	db *gorm.DB

	field.RelationField
}

func (a transactionAccountBelongsToImportSource) Where(conds ...field.Expr) *transactionAccountBelongsToImportSource {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a transactionAccountBelongsToImportSource) WithContext(ctx context.Context) *transactionAccountBelongsToImportSource {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a transactionAccountBelongsToImportSource) Session(session *gorm.Session) *transactionAccountBelongsToImportSource {
	a.db = a.db.Session(session)
	return &a
}

func (a transactionAccountBelongsToImportSource) Model(m *model.TransactionAccount) *transactionAccountBelongsToImportSourceTx {
	return &transactionAccountBelongsToImportSourceTx{a.db.Model(m).Association(a.Name())}
}

func (a transactionAccountBelongsToImportSource) Unscoped() *transactionAccountBelongsToImportSource {
	a.db = a.db.Unscoped()
	return &a
}

type transactionAccountBelongsToImportSourceTx struct{ tx *gorm.Association }

func (a transactionAccountBelongsToImportSourceTx) Find() (result *model.ImportSource, err error) {
	return result, a.tx.Find(&result)
}

func (a transactionAccountBelongsToImportSourceTx) Append(values ...*model.ImportSource) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a transactionAccountBelongsToImportSourceTx) Replace(values ...*model.ImportSource) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a transactionAccountBelongsToImportSourceTx) Delete(values ...*model.ImportSource) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a transactionAccountBelongsToImportSourceTx) Clear() error {
	return a.tx.Clear()
}

func (a transactionAccountBelongsToImportSourceTx) Count() int64 {
	return a.tx.Count()
}

func (a transactionAccountBelongsToImportSourceTx) Unscoped() *transactionAccountBelongsToImportSourceTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type transactionAccountDo struct{ gen.DO }

type ITransactionAccountDo interface {
	gen.SubQuery
	Debug() ITransactionAccountDo
	WithContext(ctx context.Context) ITransactionAccountDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITransactionAccountDo
	WriteDB() ITransactionAccountDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITransactionAccountDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITransactionAccountDo
	Not(conds ...gen.Condition) ITransactionAccountDo
	Or(conds ...gen.Condition) ITransactionAccountDo
	Select(conds ...field.Expr) ITransactionAccountDo
	Where(conds ...gen.Condition) ITransactionAccountDo
	Order(conds ...field.Expr) ITransactionAccountDo
	Distinct(cols ...field.Expr) ITransactionAccountDo
	Omit(cols ...field.Expr) ITransactionAccountDo
	Join(table schema.Tabler, on ...field.Expr) ITransactionAccountDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITransactionAccountDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITransactionAccountDo
	Group(cols ...field.Expr) ITransactionAccountDo
	Having(conds ...gen.Condition) ITransactionAccountDo
	Limit(limit int) ITransactionAccountDo
	Offset(offset int) ITransactionAccountDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITransactionAccountDo
	Unscoped() ITransactionAccountDo
	Create(values ...*model.TransactionAccount) error
	CreateInBatches(values []*model.TransactionAccount, batchSize int) error
	Save(values ...*model.TransactionAccount) error
	First() (*model.TransactionAccount, error)
	Take() (*model.TransactionAccount, error)
	Last() (*model.TransactionAccount, error)
	Find() ([]*model.TransactionAccount, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TransactionAccount, err error)
	FindInBatches(result *[]*model.TransactionAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TransactionAccount) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITransactionAccountDo
	Assign(attrs ...field.AssignExpr) ITransactionAccountDo
	Joins(fields ...field.RelationField) ITransactionAccountDo
	Preload(fields ...field.RelationField) ITransactionAccountDo
	FirstOrInit() (*model.TransactionAccount, error)
	FirstOrCreate() (*model.TransactionAccount, error)
	FindByPage(offset int, limit int) (result []*model.TransactionAccount, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITransactionAccountDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t transactionAccountDo) Debug() ITransactionAccountDo {
	return t.withDO(t.DO.Debug())
}

func (t transactionAccountDo) WithContext(ctx context.Context) ITransactionAccountDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t transactionAccountDo) ReadDB() ITransactionAccountDo {
	return t.Clauses(dbresolver.Read)
}

func (t transactionAccountDo) WriteDB() ITransactionAccountDo {
	return t.Clauses(dbresolver.Write)
}

func (t transactionAccountDo) Session(config *gorm.Session) ITransactionAccountDo {
	return t.withDO(t.DO.Session(config))
}

func (t transactionAccountDo) Clauses(conds ...clause.Expression) ITransactionAccountDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t transactionAccountDo) Returning(value interface{}, columns ...string) ITransactionAccountDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t transactionAccountDo) Not(conds ...gen.Condition) ITransactionAccountDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t transactionAccountDo) Or(conds ...gen.Condition) ITransactionAccountDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t transactionAccountDo) Select(conds ...field.Expr) ITransactionAccountDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t transactionAccountDo) Where(conds ...gen.Condition) ITransactionAccountDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t transactionAccountDo) Order(conds ...field.Expr) ITransactionAccountDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t transactionAccountDo) Distinct(cols ...field.Expr) ITransactionAccountDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t transactionAccountDo) Omit(cols ...field.Expr) ITransactionAccountDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t transactionAccountDo) Join(table schema.Tabler, on ...field.Expr) ITransactionAccountDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t transactionAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITransactionAccountDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t transactionAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) ITransactionAccountDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t transactionAccountDo) Group(cols ...field.Expr) ITransactionAccountDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t transactionAccountDo) Having(conds ...gen.Condition) ITransactionAccountDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t transactionAccountDo) Limit(limit int) ITransactionAccountDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t transactionAccountDo) Offset(offset int) ITransactionAccountDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t transactionAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITransactionAccountDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t transactionAccountDo) Unscoped() ITransactionAccountDo {
	return t.withDO(t.DO.Unscoped())
}

func (t transactionAccountDo) Create(values ...*model.TransactionAccount) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t transactionAccountDo) CreateInBatches(values []*model.TransactionAccount, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t transactionAccountDo) Save(values ...*model.TransactionAccount) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t transactionAccountDo) First() (*model.TransactionAccount, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TransactionAccount), nil
	}
}

func (t transactionAccountDo) Take() (*model.TransactionAccount, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TransactionAccount), nil
	}
}

func (t transactionAccountDo) Last() (*model.TransactionAccount, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TransactionAccount), nil
	}
}

func (t transactionAccountDo) Find() ([]*model.TransactionAccount, error) {
	result, err := t.DO.Find()
	return result.([]*model.TransactionAccount), err
}

func (t transactionAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TransactionAccount, err error) {
	buf := make([]*model.TransactionAccount, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t transactionAccountDo) FindInBatches(result *[]*model.TransactionAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t transactionAccountDo) Attrs(attrs ...field.AssignExpr) ITransactionAccountDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t transactionAccountDo) Assign(attrs ...field.AssignExpr) ITransactionAccountDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t transactionAccountDo) Joins(fields ...field.RelationField) ITransactionAccountDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t transactionAccountDo) Preload(fields ...field.RelationField) ITransactionAccountDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t transactionAccountDo) FirstOrInit() (*model.TransactionAccount, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TransactionAccount), nil
	}
}

func (t transactionAccountDo) FirstOrCreate() (*model.TransactionAccount, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TransactionAccount), nil
	}
}

func (t transactionAccountDo) FindByPage(offset int, limit int) (result []*model.TransactionAccount, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t transactionAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t transactionAccountDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t transactionAccountDo) Delete(models ...*model.TransactionAccount) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *transactionAccountDo) withDO(do gen.Dao) *transactionAccountDo {
	t.DO = *do.(*gen.DO)
	return t
}
