// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"github.com/pixlcrashr/vsfv/pkg/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newView(db *gorm.DB, opts ...gen.DOOption) view {
	_view := view{}

	_view.viewDo.UseDB(db, opts...)
	_view.viewDo.UseModel(&model.View{})

	tableName := _view.viewDo.TableName()
	_view.ALL = field.NewAsterisk(tableName)
	_view.ID = field.NewField(tableName, "id")
	_view.DisplayName = field.NewString(tableName, "display_name")
	_view.DisplayDescription = field.NewString(tableName, "display_description")
	_view.UpdatedAt = field.NewTime(tableName, "updated_at")
	_view.CreatedAt = field.NewTime(tableName, "created_at")
	_view.ViewAccountAssignments = viewHasManyViewAccountAssignments{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ViewAccountAssignments", "model.ViewAccountAssignment"),
		View: struct {
			field.RelationField
			ViewAccountAssignments struct {
				field.RelationField
			}
			ViewAccountGroupAssignments struct {
				field.RelationField
				View struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
						AccountGroupAssignments struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							AccountGroup struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								ParentAccount struct {
									field.RelationField
								}
								ChildAccounts struct {
									field.RelationField
								}
								AccountGroupAssignments struct {
									field.RelationField
								}
								BudgetTagAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									BudgetTag struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										Budget struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											BudgetTags struct {
												field.RelationField
											}
										}
										BudgetTagAccountValues struct {
											field.RelationField
										}
									}
									Account struct {
										field.RelationField
									}
								}
								TransactionAccountAssignments struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Transaction struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										CreditTransactionAccount struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											ImportSource struct {
												field.RelationField
												Organization struct {
													field.RelationField
												}
												TransactionAccounts struct {
													field.RelationField
												}
												ImportSourcePeriods struct {
													field.RelationField
													Organization struct {
														field.RelationField
													}
													ImportSource struct {
														field.RelationField
													}
												}
											}
											CreditTransactions struct {
												field.RelationField
											}
											DebitTransactions struct {
												field.RelationField
											}
										}
										DebitTransactionAccount struct {
											field.RelationField
										}
										TransactionAccountAssignments struct {
											field.RelationField
										}
									}
									Account struct {
										field.RelationField
									}
								}
							}
						}
						AccountGroups struct {
							field.RelationField
						}
						Accounts struct {
							field.RelationField
						}
						BudgetTags struct {
							field.RelationField
						}
						BudgetTagAccountValues struct {
							field.RelationField
						}
						Budgets struct {
							field.RelationField
						}
						ImportSourcePeriods struct {
							field.RelationField
						}
						ImportSources struct {
							field.RelationField
						}
						ReportTemplates struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
						}
						Reports struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
						}
						Transactions struct {
							field.RelationField
						}
						TransactionAccountAssignments struct {
							field.RelationField
						}
						TransactionAccounts struct {
							field.RelationField
						}
						UserGroups struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
						}
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
			}
			ViewBudgetAssignments struct {
				field.RelationField
				View struct {
					field.RelationField
				}
				Budget struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("ViewAccountAssignments.View", "model.View"),
			ViewAccountAssignments: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountAssignments", "model.ViewAccountAssignment"),
			},
			ViewAccountGroupAssignments: struct {
				field.RelationField
				View struct {
					field.RelationField
				}
				AccountGroup struct {
					field.RelationField
					Organization struct {
						field.RelationField
						AccountGroupAssignments struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							AccountGroup struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								ParentAccount struct {
									field.RelationField
								}
								ChildAccounts struct {
									field.RelationField
								}
								AccountGroupAssignments struct {
									field.RelationField
								}
								BudgetTagAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									BudgetTag struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										Budget struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											BudgetTags struct {
												field.RelationField
											}
										}
										BudgetTagAccountValues struct {
											field.RelationField
										}
									}
									Account struct {
										field.RelationField
									}
								}
								TransactionAccountAssignments struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Transaction struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										CreditTransactionAccount struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											ImportSource struct {
												field.RelationField
												Organization struct {
													field.RelationField
												}
												TransactionAccounts struct {
													field.RelationField
												}
												ImportSourcePeriods struct {
													field.RelationField
													Organization struct {
														field.RelationField
													}
													ImportSource struct {
														field.RelationField
													}
												}
											}
											CreditTransactions struct {
												field.RelationField
											}
											DebitTransactions struct {
												field.RelationField
											}
										}
										DebitTransactionAccount struct {
											field.RelationField
										}
										TransactionAccountAssignments struct {
											field.RelationField
										}
									}
									Account struct {
										field.RelationField
									}
								}
							}
						}
						AccountGroups struct {
							field.RelationField
						}
						Accounts struct {
							field.RelationField
						}
						BudgetTags struct {
							field.RelationField
						}
						BudgetTagAccountValues struct {
							field.RelationField
						}
						Budgets struct {
							field.RelationField
						}
						ImportSourcePeriods struct {
							field.RelationField
						}
						ImportSources struct {
							field.RelationField
						}
						ReportTemplates struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
						}
						Reports struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
						}
						Transactions struct {
							field.RelationField
						}
						TransactionAccountAssignments struct {
							field.RelationField
						}
						TransactionAccounts struct {
							field.RelationField
						}
						UserGroups struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
						}
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments", "model.ViewAccountGroupAssignment"),
				View: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.View", "model.View"),
				},
				AccountGroup: struct {
					field.RelationField
					Organization struct {
						field.RelationField
						AccountGroupAssignments struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							AccountGroup struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								ParentAccount struct {
									field.RelationField
								}
								ChildAccounts struct {
									field.RelationField
								}
								AccountGroupAssignments struct {
									field.RelationField
								}
								BudgetTagAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									BudgetTag struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										Budget struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											BudgetTags struct {
												field.RelationField
											}
										}
										BudgetTagAccountValues struct {
											field.RelationField
										}
									}
									Account struct {
										field.RelationField
									}
								}
								TransactionAccountAssignments struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Transaction struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										CreditTransactionAccount struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											ImportSource struct {
												field.RelationField
												Organization struct {
													field.RelationField
												}
												TransactionAccounts struct {
													field.RelationField
												}
												ImportSourcePeriods struct {
													field.RelationField
													Organization struct {
														field.RelationField
													}
													ImportSource struct {
														field.RelationField
													}
												}
											}
											CreditTransactions struct {
												field.RelationField
											}
											DebitTransactions struct {
												field.RelationField
											}
										}
										DebitTransactionAccount struct {
											field.RelationField
										}
										TransactionAccountAssignments struct {
											field.RelationField
										}
									}
									Account struct {
										field.RelationField
									}
								}
							}
						}
						AccountGroups struct {
							field.RelationField
						}
						Accounts struct {
							field.RelationField
						}
						BudgetTags struct {
							field.RelationField
						}
						BudgetTagAccountValues struct {
							field.RelationField
						}
						Budgets struct {
							field.RelationField
						}
						ImportSourcePeriods struct {
							field.RelationField
						}
						ImportSources struct {
							field.RelationField
						}
						ReportTemplates struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
						}
						Reports struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
						}
						Transactions struct {
							field.RelationField
						}
						TransactionAccountAssignments struct {
							field.RelationField
						}
						TransactionAccounts struct {
							field.RelationField
						}
						UserGroups struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
						}
					}
					AccountGroupAssignments struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup", "model.AccountGroup"),
					Organization: struct {
						field.RelationField
						AccountGroupAssignments struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							AccountGroup struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								ParentAccount struct {
									field.RelationField
								}
								ChildAccounts struct {
									field.RelationField
								}
								AccountGroupAssignments struct {
									field.RelationField
								}
								BudgetTagAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									BudgetTag struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										Budget struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											BudgetTags struct {
												field.RelationField
											}
										}
										BudgetTagAccountValues struct {
											field.RelationField
										}
									}
									Account struct {
										field.RelationField
									}
								}
								TransactionAccountAssignments struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Transaction struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										CreditTransactionAccount struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											ImportSource struct {
												field.RelationField
												Organization struct {
													field.RelationField
												}
												TransactionAccounts struct {
													field.RelationField
												}
												ImportSourcePeriods struct {
													field.RelationField
													Organization struct {
														field.RelationField
													}
													ImportSource struct {
														field.RelationField
													}
												}
											}
											CreditTransactions struct {
												field.RelationField
											}
											DebitTransactions struct {
												field.RelationField
											}
										}
										DebitTransactionAccount struct {
											field.RelationField
										}
										TransactionAccountAssignments struct {
											field.RelationField
										}
									}
									Account struct {
										field.RelationField
									}
								}
							}
						}
						AccountGroups struct {
							field.RelationField
						}
						Accounts struct {
							field.RelationField
						}
						BudgetTags struct {
							field.RelationField
						}
						BudgetTagAccountValues struct {
							field.RelationField
						}
						Budgets struct {
							field.RelationField
						}
						ImportSourcePeriods struct {
							field.RelationField
						}
						ImportSources struct {
							field.RelationField
						}
						ReportTemplates struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
						}
						Reports struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
						}
						Transactions struct {
							field.RelationField
						}
						TransactionAccountAssignments struct {
							field.RelationField
						}
						TransactionAccounts struct {
							field.RelationField
						}
						UserGroups struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
						}
					}{
						RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization", "model.Organization"),
						AccountGroupAssignments: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							AccountGroup struct {
								field.RelationField
							}
							Account struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								ParentAccount struct {
									field.RelationField
								}
								ChildAccounts struct {
									field.RelationField
								}
								AccountGroupAssignments struct {
									field.RelationField
								}
								BudgetTagAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									BudgetTag struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										Budget struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											BudgetTags struct {
												field.RelationField
											}
										}
										BudgetTagAccountValues struct {
											field.RelationField
										}
									}
									Account struct {
										field.RelationField
									}
								}
								TransactionAccountAssignments struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Transaction struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										CreditTransactionAccount struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											ImportSource struct {
												field.RelationField
												Organization struct {
													field.RelationField
												}
												TransactionAccounts struct {
													field.RelationField
												}
												ImportSourcePeriods struct {
													field.RelationField
													Organization struct {
														field.RelationField
													}
													ImportSource struct {
														field.RelationField
													}
												}
											}
											CreditTransactions struct {
												field.RelationField
											}
											DebitTransactions struct {
												field.RelationField
											}
										}
										DebitTransactionAccount struct {
											field.RelationField
										}
										TransactionAccountAssignments struct {
											field.RelationField
										}
									}
									Account struct {
										field.RelationField
									}
								}
							}
						}{
							RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments", "model.AccountGroupAssignment"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Organization", "model.Organization"),
							},
							AccountGroup: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.AccountGroup", "model.AccountGroup"),
							},
							Account: struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								ParentAccount struct {
									field.RelationField
								}
								ChildAccounts struct {
									field.RelationField
								}
								AccountGroupAssignments struct {
									field.RelationField
								}
								BudgetTagAccountValues struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									BudgetTag struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										Budget struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											BudgetTags struct {
												field.RelationField
											}
										}
										BudgetTagAccountValues struct {
											field.RelationField
										}
									}
									Account struct {
										field.RelationField
									}
								}
								TransactionAccountAssignments struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Transaction struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										CreditTransactionAccount struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											ImportSource struct {
												field.RelationField
												Organization struct {
													field.RelationField
												}
												TransactionAccounts struct {
													field.RelationField
												}
												ImportSourcePeriods struct {
													field.RelationField
													Organization struct {
														field.RelationField
													}
													ImportSource struct {
														field.RelationField
													}
												}
											}
											CreditTransactions struct {
												field.RelationField
											}
											DebitTransactions struct {
												field.RelationField
											}
										}
										DebitTransactionAccount struct {
											field.RelationField
										}
										TransactionAccountAssignments struct {
											field.RelationField
										}
									}
									Account struct {
										field.RelationField
									}
								}
							}{
								RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account", "model.Account"),
								Organization: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.Organization", "model.Organization"),
								},
								ParentAccount: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.ParentAccount", "model.Account"),
								},
								ChildAccounts: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.ChildAccounts", "model.Account"),
								},
								AccountGroupAssignments: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.AccountGroupAssignments", "model.AccountGroupAssignment"),
								},
								BudgetTagAccountValues: struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									BudgetTag struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										Budget struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											BudgetTags struct {
												field.RelationField
											}
										}
										BudgetTagAccountValues struct {
											field.RelationField
										}
									}
									Account struct {
										field.RelationField
									}
								}{
									RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.BudgetTagAccountValues", "model.BudgetTagAccountValue"),
									Organization: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.Organization", "model.Organization"),
									},
									BudgetTag: struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										Budget struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											BudgetTags struct {
												field.RelationField
											}
										}
										BudgetTagAccountValues struct {
											field.RelationField
										}
									}{
										RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.BudgetTag", "model.BudgetTag"),
										Organization: struct {
											field.RelationField
										}{
											RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.BudgetTag.Organization", "model.Organization"),
										},
										Budget: struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											BudgetTags struct {
												field.RelationField
											}
										}{
											RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.BudgetTag.Budget", "model.Budget"),
											Organization: struct {
												field.RelationField
											}{
												RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.BudgetTag.Budget.Organization", "model.Organization"),
											},
											BudgetTags: struct {
												field.RelationField
											}{
												RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.BudgetTag.Budget.BudgetTags", "model.BudgetTag"),
											},
										},
										BudgetTagAccountValues: struct {
											field.RelationField
										}{
											RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.BudgetTag.BudgetTagAccountValues", "model.BudgetTagAccountValue"),
										},
									},
									Account: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.BudgetTagAccountValues.Account", "model.Account"),
									},
								},
								TransactionAccountAssignments: struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Transaction struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										CreditTransactionAccount struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											ImportSource struct {
												field.RelationField
												Organization struct {
													field.RelationField
												}
												TransactionAccounts struct {
													field.RelationField
												}
												ImportSourcePeriods struct {
													field.RelationField
													Organization struct {
														field.RelationField
													}
													ImportSource struct {
														field.RelationField
													}
												}
											}
											CreditTransactions struct {
												field.RelationField
											}
											DebitTransactions struct {
												field.RelationField
											}
										}
										DebitTransactionAccount struct {
											field.RelationField
										}
										TransactionAccountAssignments struct {
											field.RelationField
										}
									}
									Account struct {
										field.RelationField
									}
								}{
									RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
									Organization: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Organization", "model.Organization"),
									},
									Transaction: struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										CreditTransactionAccount struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											ImportSource struct {
												field.RelationField
												Organization struct {
													field.RelationField
												}
												TransactionAccounts struct {
													field.RelationField
												}
												ImportSourcePeriods struct {
													field.RelationField
													Organization struct {
														field.RelationField
													}
													ImportSource struct {
														field.RelationField
													}
												}
											}
											CreditTransactions struct {
												field.RelationField
											}
											DebitTransactions struct {
												field.RelationField
											}
										}
										DebitTransactionAccount struct {
											field.RelationField
										}
										TransactionAccountAssignments struct {
											field.RelationField
										}
									}{
										RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction", "model.Transaction_"),
										Organization: struct {
											field.RelationField
										}{
											RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.Organization", "model.Organization"),
										},
										CreditTransactionAccount: struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											ImportSource struct {
												field.RelationField
												Organization struct {
													field.RelationField
												}
												TransactionAccounts struct {
													field.RelationField
												}
												ImportSourcePeriods struct {
													field.RelationField
													Organization struct {
														field.RelationField
													}
													ImportSource struct {
														field.RelationField
													}
												}
											}
											CreditTransactions struct {
												field.RelationField
											}
											DebitTransactions struct {
												field.RelationField
											}
										}{
											RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount", "model.TransactionAccount"),
											Organization: struct {
												field.RelationField
											}{
												RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.Organization", "model.Organization"),
											},
											ImportSource: struct {
												field.RelationField
												Organization struct {
													field.RelationField
												}
												TransactionAccounts struct {
													field.RelationField
												}
												ImportSourcePeriods struct {
													field.RelationField
													Organization struct {
														field.RelationField
													}
													ImportSource struct {
														field.RelationField
													}
												}
											}{
												RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource", "model.ImportSource"),
												Organization: struct {
													field.RelationField
												}{
													RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.Organization", "model.Organization"),
												},
												TransactionAccounts: struct {
													field.RelationField
												}{
													RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.TransactionAccounts", "model.TransactionAccount"),
												},
												ImportSourcePeriods: struct {
													field.RelationField
													Organization struct {
														field.RelationField
													}
													ImportSource struct {
														field.RelationField
													}
												}{
													RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.ImportSourcePeriods", "model.ImportSourcePeriod"),
													Organization: struct {
														field.RelationField
													}{
														RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.ImportSourcePeriods.Organization", "model.Organization"),
													},
													ImportSource: struct {
														field.RelationField
													}{
														RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.ImportSource.ImportSourcePeriods.ImportSource", "model.ImportSource"),
													},
												},
											},
											CreditTransactions: struct {
												field.RelationField
											}{
												RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.CreditTransactions", "model.Transaction_"),
											},
											DebitTransactions: struct {
												field.RelationField
											}{
												RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.CreditTransactionAccount.DebitTransactions", "model.Transaction_"),
											},
										},
										DebitTransactionAccount: struct {
											field.RelationField
										}{
											RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.DebitTransactionAccount", "model.TransactionAccount"),
										},
										TransactionAccountAssignments: struct {
											field.RelationField
										}{
											RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Transaction.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
										},
									},
									Account: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroupAssignments.Account.TransactionAccountAssignments.Account", "model.Account"),
									},
								},
							},
						},
						AccountGroups: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.AccountGroups", "model.AccountGroup"),
						},
						Accounts: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.Accounts", "model.Account"),
						},
						BudgetTags: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.BudgetTags", "model.BudgetTag"),
						},
						BudgetTagAccountValues: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.BudgetTagAccountValues", "model.BudgetTagAccountValue"),
						},
						Budgets: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.Budgets", "model.Budget"),
						},
						ImportSourcePeriods: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.ImportSourcePeriods", "model.ImportSourcePeriod"),
						},
						ImportSources: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.ImportSources", "model.ImportSource"),
						},
						ReportTemplates: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.ReportTemplates", "model.ReportTemplate"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.ReportTemplates.Organization", "model.Organization"),
							},
						},
						Reports: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.Reports", "model.Report"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.Reports.Organization", "model.Organization"),
							},
						},
						Transactions: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.Transactions", "model.Transaction_"),
						},
						TransactionAccountAssignments: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.TransactionAccountAssignments", "model.TransactionAccountAssignment"),
						},
						TransactionAccounts: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.TransactionAccounts", "model.TransactionAccount"),
						},
						UserGroups: struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.UserGroups", "model.UserGroup"),
							Organization: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.Organization.UserGroups.Organization", "model.Organization"),
							},
						},
					},
					AccountGroupAssignments: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ViewAccountAssignments.View.ViewAccountGroupAssignments.AccountGroup.AccountGroupAssignments", "model.AccountGroupAssignment"),
					},
				},
			},
			ViewBudgetAssignments: struct {
				field.RelationField
				View struct {
					field.RelationField
				}
				Budget struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("ViewAccountAssignments.View.ViewBudgetAssignments", "model.ViewBudgetAssignment"),
				View: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ViewAccountAssignments.View.ViewBudgetAssignments.View", "model.View"),
				},
				Budget: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ViewAccountAssignments.View.ViewBudgetAssignments.Budget", "model.Budget"),
				},
			},
		},
		Account: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("ViewAccountAssignments.Account", "model.Account"),
		},
	}

	_view.ViewAccountGroupAssignments = viewHasManyViewAccountGroupAssignments{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ViewAccountGroupAssignments", "model.ViewAccountGroupAssignment"),
	}

	_view.ViewBudgetAssignments = viewHasManyViewBudgetAssignments{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ViewBudgetAssignments", "model.ViewBudgetAssignment"),
	}

	_view.fillFieldMap()

	return _view
}

type view struct {
	viewDo viewDo

	ALL                    field.Asterisk
	ID                     field.Field
	DisplayName            field.String
	DisplayDescription     field.String
	UpdatedAt              field.Time
	CreatedAt              field.Time
	ViewAccountAssignments viewHasManyViewAccountAssignments

	ViewAccountGroupAssignments viewHasManyViewAccountGroupAssignments

	ViewBudgetAssignments viewHasManyViewBudgetAssignments

	fieldMap map[string]field.Expr
}

func (v view) Table(newTableName string) *view {
	v.viewDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v view) As(alias string) *view {
	v.viewDo.DO = *(v.viewDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *view) updateTableName(table string) *view {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewField(table, "id")
	v.DisplayName = field.NewString(table, "display_name")
	v.DisplayDescription = field.NewString(table, "display_description")
	v.UpdatedAt = field.NewTime(table, "updated_at")
	v.CreatedAt = field.NewTime(table, "created_at")

	v.fillFieldMap()

	return v
}

func (v *view) WithContext(ctx context.Context) IViewDo { return v.viewDo.WithContext(ctx) }

func (v view) TableName() string { return v.viewDo.TableName() }

func (v view) Alias() string { return v.viewDo.Alias() }

func (v view) Columns(cols ...field.Expr) gen.Columns { return v.viewDo.Columns(cols...) }

func (v *view) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *view) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 8)
	v.fieldMap["id"] = v.ID
	v.fieldMap["display_name"] = v.DisplayName
	v.fieldMap["display_description"] = v.DisplayDescription
	v.fieldMap["updated_at"] = v.UpdatedAt
	v.fieldMap["created_at"] = v.CreatedAt

}

func (v view) clone(db *gorm.DB) view {
	v.viewDo.ReplaceConnPool(db.Statement.ConnPool)
	v.ViewAccountAssignments.db = db.Session(&gorm.Session{Initialized: true})
	v.ViewAccountAssignments.db.Statement.ConnPool = db.Statement.ConnPool
	v.ViewAccountGroupAssignments.db = db.Session(&gorm.Session{Initialized: true})
	v.ViewAccountGroupAssignments.db.Statement.ConnPool = db.Statement.ConnPool
	v.ViewBudgetAssignments.db = db.Session(&gorm.Session{Initialized: true})
	v.ViewBudgetAssignments.db.Statement.ConnPool = db.Statement.ConnPool
	return v
}

func (v view) replaceDB(db *gorm.DB) view {
	v.viewDo.ReplaceDB(db)
	v.ViewAccountAssignments.db = db.Session(&gorm.Session{})
	v.ViewAccountGroupAssignments.db = db.Session(&gorm.Session{})
	v.ViewBudgetAssignments.db = db.Session(&gorm.Session{})
	return v
}

type viewHasManyViewAccountAssignments struct {
	db *gorm.DB

	field.RelationField

	View struct {
		field.RelationField
		ViewAccountAssignments struct {
			field.RelationField
		}
		ViewAccountGroupAssignments struct {
			field.RelationField
			View struct {
				field.RelationField
			}
			AccountGroup struct {
				field.RelationField
				Organization struct {
					field.RelationField
					AccountGroupAssignments struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
						AccountGroup struct {
							field.RelationField
						}
						Account struct {
							field.RelationField
							Organization struct {
								field.RelationField
							}
							ParentAccount struct {
								field.RelationField
							}
							ChildAccounts struct {
								field.RelationField
							}
							AccountGroupAssignments struct {
								field.RelationField
							}
							BudgetTagAccountValues struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								BudgetTag struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									Budget struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										BudgetTags struct {
											field.RelationField
										}
									}
									BudgetTagAccountValues struct {
										field.RelationField
									}
								}
								Account struct {
									field.RelationField
								}
							}
							TransactionAccountAssignments struct {
								field.RelationField
								Organization struct {
									field.RelationField
								}
								Transaction struct {
									field.RelationField
									Organization struct {
										field.RelationField
									}
									CreditTransactionAccount struct {
										field.RelationField
										Organization struct {
											field.RelationField
										}
										ImportSource struct {
											field.RelationField
											Organization struct {
												field.RelationField
											}
											TransactionAccounts struct {
												field.RelationField
											}
											ImportSourcePeriods struct {
												field.RelationField
												Organization struct {
													field.RelationField
												}
												ImportSource struct {
													field.RelationField
												}
											}
										}
										CreditTransactions struct {
											field.RelationField
										}
										DebitTransactions struct {
											field.RelationField
										}
									}
									DebitTransactionAccount struct {
										field.RelationField
									}
									TransactionAccountAssignments struct {
										field.RelationField
									}
								}
								Account struct {
									field.RelationField
								}
							}
						}
					}
					AccountGroups struct {
						field.RelationField
					}
					Accounts struct {
						field.RelationField
					}
					BudgetTags struct {
						field.RelationField
					}
					BudgetTagAccountValues struct {
						field.RelationField
					}
					Budgets struct {
						field.RelationField
					}
					ImportSourcePeriods struct {
						field.RelationField
					}
					ImportSources struct {
						field.RelationField
					}
					ReportTemplates struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
					}
					Reports struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
					}
					Transactions struct {
						field.RelationField
					}
					TransactionAccountAssignments struct {
						field.RelationField
					}
					TransactionAccounts struct {
						field.RelationField
					}
					UserGroups struct {
						field.RelationField
						Organization struct {
							field.RelationField
						}
					}
				}
				AccountGroupAssignments struct {
					field.RelationField
				}
			}
		}
		ViewBudgetAssignments struct {
			field.RelationField
			View struct {
				field.RelationField
			}
			Budget struct {
				field.RelationField
			}
		}
	}
	Account struct {
		field.RelationField
	}
}

func (a viewHasManyViewAccountAssignments) Where(conds ...field.Expr) *viewHasManyViewAccountAssignments {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a viewHasManyViewAccountAssignments) WithContext(ctx context.Context) *viewHasManyViewAccountAssignments {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a viewHasManyViewAccountAssignments) Session(session *gorm.Session) *viewHasManyViewAccountAssignments {
	a.db = a.db.Session(session)
	return &a
}

func (a viewHasManyViewAccountAssignments) Model(m *model.View) *viewHasManyViewAccountAssignmentsTx {
	return &viewHasManyViewAccountAssignmentsTx{a.db.Model(m).Association(a.Name())}
}

func (a viewHasManyViewAccountAssignments) Unscoped() *viewHasManyViewAccountAssignments {
	a.db = a.db.Unscoped()
	return &a
}

type viewHasManyViewAccountAssignmentsTx struct{ tx *gorm.Association }

func (a viewHasManyViewAccountAssignmentsTx) Find() (result []*model.ViewAccountAssignment, err error) {
	return result, a.tx.Find(&result)
}

func (a viewHasManyViewAccountAssignmentsTx) Append(values ...*model.ViewAccountAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a viewHasManyViewAccountAssignmentsTx) Replace(values ...*model.ViewAccountAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a viewHasManyViewAccountAssignmentsTx) Delete(values ...*model.ViewAccountAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a viewHasManyViewAccountAssignmentsTx) Clear() error {
	return a.tx.Clear()
}

func (a viewHasManyViewAccountAssignmentsTx) Count() int64 {
	return a.tx.Count()
}

func (a viewHasManyViewAccountAssignmentsTx) Unscoped() *viewHasManyViewAccountAssignmentsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type viewHasManyViewAccountGroupAssignments struct {
	db *gorm.DB

	field.RelationField
}

func (a viewHasManyViewAccountGroupAssignments) Where(conds ...field.Expr) *viewHasManyViewAccountGroupAssignments {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a viewHasManyViewAccountGroupAssignments) WithContext(ctx context.Context) *viewHasManyViewAccountGroupAssignments {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a viewHasManyViewAccountGroupAssignments) Session(session *gorm.Session) *viewHasManyViewAccountGroupAssignments {
	a.db = a.db.Session(session)
	return &a
}

func (a viewHasManyViewAccountGroupAssignments) Model(m *model.View) *viewHasManyViewAccountGroupAssignmentsTx {
	return &viewHasManyViewAccountGroupAssignmentsTx{a.db.Model(m).Association(a.Name())}
}

func (a viewHasManyViewAccountGroupAssignments) Unscoped() *viewHasManyViewAccountGroupAssignments {
	a.db = a.db.Unscoped()
	return &a
}

type viewHasManyViewAccountGroupAssignmentsTx struct{ tx *gorm.Association }

func (a viewHasManyViewAccountGroupAssignmentsTx) Find() (result []*model.ViewAccountGroupAssignment, err error) {
	return result, a.tx.Find(&result)
}

func (a viewHasManyViewAccountGroupAssignmentsTx) Append(values ...*model.ViewAccountGroupAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a viewHasManyViewAccountGroupAssignmentsTx) Replace(values ...*model.ViewAccountGroupAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a viewHasManyViewAccountGroupAssignmentsTx) Delete(values ...*model.ViewAccountGroupAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a viewHasManyViewAccountGroupAssignmentsTx) Clear() error {
	return a.tx.Clear()
}

func (a viewHasManyViewAccountGroupAssignmentsTx) Count() int64 {
	return a.tx.Count()
}

func (a viewHasManyViewAccountGroupAssignmentsTx) Unscoped() *viewHasManyViewAccountGroupAssignmentsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type viewHasManyViewBudgetAssignments struct {
	db *gorm.DB

	field.RelationField
}

func (a viewHasManyViewBudgetAssignments) Where(conds ...field.Expr) *viewHasManyViewBudgetAssignments {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a viewHasManyViewBudgetAssignments) WithContext(ctx context.Context) *viewHasManyViewBudgetAssignments {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a viewHasManyViewBudgetAssignments) Session(session *gorm.Session) *viewHasManyViewBudgetAssignments {
	a.db = a.db.Session(session)
	return &a
}

func (a viewHasManyViewBudgetAssignments) Model(m *model.View) *viewHasManyViewBudgetAssignmentsTx {
	return &viewHasManyViewBudgetAssignmentsTx{a.db.Model(m).Association(a.Name())}
}

func (a viewHasManyViewBudgetAssignments) Unscoped() *viewHasManyViewBudgetAssignments {
	a.db = a.db.Unscoped()
	return &a
}

type viewHasManyViewBudgetAssignmentsTx struct{ tx *gorm.Association }

func (a viewHasManyViewBudgetAssignmentsTx) Find() (result []*model.ViewBudgetAssignment, err error) {
	return result, a.tx.Find(&result)
}

func (a viewHasManyViewBudgetAssignmentsTx) Append(values ...*model.ViewBudgetAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a viewHasManyViewBudgetAssignmentsTx) Replace(values ...*model.ViewBudgetAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a viewHasManyViewBudgetAssignmentsTx) Delete(values ...*model.ViewBudgetAssignment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a viewHasManyViewBudgetAssignmentsTx) Clear() error {
	return a.tx.Clear()
}

func (a viewHasManyViewBudgetAssignmentsTx) Count() int64 {
	return a.tx.Count()
}

func (a viewHasManyViewBudgetAssignmentsTx) Unscoped() *viewHasManyViewBudgetAssignmentsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type viewDo struct{ gen.DO }

type IViewDo interface {
	gen.SubQuery
	Debug() IViewDo
	WithContext(ctx context.Context) IViewDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IViewDo
	WriteDB() IViewDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IViewDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IViewDo
	Not(conds ...gen.Condition) IViewDo
	Or(conds ...gen.Condition) IViewDo
	Select(conds ...field.Expr) IViewDo
	Where(conds ...gen.Condition) IViewDo
	Order(conds ...field.Expr) IViewDo
	Distinct(cols ...field.Expr) IViewDo
	Omit(cols ...field.Expr) IViewDo
	Join(table schema.Tabler, on ...field.Expr) IViewDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IViewDo
	RightJoin(table schema.Tabler, on ...field.Expr) IViewDo
	Group(cols ...field.Expr) IViewDo
	Having(conds ...gen.Condition) IViewDo
	Limit(limit int) IViewDo
	Offset(offset int) IViewDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IViewDo
	Unscoped() IViewDo
	Create(values ...*model.View) error
	CreateInBatches(values []*model.View, batchSize int) error
	Save(values ...*model.View) error
	First() (*model.View, error)
	Take() (*model.View, error)
	Last() (*model.View, error)
	Find() ([]*model.View, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.View, err error)
	FindInBatches(result *[]*model.View, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.View) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IViewDo
	Assign(attrs ...field.AssignExpr) IViewDo
	Joins(fields ...field.RelationField) IViewDo
	Preload(fields ...field.RelationField) IViewDo
	FirstOrInit() (*model.View, error)
	FirstOrCreate() (*model.View, error)
	FindByPage(offset int, limit int) (result []*model.View, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IViewDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v viewDo) Debug() IViewDo {
	return v.withDO(v.DO.Debug())
}

func (v viewDo) WithContext(ctx context.Context) IViewDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v viewDo) ReadDB() IViewDo {
	return v.Clauses(dbresolver.Read)
}

func (v viewDo) WriteDB() IViewDo {
	return v.Clauses(dbresolver.Write)
}

func (v viewDo) Session(config *gorm.Session) IViewDo {
	return v.withDO(v.DO.Session(config))
}

func (v viewDo) Clauses(conds ...clause.Expression) IViewDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v viewDo) Returning(value interface{}, columns ...string) IViewDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v viewDo) Not(conds ...gen.Condition) IViewDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v viewDo) Or(conds ...gen.Condition) IViewDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v viewDo) Select(conds ...field.Expr) IViewDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v viewDo) Where(conds ...gen.Condition) IViewDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v viewDo) Order(conds ...field.Expr) IViewDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v viewDo) Distinct(cols ...field.Expr) IViewDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v viewDo) Omit(cols ...field.Expr) IViewDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v viewDo) Join(table schema.Tabler, on ...field.Expr) IViewDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v viewDo) LeftJoin(table schema.Tabler, on ...field.Expr) IViewDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v viewDo) RightJoin(table schema.Tabler, on ...field.Expr) IViewDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v viewDo) Group(cols ...field.Expr) IViewDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v viewDo) Having(conds ...gen.Condition) IViewDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v viewDo) Limit(limit int) IViewDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v viewDo) Offset(offset int) IViewDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v viewDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IViewDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v viewDo) Unscoped() IViewDo {
	return v.withDO(v.DO.Unscoped())
}

func (v viewDo) Create(values ...*model.View) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v viewDo) CreateInBatches(values []*model.View, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v viewDo) Save(values ...*model.View) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v viewDo) First() (*model.View, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.View), nil
	}
}

func (v viewDo) Take() (*model.View, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.View), nil
	}
}

func (v viewDo) Last() (*model.View, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.View), nil
	}
}

func (v viewDo) Find() ([]*model.View, error) {
	result, err := v.DO.Find()
	return result.([]*model.View), err
}

func (v viewDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.View, err error) {
	buf := make([]*model.View, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v viewDo) FindInBatches(result *[]*model.View, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v viewDo) Attrs(attrs ...field.AssignExpr) IViewDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v viewDo) Assign(attrs ...field.AssignExpr) IViewDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v viewDo) Joins(fields ...field.RelationField) IViewDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v viewDo) Preload(fields ...field.RelationField) IViewDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v viewDo) FirstOrInit() (*model.View, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.View), nil
	}
}

func (v viewDo) FirstOrCreate() (*model.View, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.View), nil
	}
}

func (v viewDo) FindByPage(offset int, limit int) (result []*model.View, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v viewDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v viewDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v viewDo) Delete(models ...*model.View) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *viewDo) withDO(do gen.Dao) *viewDo {
	v.DO = *do.(*gen.DO)
	return v
}
