/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountGroupAssignment } from '../../models/account-group-assignment';
import { CreateAccountGroupAssignmentRequestBody } from '../../models/create-account-group-assignment-request-body';

export interface CreateAccountGroupAssignment$Params {
  accountGroupId: string;
      body: CreateAccountGroupAssignmentRequestBody
}

export function createAccountGroupAssignment(http: HttpClient, rootUrl: string, params: CreateAccountGroupAssignment$Params, context?: HttpContext): Observable<StrictHttpResponse<AccountGroupAssignment>> {
  const rb = new RequestBuilder(rootUrl, createAccountGroupAssignment.PATH, 'post');
  if (params) {
    rb.path('accountGroupId', params.accountGroupId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AccountGroupAssignment>;
    })
  );
}

createAccountGroupAssignment.PATH = '/v1/accountGroups/{accountGroupId}/assignments';
