/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateImportSourceRequestBody } from '../../models/create-import-source-request-body';
import { ImportSource } from '../../models/import-source';

export interface CreateImportSource$Params {
      body: CreateImportSourceRequestBody
}

export function createImportSource(http: HttpClient, rootUrl: string, params: CreateImportSource$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportSource>> {
  const rb = new RequestBuilder(rootUrl, createImportSource.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImportSource>;
    })
  );
}

createImportSource.PATH = '/v1/importSources';
