/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListImportSourcesResponseBody } from '../../models/list-import-sources-response-body';

export interface ListImportSources$Params {

/**
 * Import sources per page (max 100)
 */
  pageSize?: number;

/**
 * Page number (1-indexed)
 */
  page?: number;

/**
 * Filter by display name prefix
 */
  displayName?: string;

/**
 * Order by field (e.g. 'displayName', 'createTime desc')
 */
  orderBy?: string;
}

export function listImportSources(http: HttpClient, rootUrl: string, params?: ListImportSources$Params, context?: HttpContext): Observable<StrictHttpResponse<ListImportSourcesResponseBody>> {
  const rb = new RequestBuilder(rootUrl, listImportSources.PATH, 'get');
  if (params) {
    rb.query('pageSize', params.pageSize, {"explode":false});
    rb.query('page', params.page, {"explode":false});
    rb.query('displayName', params.displayName, {"explode":false});
    rb.query('orderBy', params.orderBy, {"explode":false});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListImportSourcesResponseBody>;
    })
  );
}

listImportSources.PATH = '/v1/importSources';
