/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BudgetRevision } from '../../models/budget-revision';
import { UpdateBudgetRevisionRequestBody } from '../../models/update-budget-revision-request-body';

export interface UpdateBudgetRevision$Params {

/**
 * Budget UUID
 */
  budgetId: string;

/**
 * Revision UUID
 */
  revisionId: string;
      body: UpdateBudgetRevisionRequestBody
}

export function updateBudgetRevision(http: HttpClient, rootUrl: string, params: UpdateBudgetRevision$Params, context?: HttpContext): Observable<StrictHttpResponse<BudgetRevision>> {
  const rb = new RequestBuilder(rootUrl, updateBudgetRevision.PATH, 'patch');
  if (params) {
    rb.path('budgetId', params.budgetId, {});
    rb.path('revisionId', params.revisionId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BudgetRevision>;
    })
  );
}

updateBudgetRevision.PATH = '/v1/budgets/{budgetId}/revisions/{revisionId}';
