/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateImportSourcePeriodRequestBody } from '../../models/create-import-source-period-request-body';
import { ImportSourcePeriod } from '../../models/import-source-period';

export interface CreateImportSourcePeriod$Params {
  importSourceId: string;
      body: CreateImportSourcePeriodRequestBody
}

export function createImportSourcePeriod(http: HttpClient, rootUrl: string, params: CreateImportSourcePeriod$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportSourcePeriod>> {
  const rb = new RequestBuilder(rootUrl, createImportSourcePeriod.PATH, 'post');
  if (params) {
    rb.path('importSourceId', params.importSourceId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImportSourcePeriod>;
    })
  );
}

createImportSourcePeriod.PATH = '/v1/importSources/{importSourceId}/periods';
