/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImportSourcePeriod } from '../../models/import-source-period';

export interface GetImportSourcePeriod$Params {
  importSourceId: string;
  periodId: string;
}

export function getImportSourcePeriod(http: HttpClient, rootUrl: string, params: GetImportSourcePeriod$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportSourcePeriod>> {
  const rb = new RequestBuilder(rootUrl, getImportSourcePeriod.PATH, 'get');
  if (params) {
    rb.path('importSourceId', params.importSourceId, {});
    rb.path('periodId', params.periodId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImportSourcePeriod>;
    })
  );
}

getImportSourcePeriod.PATH = '/v1/importSources/{importSourceId}/periods/{periodId}';
