/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountGroup } from '../../models/account-group';

export interface GetAccountGroup$Params {

/**
 * Account group UUID
 */
  accountGroupId: string;
}

export function getAccountGroup(http: HttpClient, rootUrl: string, params: GetAccountGroup$Params, context?: HttpContext): Observable<StrictHttpResponse<AccountGroup>> {
  const rb = new RequestBuilder(rootUrl, getAccountGroup.PATH, 'get');
  if (params) {
    rb.path('accountGroupId', params.accountGroupId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AccountGroup>;
    })
  );
}

getAccountGroup.PATH = '/v1/accountGroups/{accountGroupId}';
