/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountGroup } from '../../models/account-group';
import { UpdateAccountGroupRequestBody } from '../../models/update-account-group-request-body';

export interface UpdateAccountGroup$Params {

/**
 * Account group UUID
 */
  accountGroupId: string;
      body: UpdateAccountGroupRequestBody
}

export function updateAccountGroup(http: HttpClient, rootUrl: string, params: UpdateAccountGroup$Params, context?: HttpContext): Observable<StrictHttpResponse<AccountGroup>> {
  const rb = new RequestBuilder(rootUrl, updateAccountGroup.PATH, 'patch');
  if (params) {
    rb.path('accountGroupId', params.accountGroupId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AccountGroup>;
    })
  );
}

updateAccountGroup.PATH = '/v1/accountGroups/{accountGroupId}';
