/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListTransactionsResponseBody } from '../../models/list-transactions-response-body';

export interface ListTransactions$Params {

/**
 * Transactions per page (max 100)
 */
  pageSize?: number;

/**
 * Opaque continuation token from the previous response; omit for the first page
 */
  pageToken?: string;

/**
 * Filter by credit transaction account ID
 */
  creditTransactionAccountId?: string;

/**
 * Filter by debit transaction account ID
 */
  debitTransactionAccountId?: string;

/**
 * Filter transactions booked on or after this date
 */
  bookedAtStart?: string;

/**
 * Filter transactions booked on or before this date
 */
  bookedAtEnd?: string;
}

export function listTransactions(http: HttpClient, rootUrl: string, params?: ListTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<ListTransactionsResponseBody>> {
  const rb = new RequestBuilder(rootUrl, listTransactions.PATH, 'get');
  if (params) {
    rb.query('pageSize', params.pageSize, {"explode":false});
    rb.query('pageToken', params.pageToken, {"explode":false});
    rb.query('creditTransactionAccountId', params.creditTransactionAccountId, {"explode":false});
    rb.query('debitTransactionAccountId', params.debitTransactionAccountId, {"explode":false});
    rb.query('bookedAtStart', params.bookedAtStart, {"explode":false});
    rb.query('bookedAtEnd', params.bookedAtEnd, {"explode":false});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListTransactionsResponseBody>;
    })
  );
}

listTransactions.PATH = '/v1/transactions';
