/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DownloadReportResponseBody } from '../../models/download-report-response-body';

export interface DownloadReport$Params {

/**
 * Report UUID
 */
  reportId: string;
}

export function downloadReport(http: HttpClient, rootUrl: string, params: DownloadReport$Params, context?: HttpContext): Observable<StrictHttpResponse<DownloadReportResponseBody>> {
  const rb = new RequestBuilder(rootUrl, downloadReport.PATH, 'get');
  if (params) {
    rb.path('reportId', params.reportId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DownloadReportResponseBody>;
    })
  );
}

downloadReport.PATH = '/v1/reports/{reportId}:download';
