/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListBudgetsResponseBody } from '../../models/list-budgets-response-body';

export interface ListBudgets$Params {

/**
 * Budgets per page (max 100)
 */
  pageSize?: number;

/**
 * Page number (1-indexed)
 */
  page?: number;

/**
 * Filter by display name prefix
 */
  displayName?: string;

/**
 * Include closed budgets (default false)
 */
  showDeleted?: boolean;

/**
 * Order by field (e.g. 'displayName', 'periodStart desc')
 */
  orderBy?: string;
}

export function listBudgets(http: HttpClient, rootUrl: string, params?: ListBudgets$Params, context?: HttpContext): Observable<StrictHttpResponse<ListBudgetsResponseBody>> {
  const rb = new RequestBuilder(rootUrl, listBudgets.PATH, 'get');
  if (params) {
    rb.query('pageSize', params.pageSize, {"explode":false});
    rb.query('page', params.page, {"explode":false});
    rb.query('displayName', params.displayName, {"explode":false});
    rb.query('showDeleted', params.showDeleted, {"explode":false});
    rb.query('orderBy', params.orderBy, {"explode":false});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListBudgetsResponseBody>;
    })
  );
}

listBudgets.PATH = '/v1/budgets';
