/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Budget } from '../../models/budget';
import { UpdateBudgetRequestBody } from '../../models/update-budget-request-body';

export interface UpdateBudget$Params {

/**
 * Budget UUID
 */
  budgetId: string;
      body: UpdateBudgetRequestBody
}

export function updateBudget(http: HttpClient, rootUrl: string, params: UpdateBudget$Params, context?: HttpContext): Observable<StrictHttpResponse<Budget>> {
  const rb = new RequestBuilder(rootUrl, updateBudget.PATH, 'patch');
  if (params) {
    rb.path('budgetId', params.budgetId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Budget>;
    })
  );
}

updateBudget.PATH = '/v1/budgets/{budgetId}';
